import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');
const read=n=>JSON.parse(fs.readFileSync(path.join(root,n),'utf8'));
const defs=read('fixtures/road-ltl/work-definitions.json'), src=read('fixtures/road-ltl/v2.3-lossless-pack.json'), flow=read('fixtures/road-ltl/queue-flow.json'), canonicalFlow=read('fixtures/road-ltl/canonical-source-flow.json'), wf=read('fixtures/road-ltl/workflow-projections.json'), counts=read('fixtures/road-ltl/counts.json'), queues=read('fixtures/road-ltl/queue-templates.json');
const errors=[],warnings=[];const assert=(x,m)=>(x||errors.push(m));
assert(defs.length===22,`definitions ${defs.length}`);assert(counts.subQueues===70,'subQueues');assert(counts.workTypes===70,'workTypes');assert(counts.fields===228,'fields');assert(counts.outcomes===69,'outcomes');assert(src.source.model.processFlowEdges.length===39,'source edges');assert(src.source.model.executionTransitions.length===22,'execution transitions');assert(src.source.model.entityNodes.length===220,'entity nodes');assert(src.source.model.ontologyEdges.length===176,'ontology edges');assert(src.source.model.sources.length===29,'sources');
const ids=new Set(defs.map(d=>d.sourceTask.taskId));assert(ids.size===22,'unique task IDs');for(const e of src.source.model.processFlowEdges){assert(ids.has(e.from)&&ids.has(e.to),`edge endpoint ${e.id}`)}
for(const d of defs){const p=src.source.model.processes.find(x=>x.id===d.sourceTask.taskId);assert(!!p,`source process ${d.sourceTask.taskId}`);if(p)assert(JSON.stringify(p)===JSON.stringify(d.sourceRecord),`lossless source record ${d.sourceTask.taskId}`);assert(d.provenance.sourceRecord==='SOURCE_BACKED',`source provenance ${d.id}`);assert(d.provenance.decomposition==='MALKOM_STANDARD',`decomp provenance ${d.id}`);assert(d.notes?.length===3,`knowledge notes ${d.id}`);assert(d.projections?.length===1,`runtime projection ${d.id}`)}
const esc=canonicalFlow.edges.filter(e=>e.kind==='CANONICAL_ESCALATION');assert(esc.length===3,`canonical escalation edges ${esc.length}`);for(const id of ['LTL-15','LTL-18','LTL-22'])assert(esc.some(e=>e.from===id&&e.to==='LTL-14'&&e.style==='dashed'&&!e.runtimeSupported),`escalation ${id}->LTL-14`);
assert(flow.derivedFrom==='compiled-malkom-queue-projection','queue flow derivation marker');assert(flow.queues.length===22,`queue flow count ${flow.queues.length}`);assert(flow.loopGuards.maxVisitsPerNode===2&&flow.loopGuards.maxDepth===64,'loop guards');
const queueByTask=new Map(queues.map(q=>[q.sourceTaskId,q]));
let expectedStayBranches=0,actualStayBranches=0,totalPaths=0;
for(const item of flow.queues){const q=queueByTask.get(item.taskId);assert(!!q,`queue flow task ${item.taskId}`);if(!q)continue;const outById=new Map(q.outcomes.map(o=>[o.id,o]));expectedStayBranches+=q.subQueues.reduce((n,s)=>n+s.outcomes.filter(id=>outById.get(id)?.nextStep==='STAY_IN_QUEUE').length,0);actualStayBranches+=item.graph.edges.filter(e=>e.kind==='STAY_RETURN').length;totalPaths+=item.paths.length;assert(item.graph.sourceTaskId===item.taskId,`graph source task ${item.taskId}`);assert(item.paths.length>0,`paths ${item.taskId}`);assert(item.paths.every(p=>p.nodeIds.length<=65),`path max depth ${item.taskId}`);for(const e of item.graph.edges.filter(e=>e.meta)){assert(e.meta.outcomeCode&&e.meta.route&&e.meta.status&&e.meta.nextStep,`edge semantic metadata ${item.taskId}:${e.id}`)}
}
assert(expectedStayBranches===actualStayBranches,`STAY branch edges expected ${expectedStayBranches} actual ${actualStayBranches}`);assert(actualStayBranches===counts.queueFlowStayEdges,'STAY count registry');assert(totalPaths===counts.queueFlowPaths,'path count registry');assert(flow.queues.reduce((n,q)=>n+q.graph.edges.filter(e=>e.kind==='CANONICAL_ESCALATION').length,0)===counts.queueFlowEscalationEdges,'queue escalation edge count registry');assert(counts.stayOutcomes===19,'unique STAY outcomes');assert(counts.knowledgeNotes===66,'knowledge note count');assert(counts.runtimeProjections===22,'runtime projection count');
for(const id of ['LTL-15','LTL-18','LTL-22']){const item=flow.queues.find(q=>q.taskId===id);assert(item?.graph.edges.some(e=>e.kind==='CANONICAL_ESCALATION'&&e.to.includes('LTL-14')&&!e.runtimeSupported&&e.style==='dashed'),`queue escalation ${id}->LTL-14`)}
const blocked=wf.filter(x=>x.blockers.length);assert(JSON.stringify(blocked.map(x=>x.taskId))===JSON.stringify(['LTL-15','LTL-18','LTL-22']),'workflow blocker task set');for(const x of blocked)assert(x.blockers.every(b=>b.targetTaskId==='LTL-14'&&b.disposition==='UNSUPPORTED_CURRENT_MALKOM'),'blocker disposition');
const proto=fs.readFileSync(path.join(root,'prototype/domain-warehouse.html'),'utf8');for(const id of ['ESC-LTL-15-LTL-14','ESC-LTL-18-LTL-14','ESC-LTL-22-LTL-14'])assert(proto.includes(id),`prototype embeds escalation ${id}`);for(const token of ['Queue Flow Explorer','STAY return edge','BPMN XML','Existing Malkom Workflow Engine projection','Knowledge notes','Runtime projection metadata'])assert(proto.includes(token),`prototype token ${token}`);
const jsFiles=fs.readdirSync(path.join(root,'scripts')).filter(f=>f.endsWith('.mjs'));for(const f of jsFiles){const t=fs.readFileSync(path.join(root,'scripts',f),'utf8');assert(t.length>0,`script ${f}`)}
const sha=crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'fixtures/road-ltl/v2.3-lossless-pack.json'))).digest('hex');
const report={ok:errors.length===0,errors,warnings,counts,declaredNormalizedSourceSha256:src.source.normalizedSha256,v23PackFileSha256:sha,canonicalEscalations:esc.map(e=>({from:e.from,to:e.to,runtimeSupported:e.runtimeSupported,style:e.style})),workflowBlockers:blocked.flatMap(x=>x.blockers),queueFlow:{derivedFrom:flow.derivedFrom,queues:flow.queues.length,expectedStayBranches,actualStayBranches,totalPaths,loopGuards:flow.loopGuards},timestamp:new Date().toISOString()};fs.writeFileSync(path.join(root,'docs/OFFLINE_AUDIT.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(errors.length)process.exit(1);
