import fs from 'node:fs';
import path from 'node:path';
const cache=new Map();
const SURFACES=new Set(['canvas','universe','daughter','admin']);
function readJson(rel){if(cache.has(rel))return cache.get(rel);const x=JSON.parse(fs.readFileSync(path.join(process.cwd(),rel),'utf8'));cache.set(rel,x);return x}
function activeEntries(registry){return (registry.modules||[]).filter(x=>x.status==='ACTIVE'&&x.depth==='A5_VERIFIED'&&x.source)}
function loadModules(registry){return activeEntries(registry).map(entry=>({entry,module:readJson(entry.source)}))}
function buildIndexes(rows){const processById={},sourceById={},moduleByProcessId={},moduleById={},moduleEntryById={};for(const {entry,module} of rows){moduleById[entry.id]=module;moduleEntryById[entry.id]=entry;for(const p of module.processes||[]){if(processById[p.id])throw new Error(`Duplicate process id ${p.id}`);processById[p.id]=p;moduleByProcessId[p.id]=entry.id}for(const s of module.sources||[])sourceById[s.id]??=s}return{processById,sourceById,moduleByProcessId,moduleById,moduleEntryById}}
function slug(v){return String(v||'').toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function scalarName(x){return String(x?.name||x?.title||x?.label||x?.canonicalName||x?.id||x||'')}
function refs(x){return [...new Set([...(x?.sourceIds||[]),...(x?.sources||[])].map(v=>typeof v==='string'?v:v?.id).filter(Boolean))]}
function page0Records(page0){
 const rows=[];const add=(kind,id,title,content,sourceIds=[])=>{if(!id||!title)return;rows.push({kind,id:String(id),title:String(title),content,sourceIds:[...new Set(sourceIds)]})};
 for(const d of page0.domains||page0.page0Domains||[])add('DOMAIN',d.id||slug(scalarName(d)),scalarName(d),d,refs(d));
 for(const f of page0.navigatorFamilies||[]){for(const item of f.items||[]){const o=typeof item==='string'?{name:item}:item;const name=scalarName(o);add('NAV_ITEM',o.id||slug(name),name,{...o,familyId:f.id,family:scalarName(f)},refs(o))}}
 const sets=[['SYSTEM',page0.systemRecords],['OBJECT',page0.businessObjectRecords],['DOCUMENT',page0.documentRecords],['EVENT',page0.eventRecords],['RELATIONSHIP',page0.processRelationshipRecords],['JURISDICTION',page0.jurisdictions],['CARRIAGE_REGIME',page0.carriageRegimes],['CONDITION',page0.conditions],['EXECUTIVE_INTENT',page0.executiveIntents]];
 for(const [kind,list] of sets)for(const x of list||[])add(kind,x.id||slug(scalarName(x)),scalarName(x),x,refs(x));
 return rows;
}
function buildReferenceIndex(page0){const records=page0Records(page0),byId={};for(const r of records)byId[r.id]=r;return{records,byId}}
export function atlasData(){const registry=readJson('data/atlas-registry.json'),catalog=readJson('data/module-catalog.json'),page0=readJson(registry.baseModule?.source||'data/page0/page0-v6.2.2.json'),active=loadModules(registry),idx=buildIndexes(active),ref=buildReferenceIndex(page0);return{registry,catalog,page0,activeModules:active,moduleById:idx.moduleById,moduleEntryById:idx.moduleEntryById,moduleByProcessId:idx.moduleByProcessId,processById:idx.processById,sourceById:idx.sourceById,referenceRecords:ref.records,referenceById:ref.byId,roadLtl:idx.moduleById['road-ltl']||null,overlays:readJson('governance/overlay-registry-v1.json'),foundationOverlays:readJson('governance/overlay-registry-v1.1.json'),rules:readJson('governance/rule-registry-v1.json'),foundationRules:readJson('governance/rule-registry-v1.1.json'),commandContract:readJson('governance/canvas-command-contract-v1.json'),surfaceContract:readJson('governance/ask-atlas-surface-contract-v1.json')}}
function toks(s){return[...new Set(String(s||'').toLowerCase().replace(/[^a-z0-9-]+/g,' ').split(/\s+/).filter(x=>x.length>2&&!['the','and','for','with','show','what','where','why','how','this','that','atlas','please','tell','current'].includes(x)))]}
function text(x){return JSON.stringify(x).toLowerCase()}
function scoreItem(item,terms,boost=0){const h=text(item);return boost+terms.reduce((n,t)=>n+(h.includes(t)?1:0),0)}
function add(out,item){if(!out.some(x=>x.key===item.key))out.push(item)}
function sourceTitle(s){return `${s.issuer||'Source'} · ${s.title||s.id}`}
function registryLookup(value,A=atlasData()){const v=String(value||'').trim().toLowerCase();if(!v)return null;return [...(A.registry.modules||[]),...(A.registry.items||[])].find(x=>String(x.id||'').toLowerCase()===v||String(x.name||x.label||'').toLowerCase()===v)||null}
function activeMentionIds(question,A=atlasData()){const l=String(question||'').toLowerCase(),hits=[];for(const entry of activeEntries(A.registry)){const labels=[entry.id,entry.label,(A.registry.items||[]).find(x=>x.id===entry.id)?.name].filter(Boolean);if(labels.some(v=>l.includes(String(v).toLowerCase())))hits.push(entry.id)}return [...new Set(hits)]}
export function normalizeSurfaceState(input={}){
 const x=input&&typeof input==='object'?input:{};let surface=String(x.surface||x.view||x.activeSurface||'').toLowerCase();if(!SURFACES.has(surface))surface='canvas';
 const moduleIds=[...(Array.isArray(x.moduleIds)?x.moduleIds:[]),x.moduleId,x.activeModule,x.mode,x.service].filter(Boolean).map(String);
 const selectedProcess=x.selectedProcess||x.processId||x.playback?.processId||null;
 const selectedEntity=x.selectedEntity&&typeof x.selectedEntity==='object'?x.selectedEntity:(x.selectedEntityId?{id:x.selectedEntityId,type:x.selectedEntityType||null}:null);
 return {...x,surface,moduleIds:[...new Set(moduleIds)],moduleId:x.moduleId||x.activeModule||moduleIds[0]||null,selectedProcess,selectedEntity,section:x.section||x.tab||x.hash||null};
}
export function activeModuleIds(context={},question=''){const A=atlasData(),state=normalizeSurfaceState(context),active=new Set(activeEntries(A.registry).map(x=>x.id)),explicit=state.moduleIds.map(v=>registryLookup(v,A)?.id||v).filter(x=>active.has(x)),mentioned=activeMentionIds(question,A);if(explicit.length)return[...new Set(explicit)];if(mentioned.length)return mentioned;if(state.surface==='universe')return[];return[...active]}
export function coverageMatch(q,registry=atlasData().registry){const l=String(q||'').toLowerCase();return(registry.items||[]).filter(x=>{const name=String(x.name||'').toLowerCase();if(name&&l.includes(name))return true;const id=String(x.id||'');if(id==='road-ltl'&&/\bltl\b/.test(l))return true;if(id==='road-ftl'&&/\bftl\b/.test(l))return true;if(id==='ocean-fcl'&&/\bfcl\b/.test(l))return true;if(id==='ocean-lcl'&&/\blcl\b/.test(l))return true;return false}).slice(0,5)}
function referenceEvidence(A,question,state,seqRef,out){const terms=toks(question),selected=state.selectedEntity?.id||state.selectedDomain||null,l=String(question||'').toLowerCase();let kinds=null;if(/system|tms|wms|erp|platform|authority/.test(l))kinds=new Set(['SYSTEM']);else if(/document|bol|bill of lading|waybill|pod|invoice/.test(l))kinds=new Set(['DOCUMENT']);else if(/object|data element|business object/.test(l))kinds=new Set(['OBJECT']);else if(/event|milestone|scan/.test(l))kinds=new Set(['EVENT']);else if(/jurisdiction|geograph|country|region/.test(l))kinds=new Set(['JURISDICTION']);else if(/carriage regime|regime|cmr|montreal/.test(l))kinds=new Set(['CARRIAGE_REGIME']);else if(/condition|hazmat|dangerous goods|temperature|security/.test(l))kinds=new Set(['CONDITION']);const pool=kinds?A.referenceRecords.filter(r=>kinds.has(r.kind)):A.referenceRecords;const scored=pool.map(r=>({r,s:scoreItem(r,terms,r.id===selected?10:0)})).filter(x=>x.s>0||rIsSelected(x.r,selected)).sort((a,b)=>b.s-a.s).slice(0,8);for(const {r} of scored)add(out,{key:`r:${r.kind}:${r.id}`,id:`E${seqRef.n++}`,class:`ATLAS_${r.kind}`,title:`Universe · ${r.title}`,sourceIds:r.sourceIds,moduleId:null,content:{...r.content,id:r.id,name:r.title,referenceType:r.kind}})}
function rIsSelected(r,selected){return!!selected&&r.id===selected}
function protectedEvidence(protectedContext,question,state,seqRef,out){if(!protectedContext?.definitions?.length)return;const terms=toks(question),selected=state.selectedProcess;const defs=protectedContext.definitions.map(d=>({d,s:scoreItem(d,terms,d.sourceTaskId===selected?15:0)})).sort((a,b)=>b.s-a.s).slice(0,5);for(const {d,s} of defs){if(s<=0&&!selected&&defs.length>1)continue;add(out,{key:`wd:${d.definitionId||d.sourceTaskId}`,id:`E${seqRef.n++}`,class:'PROTECTED_WORK_DEFINITION',title:`Protected WorkDefinition · ${d.sourceTaskId||d.definitionId}`,sourceIds:d.sourceIds||[],moduleId:d.moduleId||d.domain||null,content:d})}}
export function retrieveAtlas(question,rawState={},client=null,protectedContext=null){const A=atlasData(),state=normalizeSurfaceState(rawState),terms=toks(question),out=[],moduleIds=activeModuleIds(state,question),allowed=new Set(moduleIds);const seqRef={n:1},selected=state.selectedProcess||null;
 for(const c of coverageMatch(question,A.registry))add(out,{key:'c:'+c.id,id:`E${seqRef.n++}`,class:'COVERAGE',title:`Coverage · ${c.name}`,sourceIds:[],content:{id:c.id,name:c.name,status:c.status,depth:c.depth,category:c.category||c.family||null}});
 const processes=Object.entries(A.processById).filter(([id])=>allowed.has(A.moduleByProcessId[id])).map(([id,p])=>({p,moduleId:A.moduleByProcessId[id],s:scoreItem(p,terms,id===selected?12:0)})).sort((a,b)=>b.s-a.s);
 for(const {p,moduleId,s} of processes.slice(0,Math.max(4,Math.min(8,processes.filter(x=>x.s>0).length||4)))){if(s<=0&&!selected)continue;add(out,{key:'p:'+p.id,id:`E${seqRef.n++}`,class:'ATLAS_PROCESS',title:`${p.id} · ${p.label}`,sourceIds:p.sourceIds||[],moduleId,content:{id:p.id,label:p.label,a3:p.a3ParentLabel,pathType:p.pathType,trigger:p.trigger,stateBefore:p.before,event:p.event,decision:p.decision,rule:p.rule,control:p.control,action:p.action,evidence:p.evidence,stateAfter:p.after,outcome:p.outcome,performer:p.performer,owner:p.owner,custody:p.custody,inputs:p.inputs,outputs:p.outputs,authoritySystem:p.authoritySystem,producer:p.producer,consumers:p.consumers,claimBoundary:p.claimBoundary,provenance:p.provenance}})}
 referenceEvidence(A,question,state,seqRef,out);
 const sourceIds=new Set(out.flatMap(x=>x.sourceIds||[]));for(const s of Object.values(A.sourceById)){const sc=scoreItem(s,terms,sourceIds.has(s.id)?5:0);if(sc<=0)continue;add(out,{key:'s:'+s.id,id:`E${seqRef.n++}`,class:'ATLAS_SOURCE',title:sourceTitle(s),sourceIds:[s.id],content:{id:s.id,issuer:s.issuer,title:s.title,version:s.version,confidence:s.confidence,research:s.research,supports:s.supports,doesNotSupport:s.notSupports,scope:[s.modeScope,s.jurisdictionScope,s.roleScope].filter(Boolean).join(' · '),url:s.url}});if(out.length>=16)break}
 if(client?.workspace){const ws=client.workspace,mp=ws.mappings||{},ev=ws.evidence||{},ids=[selected,...Object.keys(mp).filter(id=>terms.some(t=>text(mp[id]).includes(t)))].filter(Boolean);for(const id of [...new Set(ids)].slice(0,4)){const m=mp[id];if(!m)continue;add(out,{key:'cm:'+id,id:`E${seqRef.n++}`,class:'CLIENT_MAPPING',title:`Client mapping · ${id}`,sourceIds:[],content:{processId:id,status:m.status,clientLabel:m.clientLabel,clientOwner:m.clientOwner,clientSystems:m.clientSystems,alignment:m.alignment,deviationNote:m.deviationNote,rationale:m.rationale,evidenceIds:m.evidenceIds||[]}});for(const eid of(m.evidenceIds||[]).slice(0,3)){const e=ev[eid];if(e)add(out,{key:'ce:'+eid,id:`E${seqRef.n++}`,class:'CLIENT_EVIDENCE',title:`Client evidence · ${e.title||eid}`,sourceIds:[],content:{id:eid,type:e.type,title:e.title,note:e.note,fileName:e.fileName||''}})}}}
 protectedEvidence(protectedContext,question,state,seqRef,out);
 return out.slice(0,20)}
export function validateSurfaceState(rawState={}){const A=atlasData(),state=normalizeSurfaceState(rawState),errors=[];if(!SURFACES.has(state.surface))errors.push('Unknown Atlas surface.');const mid=state.moduleId;if(mid){const resolved=registryLookup(mid,A),id=resolved?.id||mid;if((state.surface==='daughter'||state.surface==='canvas'||state.surface==='admin')&&!A.moduleById[id]){const r=(A.registry.items||[]).find(x=>x.id===id);if(!r||r.depth!=='A5_VERIFIED')errors.push('Requested module does not have published A5 execution depth.')}state.moduleId=id}if(state.surface==='daughter'&&!state.moduleId)errors.push('Daughter surface requires a published module.');if(state.selectedProcess&&!A.processById[state.selectedProcess])errors.push('Selected process is not in an active published module.');return{valid:!errors.length,errors,state}}
export function validateCanvasState(state={}){return validateSurfaceState({...state,surface:'canvas'})}
function commandDefs(A){return{...(A.commandContract.commands||{}),...(A.surfaceContract.commands||{})}}
export function validateCommands(commands=[],rawState={}){const A=atlasData(),state=normalizeSurfaceState(rawState),defs=commandDefs(A),valid=[],rejected=[];for(const c of Array.isArray(commands)?commands:[]){const type=String(c?.type||''),args=c?.args&&typeof c.args==='object'?c.args:{},d=defs[type];if(!d){rejected.push({command:c,reason:'Unknown command type'});continue}if((d.required||[]).some(k=>args[k]===undefined||args[k]===null||args[k]==='')){rejected.push({command:c,reason:'Missing required argument'});continue}let reason='',normalizedArgs={...args};if(type==='activate_module'&&!A.moduleById[args.moduleId])reason='Module is not A5-verified/published.';if(type==='select_process'&&!A.processById[args.processId])reason='Process ID is not in an active published module.';if(type==='open_source'&&!A.sourceById[args.sourceId])reason='Source ID is not in an active published module.';if(type==='set_semantic_level'&&!d.allowedLevels.includes(Number(args.level)))reason='Unsupported semantic level.';if(type==='playback'&&!d.allowedActions.includes(args.action))reason='Unsupported playback action.';if(type==='set_follow_signal'&&!d.allowedSignals.includes(args.signal))reason='Unsupported signal.';if(type==='open_lens'&&!d.allowedLenses.includes(args.lens))reason='Unsupported lens.';if(type==='navigate_surface'&&!d.allowedSurfaces.includes(args.surface))reason='Unsupported Atlas surface.';if(type==='open_daughter'&&!A.moduleById[args.moduleId])reason='Daughter module is not A5-verified/published.';if(type==='open_in_canvas'){if(args.moduleId&&!A.moduleById[args.moduleId])reason='Canvas handoff module is not A5-verified/published.';if(!reason&&args.processId&&!A.processById[args.processId])reason='Canvas handoff process is not in an active published module.'}if(type==='highlight_reference'&&!A.referenceById[args.entityId]&&!(A.registry.items||[]).some(x=>x.id===args.entityId))reason='Reference entity is not in the published Universe.';if(type==='set_context_option'){if(!d.allowedDimensions.includes(args.dimension))reason='Unsupported context dimension.';else{const list=A.overlays.overlays||A.overlays.items||[],o=list.find(o=>o.id===args.optionId||(o.dimension===args.dimension&&o.sourceContextId===args.optionId));if(!o)reason='Unknown overlay option.';else if(o.dimension!==args.dimension)reason='Overlay belongs to a different context dimension.';else normalizedArgs.optionId=o.sourceContextId}}if(reason)rejected.push({command:c,reason});else valid.push({type,args:normalizedArgs})}return{valid,rejected}}
function mentionedActiveModule(question,A){const ids=activeMentionIds(question,A);return ids[0]||null}
export function deterministicPlan(question,rawState={}){const A=atlasData(),state=normalizeSurfaceState(rawState),l=String(question||'').toLowerCase(),commands=[],mentioned=mentionedActiveModule(question,A),contextModule=mentioned||state.moduleId;
 if(/\b(open|go to|take me to)\b.*\b(universe|page\s*0)\b/.test(l))commands.push({type:'navigate_surface',args:{surface:'universe'}});else if(/\b(open|go to|take me to)\b.*\bcanvas\b/.test(l)&&!/open in canvas/.test(l))commands.push({type:'navigate_surface',args:{surface:'canvas'}});
 if(/open(?: .*?)? in canvas|show .* in canvas|take .* to canvas/.test(l)){commands.push({type:'open_in_canvas',args:{...(contextModule?{moduleId:contextModule}:{}),...(state.selectedProcess?{processId:state.selectedProcess}:{})}})}else if(mentioned){if(state.surface==='canvas'||state.surface==='admin')commands.push({type:'activate_module',args:{moduleId:mentioned}});else commands.push({type:'open_daughter',args:{moduleId:mentioned}})}
 if(/\b(universe reset|reset universe)\b/.test(l))commands.push({type:'reset_universe',args:{}});if(/\b(play|start)\b.*\bexecution\b/.test(l))commands.push({type:'playback',args:{action:'start'}});if(/\bpause\b/.test(l))commands.push({type:'playback',args:{action:'pause'}});if(/\bfreeze\b/.test(l))commands.push({type:'playback',args:{action:'freeze'}});if(/step forward|next step/.test(l))commands.push({type:'playback',args:{action:'step_forward'}});if(/step back|previous step/.test(l))commands.push({type:'playback',args:{action:'step_back'}});for(const[k,v]of[['physical','physical'],['information','information'],['document','data'],['data','data'],['money','financial'],['financial','financial'],['control','control']])if(l.includes('follow '+k)||l.includes('show only '+k)){commands.push({type:'set_follow_signal',args:{signal:v}});break}if(/trace shipment/.test(l))commands.push({type:'trace_object',args:{objectId:'obj-shipment'}});if(/trace handling unit/.test(l))commands.push({type:'trace_object',args:{objectId:'obj-handling-unit'}});if(/trace (invoice)/.test(l))commands.push({type:'trace_object',args:{objectId:'obj-invoice'}});if(/show actors|actor lens/.test(l))commands.push({type:'open_lens',args:{lens:'actors'}});if(/show systems|system lens/.test(l))commands.push({type:'open_lens',args:{lens:'systems'}});if(/show controls|control lens/.test(l))commands.push({type:'open_lens',args:{lens:'controls'}});if(/show sources|source lens/.test(l))commands.push({type:'open_lens',args:{lens:'sources'}});if(/clear context|reset context|remove context/.test(l))commands.push({type:'clear_context',args:{}});if(/add|apply|set context|use context|now make|now add/.test(l)){const list=A.overlays.overlays||[];let best=null,score=0,qt=toks(l);for(const o of list){const hay=(o.name+' '+o.sourceContextId).toLowerCase();let sc=qt.reduce((n,t)=>n+(hay.includes(t)?1:0),0);if(/hazmat|dangerous goods/.test(l)&&/dangerous goods/i.test(o.name))sc+=6;if(sc>score){best=o;score=sc}}if(best&&score>0)commands.push({type:'set_context_option',args:{dimension:best.dimension,optionId:best.sourceContextId}})}if(/transform|transformation/.test(l))commands.push({type:'enter_transform',args:{}});if(/show findings|finding register/.test(l))commands.push({type:'open_findings',args:{}});if(/show opportunities|opportunity portfolio/.test(l))commands.push({type:'open_opportunities',args:{}});return commands}
