import {getModel,processById} from './store.js';
import {constitutionItems} from './constitution.js';

const SPECIAL=[

 {id:'ui-other-ltl-knowledge',kind:'Runtime / presentation classification',label:'OTHER_LTL_KNOWLEDGE',aliases:['other_ltl_knowledge','other ltl knowledge'],definition:'Governed Road LTL knowledge outside the current focus/direct-dependency set. It remains part of the model and is not a jurisdiction, source category or source-native taxonomy node.',plainEnglish:'Other parts of the LTL operating model still exist, but they are not directly involved in the thing you are tracing right now.',section:'Road LTL · Trace relevance',namespace:'Trace relevance',origin:'Current trace + governed LTL graph',provenance:'RUNTIME / PRESENTATION STATE',sourceNative:false,regulatory:false,changesAtlas:false},
 {id:'obj-bol-canonical',kind:'Business object',label:'BOL / eBOL / consignment note',aliases:['bol','ebol','bill of lading','bill lading','transport document'],definition:'Road LTL shipment/consignment transport-document identity is created and validated in LTL-03; pickup acknowledgement evidence may also reference the BOL in LTL-05.',section:'Road LTL · Documents',processIds:['LTL-03','LTL-05']},
 {id:'obj-invoice-canonical',kind:'Business object',label:'Transport invoice',aliases:['invoice','carrier invoice','customer invoice','transport invoice'],definition:'Transport invoicing, audit, approval and settlement are governed primarily in LTL-17 after charge recognition; a billing dispute can branch into LTL-18.',section:'Road LTL · Financial',processIds:['LTL-17','LTL-18']},
 {id:'ui-source-category',kind:'Atlas concept',label:'Source category',aliases:['source category','source categories','model source','model evidence'],definition:'Source categories classify what an authority can substantiate and how it may be used. A source record is bounded by its issuer, scope, usage class and claim boundary; being in the source universe never makes it universally applicable.',section:'Sources'},
 {id:'ui-applicability',kind:'Atlas concept',label:'Applicability state',aliases:['applicability','candidate applicability','operative applicability','applicability state'],definition:'Applicability is context-dependent. A source, rule or overlay may be a candidate until the actual mode, lane, goods, contract, jurisdiction and legal scope resolve whether it is operative.',section:'Execution context / Sources'},
 {id:'ui-source-native-backbone',kind:'Atlas concept',label:'Source-native backbone',aliases:['source native backbone','backbone'],definition:'The Atlas keeps SCOR and APQC as two independent native process frameworks. BPMN and DMN are modelling notations, not logistics process evidence.',section:'Sources · Governed evidence universe'},
 {id:'ui-governed-evidence-universe',kind:'Atlas concept',label:'Governed evidence universe',aliases:['governed evidence universe','evidence universe'],definition:'The governed source universe separates primary process architecture from data semantics, industry standards, regulation, legal regimes and enterprise-enabling references; inclusion does not imply universal applicability.',section:'Sources'},
 {id:'ui-authority-domain',kind:'Atlas concept',label:'Authority domain',aliases:['authority domain','authority domains'],definition:'An authority domain is one governed source/evidence domain in the Atlas. The current Page 0 shows 17 domains spanning data, modes, roles, enterprise functions, regulation, emissions and liability, applied conditionally.',section:'Sources'},
 {id:'ui-reference-universe',kind:'Atlas concept',label:'Reference universe',aliases:['reference universe','reference source universe'],definition:'The searchable collection of governed source records. Sources are bounded to the claims they can substantiate and must not be used outside their stated scope.',section:'Sources'},
 {id:'ui-movement-pattern',kind:'Execution-context axis',label:'Movement pattern',aliases:['movement pattern','movement'],definition:'A movement pattern is a selectable execution-context axis describing how freight moves through the network, such as line-haul, first mile, last mile, hub-and-spoke, direct shipment or consolidation/deconsolidation. It does not replace the transport mode.',section:'Execution context'},
 {id:'ui-operating-role',kind:'Execution-context axis',label:'Operating role',aliases:['operating role','role'],definition:'Operating role selects the party perspective/responsibility used to refine execution applicability, such as shipper, carrier, 3PL or 4PL. Neutral means no additional role assumption.',section:'Execution context'},
 {id:'ui-node',kind:'Execution-context axis',label:'Node',aliases:['node','logistics node'],definition:'Node identifies the physical/logistics location type involved in the execution context, such as warehouse, distribution centre, cross-dock or terminal. Eligibility depends on the selected mode and context.',section:'Execution context'},
 {id:'ui-jurisdiction',kind:'Execution-context axis',label:'Jurisdiction',aliases:['jurisdiction'],definition:'Jurisdiction refines the legal/regulatory context. Selecting a geography does not by itself make every regulation operative; actual lane, goods, authority and legal scope must be resolved.',section:'Execution context'},
 {id:'ui-carriage-regime',kind:'Execution-context axis',label:'Carriage regime',aliases:['carriage regime','regime'],definition:'Carriage regime is a multi-select legal-carriage context such as CMR/e-CMR or COTIF/CIM. It applies only when the actual carriage and legal scope qualify.',section:'Execution context'},
 {id:'ui-condition',kind:'Execution-context axis',label:'Condition',aliases:['condition','regulatory condition'],definition:'Conditions are composable execution/regulatory overlays such as Dangerous Goods, Customs Transit, Temperature Controlled, Bonded context or Security controlled.',section:'Execution context'},
 {id:'ui-enterprise-lens',kind:'Analytical axis',label:'Enterprise lens',aliases:['enterprise lens','analytical lens','lens'],definition:'Enterprise lenses are analytical/control views over the same Atlas rather than new execution taxonomy. They connect execution to enterprise capabilities and outcomes.',section:'Analytical view'},
 {id:'ui-compatibility-state',kind:'Rule-engine concept',label:'Compatibility state',aliases:['compatibility state','compatibility states','enabled','conditional','incompatible','locked'],definition:'Compatibility states govern whether a selection is valid in the current context. Enabled is directly supported; Conditional requires scope resolution; Incompatible is invalid; Locked requires a prerequisite selection.',section:'Execution context'},
 {id:'ui-reference-only',kind:'Client-twin evidence state',label:'REFERENCE_ONLY',aliases:['reference only','reference_only'],definition:'REFERENCE_ONLY means the Atlas reference says the component normally exists, but the client-specific state has not been established. It must never be presented as client truth.',section:'Client Twin'},
 {id:'jur-national-corridor',kind:'Jurisdiction option',label:'Other national / corridor jurisdiction',aliases:['other jurisdiction','other national','other national corridor','national corridor','other national / corridor'],definition:'Select competent authorities and local law for the actual lane, service and goods. “Other” here is a jurisdiction option, not a source category.',section:'Execution context · Jurisdiction'}
];
function norm(s=''){return String(s).toLowerCase().replace(/[_/]+/g,' ').replace(/[^a-z0-9 -]+/g,' ').replace(/\s+/g,' ').trim()}
function objectLabel(id=''){return id.replace(/^(obj|sys|evt|actor)-/,'').replace(/-/g,' ')}
function build(){const m=getModel(),items=[...SPECIAL,...constitutionItems()];
 const add=(kind,arr,labelKey='name')=>(arr||[]).forEach(x=>items.push({id:x.id,kind,label:x[labelKey]||x.label||x.id,aliases:[x.id,x[labelKey],x.label].filter(Boolean),definition:x.desc||x.scope||x.caption||'',record:x}));
 add('Operating role',m.roles);add('Movement pattern',m.movements);add('Logistics node',m.nodes);add('Jurisdiction option',m.jurisdictions);add('Carriage regime',m.regimes);add('Condition',m.conditions);add('Contract / service context',m.contracts);add('Enterprise intent',m.intents,'label');add('Enterprise lens',m.lenses);add('Phase',m.phases);add('View',m.views);add('Source',m.sources,'title');add('Actor',m.childActors);
 for(const p of m.processes){items.push({id:p.id,kind:'Road LTL A4 execution process',label:p.label,aliases:[p.id,p.label],definition:p.outcome||p.event,plainEnglish:'A detailed Road LTL operating step. Use its trigger, event, states, decision/rule/control, action, evidence and outcome to understand what happens in real execution.',namespace:'Road LTL execution',origin:'Page-0 parent + bounded issuer evidence',provenance:p.provenance,sourceRelationship:p.sourceMap,section:'Road LTL V1.2',processIds:[p.id],record:p});for(const id of [...(p.inputs||[]),...(p.outputs||[])])items.push({id,kind:'Business object',label:objectLabel(id),aliases:[id,objectLabel(id)],definition:`Governed object referenced by ${p.id} — ${p.label}.`,processIds:[p.id]})}
 for(const e of m.entityNodes||[])items.push({id:e.id,kind:e.type||'Atlas entity',label:e.label,aliases:[e.id,e.label],definition:e.label,processIds:e.processId?[e.processId]:[],record:e});
 const merged=new Map();for(const x of items){if(!x?.id||!x.label)continue;const prev=merged.get(x.id);if(prev){prev.processIds=[...new Set([...(prev.processIds||[]),...(x.processIds||[])])];prev.aliases=[...new Set([...(prev.aliases||[]),...(x.aliases||[])])];if(!prev.definition&&x.definition)prev.definition=x.definition}else merged.set(x.id,{...x,processIds:x.processIds||[],aliases:[...new Set([x.label,...(x.aliases||[])])].filter(Boolean)})}
 return [...merged.values()]}
let CACHE;export function canonicalItems(){return CACHE||(CACHE=build())}
function score(item,q,ctx=''){const n=norm(q),context=norm(ctx),aliases=item.aliases.map(norm),stop=new Set(['trace','track','follow','show','explain','define','what','does','mean','means','meaning','signify','signifies','where','is','the','a','an','of','this','that','on','page']);const qTokens=n.split(' ').filter(t=>t.length>2&&!stop.has(t));let s=0;const nid=norm(item.id);if(item.id.includes('-')&&nid.length>=6&&n.includes(nid))s+=180;if(aliases.includes(n))s+=100;if(item.id.endsWith('-canonical')&&qTokens.some(t=>aliases.includes(t)))s+=70;for(const a of aliases){if(!a)continue;if(n.includes(a)&&a.length>=3)s+=35+Math.min(a.length,20);if(a.includes(n)&&n.length>=4)s+=18}if(s>0&&context&&aliases.some(a=>context.includes(a)))s+=28;for(const a of aliases){const at=a.split(' ');const overlap=qTokens.filter(t=>at.includes(t)||a.includes(t));if(overlap.length)s+=overlap.length*12;}if(item.kind==='Business object'&&/trace|track|lineage|where|flow/.test(n))s+=14;if(item.kind==='Road LTL process'&&/ltl-\d{2}/.test(n))s+=20;return s}
export function resolveCanonical(query,atlasContext={}){const original=norm(query),deictic=/^(?:what (?:does|is) this(?: mean)?|what's this|whats this|explain this|this)$/.test(original);const clicked=[atlasContext.lastSelection?.id,atlasContext.lastSelection?.text].filter(Boolean);if(deictic&&clicked.length)query=clicked.join(' ');const ctx=[...clicked,atlasContext.lastSelection?.scope,atlasContext.page,atlasContext.hash,...(atlasContext.visibleHeadings||[]),...(atlasContext.activeState||[]),...(atlasContext.selectedValues||[]),...(atlasContext.visibleLabels||[])].filter(Boolean).join(' ');const n=norm(query),items=canonicalItems();
 // Exact clicked/current ID or label wins before fuzzy search.
 if(clicked.length){for(const c of clicked){const nc=norm(c);const exact=items.find(x=>norm(x.id)===nc||x.aliases.map(norm).includes(nc)||norm(x.label)===nc);const sharedOther=/\bother\b/.test(n)&&/\bother\b/.test(nc);if(exact&&(deictic||n.includes(nc)||nc.includes(n)||sharedOther))return {best:exact,candidates:[{...exact,score:1000}],contextUsed:ctx,ambiguous:false,resolution:'EXACT_UI_CONTEXT'}}}
 let ranked=items.map(x=>({item:x,score:score(x,n,ctx)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);
 if(/^(trace|track|follow|lineage|where)\b/.test(n))ranked=ranked.filter(x=>x.item.id!=='constitution-ltl-trace');
 // Bare/shared OTHER is intentionally ambiguous unless exact UI context resolves it.
 if(n==='other'||/^(?:what (?:does|is) )?other(?: mean| signify| here| on the page| signify on the page| mean on the page)?\??$/.test(n)){const opts=items.filter(x=>x.id==='ui-other-ltl-knowledge'||x.id==='jur-national-corridor');return {best:null,candidates:opts.map((x,i)=>({...x,score:900-i})),contextUsed:ctx,ambiguous:true,resolution:'CLARIFICATION_REQUIRED',clarification:'I can see more than one Atlas meaning for “Other”. Do you mean OTHER_LTL_KNOWLEDGE in the Road LTL trace/relevance view, or Other national / corridor in the Jurisdiction selector?'}}
 const top=ranked[0],second=ranked[1];const short=n.split(' ').filter(Boolean).length<=4;const ambiguous=!!(top&&second&&short&&top.score-second.score<=5&&top.item.kind!==second.item.kind);
 if(ambiguous)return {best:null,candidates:ranked.slice(0,5).map(x=>({...x.item,score:x.score})),contextUsed:ctx,ambiguous:true,resolution:'CLARIFICATION_REQUIRED',clarification:`I found more than one valid Atlas meaning for “${String(query).trim()}”. Are you asking about ${top.item.label} (${top.item.kind}) or ${second.item.label} (${second.item.kind})?`};
 const best=top?.item||null;return {best,candidates:ranked.slice(0,5).map(x=>({...x.item,score:x.score})),contextUsed:ctx,ambiguous:false,resolution:best?'CANONICAL':'NONE'}}
export function linkedProcessIds(item){if(!item)return[];if(item.id?.startsWith('ui-')||['Execution-context axis','Analytical axis','Rule-engine concept','Client-twin evidence state','Jurisdiction option','Operating role','Movement pattern','Logistics node','Carriage regime','Condition','Contract / service context','Enterprise intent','Enterprise lens','Phase','View','Source','Actor'].includes(item.kind))return [...new Set(item.processIds||[])];const m=getModel(),ids=new Set(item.processIds||[]),aliases=new Set([item.id,...(item.aliases||[])].map(norm));for(const p of m.processes){const hay=[p.id,p.label,p.event,p.authorityObject,p.authoritySystem,...(p.inputs||[]),...(p.outputs||[])].filter(Boolean).map(norm);if(hay.some(v=>aliases.has(v)||[...aliases].some(a=>a.length>3&&v.includes(a))))ids.add(p.id)}return [...ids]}
export function isAtlasNativeQuery(text,atlasContext={}){return !!resolveCanonical(text,atlasContext).best}
export function explainCanonical(item){if(!item)return null;const ids=linkedProcessIds(item);const lines=[];if(item.plainEnglish)lines.push(`In simple English: ${item.plainEnglish}`);lines.push(`Atlas term: ${item.label}`);if(item.definition)lines.push(`Atlas definition: ${item.definition}`);lines.push(`Classification: ${item.kind}`);if(item.namespace)lines.push(`Namespace: ${item.namespace}`);if(item.section)lines.push(`Atlas area: ${item.section}`);if(item.origin)lines.push(`Origin: ${item.origin}`);if(item.provenance)lines.push(`Provenance: ${item.provenance}`);if(item.sourceRelationship)lines.push(`Source relationship: ${item.sourceRelationship}`);if(item.sourceNative===false)lines.push('Source-native: No');if(item.regulatory===false)lines.push('Regulatory classification: No');if(item.changesAtlas===false)lines.push('Changes Atlas content: No');if(ids.length)lines.push(`Related Road LTL processes: ${ids.join(', ')}`);return lines.join('\n')}
