import fs from 'fs';import path from 'path';
let CACHE;
export function getConstitution(){if(!CACHE)CACHE=JSON.parse(fs.readFileSync(path.join(process.cwd(),'data','atlas-constitution-v6.2.3.json'),'utf8'));return CACHE}
const norm=s=>String(s||'').toLowerCase().replace(/[_/]+/g,' ').replace(/[^a-z0-9 -]+/g,' ').replace(/\s+/g,' ').trim();
export function constitutionItems(){const c=getConstitution(),items=[];const push=(id,label,kind,technical,plain='',extra={})=>items.push({id,label,kind,aliases:[label,id,...(extra.aliases||[])].filter(Boolean),definition:technical,plainEnglish:plain,...extra});
 for(const x of c.stateVocabulary)push('constitution-state-'+norm(x.term).replace(/ /g,'-'),x.term,'Runtime / source state',x.meaning,x.plainEnglish,{namespace:x.namespace,origin:'ATLAS_RUNTIME_OR_SOURCE_RELATIONSHIP',provenance:'RUNTIME / PRESENTATION STATE'});
 for(const x of c.provenanceClasses)push('constitution-provenance-'+norm(x.name).replace(/ /g,'-'),x.name,'Provenance class',x.meaning,x.plainEnglish,{namespace:'Provenance',origin:'ATLAS_GOVERNANCE',provenance:x.name});
 for(const x of c.contextDimensions)push('constitution-context-'+norm(x[0]).replace(/ /g,'-'),x[0],'Execution / analytical context',x[1],x[2],{namespace:'Context dimension',origin:'PAGE0_GOVERNED_CONTEXT'});
 for(const x of c.ontologyTypes)push('constitution-ontology-'+norm(x[0]).replace(/ /g,'-'),x[0],'Ontology entity type',x[1],x[2],{namespace:'Ontology'});
 for(const x of c.flowRelationships)push('constitution-flow-'+norm(x[0]).replace(/ /g,'-'),x[0],'Process-flow relationship',x[1],x[2],{namespace:'Process flow'});
 for(const x of c.hierarchy)push('constitution-hierarchy-'+norm(x.level).replace(/ /g,'-'),x.level,'Atlas hierarchy level',x.meaning,x.plainEnglish,{namespace:'Hierarchy'});
 for(const x of c.architectureLayers)push('constitution-layer-'+norm(x.name).replace(/ /g,'-'),x.name,x.type,x.meaning,x.plainEnglish||'',{namespace:'Architecture layer'});
 for(const x of c.sourceArchitecture)push('constitution-sourceclass-'+norm(x.class).replace(/ /g,'-'),x.class,'Source architecture class',x.role,`Examples: ${x.examples.join(', ')}`,{namespace:'Source architecture',examples:x.examples});
 for(const x of c.page0Walkthrough)push('constitution-page0-'+norm(x[0]).replace(/ /g,'-'),x[0],'Page 0 section',x[1],x[1],{namespace:'Page 0 walkthrough'});
 for(const x of c.ltlWalkthrough)push('constitution-ltl-'+norm(x[0]).replace(/ /g,'-'),x[0],'Road LTL reading concept',x[1],x[1],{namespace:'Road LTL walkthrough'});
 push('constitution-how-built','How the Atlas was built','Methodology',c.methodology.map(x=>`${x.step}. ${x.name}: ${x.groundedMeaning}`).join(' '),'The Atlas starts with source-native process frameworks, adds data/interoperability and scoped legal/mode evidence, then uses explicit Atlas crosswalks and child synthesis while keeping provenance visible.',{aliases:['methodology','how atlas was built','how page 0 was built','how ltl was built','framework structure methodology'],namespace:'Methodology'});
 push('constitution-how-read','How to read the Atlas','User guide','Use Page 0 to orient the enterprise/reference universe, refine context only when known, use the child for detailed execution, and inspect provenance/sources before treating a statement as source-native or operative.','Start broad, choose the operating context you actually know, then drill into the detailed process. Use trace to understand dependencies and Sources/Provenance to understand why the Atlas can say something.',{aliases:['how to read atlas','walkthrough','page walkthrough','atlas guide'],namespace:'Guide'});
 return items}
export function searchConstitution(query,limit=6){const q=norm(query),tokens=q.split(' ').filter(x=>x.length>2);return constitutionItems().map(x=>{const hay=norm([x.label,...x.aliases,x.definition,x.plainEnglish,x.namespace].join(' '));let score=0;for(const t of tokens)if(hay.includes(t))score+=t.length>6?5:3;if(x.aliases.map(norm).some(a=>a===q))score+=100;return {...x,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,limit)}
export function constitutionSummary(){const c=getConstitution();return {id:c.id,release:c.release,releaseType:c.releaseType,frozenFoundation:c.frozenFoundation,purpose:c.purpose,explanationPolicy:c.explanationPolicy,governance:c.governance}}
