import fs from 'fs';import path from 'path';import crypto from 'crypto';let cached;
function deepFreeze(o){if(o&&typeof o==='object'&&!Object.isFrozen(o)){Object.freeze(o);Object.values(o).forEach(deepFreeze)}return o}
function shaBuf(b){return crypto.createHash('sha256').update(b).digest('hex')}
function sha(p){return shaBuf(fs.readFileSync(p))}
export function getModel(){if(!cached)cached=deepFreeze(JSON.parse(fs.readFileSync(path.join(process.cwd(),'data','road-ltl-v1.2-model.json'),'utf8')));return cached}
export function getIntegrityManifest(){return JSON.parse(fs.readFileSync(path.join(process.cwd(),'data','integrity-manifest.json'),'utf8'))}
function stripGuide(buf){const s=buf.toString('utf8'),a='<!-- V6.2.3 ADDITIVE GUIDE START -->',b='<!-- V6.2.3 ADDITIVE GUIDE END -->';const i=s.indexOf(a),j=s.indexOf(b);if(i<0||j<0)return null;const before=s.slice(0,i),after=s.slice(j+b.length);return Buffer.from((before+after).replace(/^\n(?=<\/body>)/m,''),'utf8')}
export function verifyModelIntegrity(){const m=getIntegrityManifest(),cwd=process.cwd(),deployed=fs.readFileSync(path.join(cwd,'public','atlas.html')),stripped=stripGuide(deployed);const actual={model:sha(path.join(cwd,'data','road-ltl-v1.2-model.json')),deployedV623:shaBuf(deployed),publicFrozenV622:sha(path.join(cwd,'public','atlas-v6.2.2-frozen.html')),integratedFrozen:sha(path.join(cwd,'frozen',m.integratedRoadLtl.name)),page0Frozen:sha(path.join(cwd,'frozen',m.frozenPage0.name)),strippedFoundation:stripped?shaBuf(stripped):null,constitution:sha(path.join(cwd,'data','atlas-constitution-v6.2.3.json'))};const checks={model:actual.model===m.extractedModel.sha256,deployedV623:actual.deployedV623===m.additiveV623.sha256,publicFrozenV622:actual.publicFrozenV622===m.integratedRoadLtl.sha256,integratedFrozen:actual.integratedFrozen===m.integratedRoadLtl.sha256,page0Frozen:actual.page0Frozen===m.frozenPage0.sha256,strippedFoundation:actual.strippedFoundation===m.integratedRoadLtl.sha256,constitution:actual.constitution===m.constitution.sha256};return {ok:Object.values(checks).every(Boolean),checks,actual,contract:m.contract,mutationPolicy:m.mutationPolicy,additivePolicy:m.additivePolicy}}
export const processById=id=>getModel().processes.find(p=>p.id===id);export const sourceById=id=>getModel().sources.find(s=>s.id===id);
