import fs from 'node:fs';
import path from 'node:path';
const cache=new Map();
function readJson(rel){if(cache.has(rel))return cache.get(rel);const x=JSON.parse(fs.readFileSync(path.join(process.cwd(),rel),'utf8'));cache.set(rel,x);return x}
function activeEntries(registry){return (registry.modules||[]).filter(x=>x.status==='ACTIVE'&&x.source)}
function loadModules(registry){return activeEntries(registry).map(entry=>({entry,module:readJson(entry.source)}))}
function buildIndexes(rows){const processById={},sourceById={},moduleByProcessId={},moduleById={};for(const {entry,module} of rows){moduleById[entry.id]=module;for(const p of module.processes||[]){if(processById[p.id])throw new Error(`Duplicate process id ${p.id}`);processById[p.id]=p;moduleByProcessId[p.id]=entry.id}for(const s of module.sources||[])sourceById[s.id]??=s}return{processById,sourceById,moduleByProcessId,moduleById}}
export function atlasData(){const registry=readJson('data/atlas-registry.json'),catalog=readJson('data/module-catalog.json'),page0=readJson(registry.baseModule?.source||'data/page0/page0-v6.2.2.json'),active=loadModules(registry),idx=buildIndexes(active);return{registry,catalog,page0,activeModules:active,moduleById:idx.moduleById,moduleByProcessId:idx.moduleByProcessId,processById:idx.processById,sourceById:idx.sourceById,roadLtl:idx.moduleById['road-ltl']||null,overlays:readJson('governance/overlay-registry-v1.json'),foundationOverlays:readJson('governance/overlay-registry-v1.1.json'),rules:readJson('governance/rule-registry-v1.json'),foundationRules:readJson('governance/rule-registry-v1.1.json'),commandContract:readJson('governance/canvas-command-contract-v1.json')}}
function toks(s){return[...new Set(String(s||'').toLowerCase().replace(/[^a-z0-9-]+/g,' ').split(/\s+/).filter(x=>x.length>2&&!['the','and','for','with','show','what','where','why','how','this','that','atlas','please','tell'].includes(x)))]}
function text(x){return JSON.stringify(x).toLowerCase()}
function scoreItem(item,terms,boost=0){const h=text(item);return boost+terms.reduce((n,t)=>n+(h.includes(t)?1:0),0)}
function add(out,item){if(!out.some(x=>x.key===item.key))out.push(item)}
function sourceTitle(s){return `${s.issuer||'Source'} · ${s.title||s.id}`}
export function activeModuleIds(context={}){const {registry}=atlasData(),active=new Set(activeEntries(registry).map(x=>x.id)),asked=[...(Array.isArray(context.moduleIds)?context.moduleIds:[]),context.moduleId,context.mode,context.service].filter(Boolean),matched=asked.filter(x=>active.has(x));return matched.length?[...new Set(matched)]:[...active]}
export function coverageMatch(q,registry=atlasData().registry){const l=String(q||'').toLowerCase();return(registry.items||[]).filter(x=>l.includes(String(x.name||'').toLowerCase())).slice(0,4)}
export function retrieveAtlas(question,state={},client=null){const A=atlasData(),terms=toks(question),out=[],moduleIds=activeModuleIds(state),allowed=new Set(moduleIds);let seq=1;const selected=state.selectedProcess||state.playback?.processId||null;
 const processes=Object.entries(A.processById).filter(([id])=>allowed.has(A.moduleByProcessId[id])).map(([id,p])=>({p,moduleId:A.moduleByProcessId[id],s:scoreItem(p,terms,id===selected?12:0)})).sort((a,b)=>b.s-a.s);
 for(const {p,moduleId,s} of processes.slice(0,Math.max(4,Math.min(8,processes.filter(x=>x.s>0).length||4)))){if(s<=0&&!selected)continue;add(out,{key:'p:'+p.id,id:`E${seq++}`,class:'ATLAS_PROCESS',title:`${p.id} · ${p.label}`,sourceIds:p.sourceIds||[],moduleId,content:{id:p.id,label:p.label,a3:p.a3ParentLabel,pathType:p.pathType,trigger:p.trigger,stateBefore:p.before,event:p.event,decision:p.decision,rule:p.rule,control:p.control,action:p.action,evidence:p.evidence,stateAfter:p.after,outcome:p.outcome,performer:p.performer,owner:p.owner,custody:p.custody,inputs:p.inputs,outputs:p.outputs,authoritySystem:p.authoritySystem,producer:p.producer,consumers:p.consumers,claimBoundary:p.claimBoundary,provenance:p.provenance}})}
 const sourceIds=new Set(out.flatMap(x=>x.sourceIds||[]));for(const s of Object.values(A.sourceById)){const sc=scoreItem(s,terms,sourceIds.has(s.id)?5:0);if(sc<=0)continue;add(out,{key:'s:'+s.id,id:`E${seq++}`,class:'ATLAS_SOURCE',title:sourceTitle(s),sourceIds:[s.id],content:{id:s.id,issuer:s.issuer,title:s.title,version:s.version,confidence:s.confidence,research:s.research,supports:s.supports,doesNotSupport:s.notSupports,scope:[s.modeScope,s.jurisdictionScope,s.roleScope].filter(Boolean).join(' · '),url:s.url}});if(out.length>=12)break}
 for(const c of coverageMatch(question,A.registry))add(out,{key:'c:'+c.id,id:`E${seq++}`,class:'COVERAGE',title:`Coverage · ${c.name}`,sourceIds:[],content:{id:c.id,name:c.name,status:c.status,depth:c.depth,category:c.category||c.family||null}});
 const domains=A.page0.domains||A.page0.page0Domains||[];for(const d of domains.map(d=>({d,s:scoreItem(d,terms,state.selectedDomain===d.id?5:0)})).sort((a,b)=>b.s-a.s).slice(0,3))if(d.s>0)add(out,{key:'d:'+d.d.id,id:`E${seq++}`,class:'ATLAS_DOMAIN',title:`Page 0 · ${d.d.title||d.d.name||d.d.label||d.d.id}`,sourceIds:d.d.sources||[],content:d.d});
 if(client?.workspace){const ws=client.workspace,mp=ws.mappings||{},ev=ws.evidence||{},ids=[selected,...Object.keys(mp).filter(id=>terms.some(t=>text(mp[id]).includes(t)))].filter(Boolean);for(const id of [...new Set(ids)].slice(0,4)){const m=mp[id];if(!m)continue;add(out,{key:'cm:'+id,id:`E${seq++}`,class:'CLIENT_MAPPING',title:`Client mapping · ${id}`,sourceIds:[],content:{processId:id,status:m.status,clientLabel:m.clientLabel,clientOwner:m.clientOwner,clientSystems:m.clientSystems,alignment:m.alignment,deviationNote:m.deviationNote,rationale:m.rationale,evidenceIds:m.evidenceIds||[]}});for(const eid of(m.evidenceIds||[]).slice(0,3)){const e=ev[eid];if(e)add(out,{key:'ce:'+eid,id:`E${seq++}`,class:'CLIENT_EVIDENCE',title:`Client evidence · ${e.title||eid}`,sourceIds:[],content:{id:eid,type:e.type,title:e.title,note:e.note,fileName:e.fileName||''}})}}}
 return out.slice(0,16)}
export function validateCanvasState(state={}){const A=atlasData(),errors=[],mid=state.moduleId||state.activeModule;if(mid&&!A.moduleById[mid]){const r=(A.registry.items||[]).find(x=>x.id===mid||String(x.name||'').toLowerCase()===String(mid).toLowerCase());if(!r||r.depth!=='A5_VERIFIED')errors.push('Requested module does not have published A5 execution depth.')}if(state.selectedProcess&&!A.processById[state.selectedProcess])errors.push('Selected process is not in an active published module.');return{valid:!errors.length,errors}}
export function validateCommands(commands=[],state={}){const A=atlasData(),defs=A.commandContract.commands||{},valid=[],rejected=[];for(const c of Array.isArray(commands)?commands:[]){const type=String(c?.type||''),args=c?.args&&typeof c.args==='object'?c.args:{},d=defs[type];if(!d){rejected.push({command:c,reason:'Unknown command type'});continue}if((d.required||[]).some(k=>args[k]===undefined||args[k]===null||args[k]==='')){rejected.push({command:c,reason:'Missing required argument'});continue}let reason='',normalizedArgs={...args};if(type==='activate_module'&&!A.moduleById[args.moduleId])reason='Module is not A5-verified/published.';if(type==='select_process'&&!A.processById[args.processId])reason='Process ID is not in an active published module.';if(type==='open_source'&&!A.sourceById[args.sourceId])reason='Source ID is not in an active published module.';if(type==='set_semantic_level'&&!d.allowedLevels.includes(Number(args.level)))reason='Unsupported semantic level.';if(type==='playback'&&!d.allowedActions.includes(args.action))reason='Unsupported playback action.';if(type==='set_follow_signal'&&!d.allowedSignals.includes(args.signal))reason='Unsupported signal.';if(type==='open_lens'&&!d.allowedLenses.includes(args.lens))reason='Unsupported lens.';if(type==='set_context_option'){if(!d.allowedDimensions.includes(args.dimension))reason='Unsupported context dimension.';else{const list=A.overlays.overlays||A.overlays.items||[],o=list.find(o=>o.id===args.optionId||(o.dimension===args.dimension&&o.sourceContextId===args.optionId));if(!o)reason='Unknown overlay option.';else if(o.dimension!==args.dimension)reason='Overlay belongs to a different context dimension.';else normalizedArgs.optionId=o.sourceContextId}}if(reason)rejected.push({command:c,reason});else valid.push({type,args:normalizedArgs})}return{valid,rejected}}
export function deterministicPlan(question,state={}){const l=String(question||'').toLowerCase(),commands=[];if(/\b(show|activate|open)\b.*\broad\s*ltl\b|\broad\s*ltl\b/.test(l))commands.push({type:'activate_module',args:{moduleId:'road-ltl'}});if(/\b(universe|reset|page\s*0)\b/.test(l))commands.push({type:'reset_universe',args:{}});if(/\b(play|start)\b.*\bexecution\b/.test(l))commands.push({type:'playback',args:{action:'start'}});if(/\bpause\b/.test(l))commands.push({type:'playback',args:{action:'pause'}});if(/\bfreeze\b/.test(l))commands.push({type:'playback',args:{action:'freeze'}});if(/step forward|next step/.test(l))commands.push({type:'playback',args:{action:'step_forward'}});if(/step back|previous step/.test(l))commands.push({type:'playback',args:{action:'step_back'}});for(const[k,v]of[['physical','physical'],['information','information'],['document','data'],['data','data'],['money','financial'],['financial','financial'],['control','control']])if(l.includes('follow '+k)||l.includes('show only '+k)){commands.push({type:'set_follow_signal',args:{signal:v}});break}if(/trace shipment/.test(l))commands.push({type:'trace_object',args:{objectId:'obj-shipment'}});if(/trace handling unit/.test(l))commands.push({type:'trace_object',args:{objectId:'obj-handling-unit'}});if(/trace (invoice)/.test(l))commands.push({type:'trace_object',args:{objectId:'obj-invoice'}});if(/show actors|actor lens/.test(l))commands.push({type:'open_lens',args:{lens:'actors'}});if(/show systems|system lens/.test(l))commands.push({type:'open_lens',args:{lens:'systems'}});if(/show controls|control lens/.test(l))commands.push({type:'open_lens',args:{lens:'controls'}});if(/show sources|source lens/.test(l))commands.push({type:'open_lens',args:{lens:'sources'}});if(/clear context|reset context|remove context/.test(l))commands.push({type:'clear_context',args:{}});if(/add|apply|set context|use context|now make|now add/.test(l)){const list=atlasData().overlays.overlays||[];let best=null,score=0,qt=toks(l);for(const o of list){const hay=(o.name+' '+o.sourceContextId).toLowerCase();let sc=qt.reduce((n,t)=>n+(hay.includes(t)?1:0),0);if(/hazmat|dangerous goods/.test(l)&&/dangerous goods/i.test(o.name))sc+=6;if(sc>score){best=o;score=sc}}if(best&&score>0)commands.push({type:'set_context_option',args:{dimension:best.dimension,optionId:best.sourceContextId}})}if(/transform|transformation/.test(l))commands.push({type:'enter_transform',args:{}});if(/show findings|finding register/.test(l))commands.push({type:'open_findings',args:{}});if(/show opportunities|opportunity portfolio/.test(l))commands.push({type:'open_opportunities',args:{}});return commands}
