import {send,body,err,requireUser,requireAdmin,supabase,supabaseService} from './_utils.js';
import {retrieveAtlas,normalizeSurfaceState,validateSurfaceState,validateCommands,deterministicPlan,atlasData} from './_atlas.js';
import {generateAtlasJson,providerStatus} from './_llm.js';

async function clientWorkspace(req,workspaceId){
  if(!workspaceId)return null;const {token,user}=await requireUser(req);
  const id=encodeURIComponent(workspaceId);const {data}=await supabase(`/rest/v1/atlas_client_states?workspace_id=eq.${id}&select=state,module_id,module_version&limit=1`,{token,headers:{Accept:'application/json'}});return data?.[0]?{workspace:data[0].state,moduleId:data[0].module_id,moduleVersion:data[0].module_version,userId:user.id}:{workspace:null,moduleId:null,moduleVersion:null,userId:user.id}
}
function moduleIdFromDomain(domain=''){const d=String(domain);if(d.includes('road-ltl'))return'road-ltl';if(d.includes('ocean-fcl'))return'ocean-fcl';if(d.includes('ocean-lcl'))return'ocean-lcl';return null}
async function protectedAdminContext(req,state){
  if(state.surface!=='admin')return null;
  const {user}=await requireAdmin(req);const selected=state.selectedProcess?`&source_task_id=eq.${encodeURIComponent(state.selectedProcess)}`:'';
  const q=`/rest/v1/atlas_work_definitions?status=eq.ACTIVE${selected}&select=definition_id,domain,source_task_id,definition_version,payload&order=source_task_id.asc&limit=${state.selectedProcess?3:8}`;
  const rows=(await supabaseService(q)).data||[];
  const definitions=rows.map(row=>{const p=row.payload||{};return{...p,definitionId:p.definitionId||row.definition_id,sourceTaskId:p.sourceTaskId||row.source_task_id,definitionVersion:p.definitionVersion||row.definition_version,moduleId:p.moduleId||moduleIdFromDomain(row.domain),domain:row.domain,sourceIds:p.sourceIds||p.lineage?.sourceIds||[]}});
  return{authorized:true,userId:user.id,definitions}
}
function safeResult(raw,evidence,fallbackCommands){
  const allowed=new Set(evidence.map(x=>x.id));const citationIds=[...new Set((raw?.citationIds||[]).filter(x=>allowed.has(x)))];
  const commands=Array.isArray(raw?.commands)?raw.commands:fallbackCommands;const answer=String(raw?.answer||'').trim();
  return {answer,citationIds,commands,needsMoreEvidence:!!raw?.needsMoreEvidence}
}
function compactRef(c){if(!c)return'';for(const k of['description','purpose','summary','short','definition','scope','role','type'])if(c[k])return String(c[k]);return''}
function fallbackAnswer(question,evidence,state){
  const l=String(question||'').toLowerCase();
  const cov=evidence.find(x=>x.class==='COVERAGE');if(cov&&cov.content?.depth!=='A5_VERIFIED'&&/\b(a4|a5|task|workflow|execution sequence|detailed execution|work definition|workdefinition)\b/.test(l))return {answer:`${cov.content.name} is ${cov.content.status} at ${String(cov.content.depth||'reference').replaceAll('_',' ')} depth. Detailed A4/A5 execution is not published, so Ask Atlas will not synthesize it.`,citationIds:[cov.id],needsMoreEvidence:true};
  const wd=evidence.find(x=>x.class==='PROTECTED_WORK_DEFINITION');if(wd){const c=wd.content,counts=[['decomposition elements',c.decomposition?.elements||c.workDecomposition?.elements],['fields',c.fields],['outcomes',c.outcomes],['transitions',c.transitions]].filter(([,v])=>Array.isArray(v)).map(([k,v])=>`${v.length} ${k}`);return{answer:`Protected WorkDefinition ${c.sourceTaskId||c.definitionId}${counts.length?` contains ${counts.join(', ')}.`:''} This detail is available because the current surface is Admin-authorized.`,citationIds:[wd.id],needsMoreEvidence:false}}
  const p=evidence.find(x=>x.class==='ATLAS_PROCESS');if(p){const c=p.content;let answer;if(/why|explain/.test(l))answer=`${c.id} — ${c.label}. ${c.claimBoundary||c.provenance||''}`.trim();else if(/input|output/.test(l))answer=`${c.id} — ${c.label}. Inputs: ${(c.inputs||[]).join(', ')||'not stated'}. Outputs: ${(c.outputs||[]).join(', ')||'not stated'}.`;else if(/system/.test(l))answer=`${c.id} — ${c.label}. Producer: ${c.producer||'not stated'}. System of authority: ${c.authoritySystem||'not stated'}. Consumers: ${Array.isArray(c.consumers)?c.consumers.join(', '):(c.consumers||'not stated')}.`;else answer=`${c.id} — ${c.label}. Event: ${c.event||'not stated'}. Decision: ${c.decision||'not stated'}. Action: ${c.action||'not stated'}. State after: ${c.stateAfter||'not stated'}.`;return {answer,citationIds:[p.id,...evidence.filter(x=>x.class==='ATLAS_SOURCE'&&(p.sourceIds||[]).some(s=>x.sourceIds?.includes(s))).slice(0,2).map(x=>x.id)],needsMoreEvidence:false}}
  const refs=evidence.filter(x=>/^ATLAS_(DOMAIN|NAV_ITEM|SYSTEM|OBJECT|DOCUMENT|EVENT|RELATIONSHIP|JURISDICTION|CARRIAGE_REGIME|CONDITION|EXECUTIVE_INTENT)$/.test(x.class));if(refs.length){const first=refs[0],many=/\b(which|list|what systems|what documents|what objects|available|where)\b/.test(l);if(many&&refs.length>1)return{answer:`From the published Universe, relevant items include ${refs.slice(0,6).map(x=>x.content?.name||x.title.replace(/^Universe · /,'')).join(', ')}.`,citationIds:refs.slice(0,6).map(x=>x.id),needsMoreEvidence:false};const detail=compactRef(first.content);return{answer:`${first.content?.name||first.title.replace(/^Universe · /,'')}${detail?` — ${detail}`:''}.`,citationIds:[first.id],needsMoreEvidence:false}}
  if(cov)return{answer:`${cov.content.name}: ${cov.content.status}; published depth ${String(cov.content.depth||'reference').replaceAll('_',' ')}.`,citationIds:[cov.id],needsMoreEvidence:cov.content.depth!=='A5_VERIFIED'};
  if(evidence.length)return {answer:`I found published Atlas evidence relevant to the request, but the deterministic fallback does not have enough evidence to form a more specific answer. Open the cited evidence or configure the server-side LLM gateway.`,citationIds:evidence.slice(0,2).map(x=>x.id),needsMoreEvidence:true};
  return {answer:`I could not find sufficient published Atlas evidence for that request. I will not fill the gap from general model knowledge.`,citationIds:[],needsMoreEvidence:true}
}
export default async function handler(req,res){
 try{
  if(req.method!=='POST')return send(res,405,{ok:false,error:'Method not allowed'});const b=await body(req);const question=String(b.question||'').trim();if(!question)return send(res,400,{ok:false,error:'question is required'});
  const supplied=(b.surfaceState&&typeof b.surfaceState==='object')?b.surfaceState:((b.canvasState&&typeof b.canvasState==='object')?{...b.canvasState,surface:'canvas'}:{});const state=normalizeSurfaceState(supplied);const vs=validateSurfaceState(state);if(!vs.valid)return send(res,409,{ok:false,error:'Atlas surface state failed validation',details:vs.errors});
  const protectedContext=await protectedAdminContext(req,state),client=await clientWorkspace(req,b.workspaceId||null),evidence=retrieveAtlas(question,state,client,protectedContext),fallbackCommands=deterministicPlan(question,state),pstat=providerStatus();
  if(!fallbackCommands.length&&/take me|go to|inspect|focus on|open task/i.test(question)){const pe=evidence.find(x=>x.class==='ATLAS_PROCESS');if(pe?.content?.id)fallbackCommands.push(state.surface==='canvas'?{type:'select_process',args:{processId:pe.content.id}}:{type:'open_in_canvas',args:{moduleId:pe.moduleId,processId:pe.content.id}})}
  if(!fallbackCommands.length&&/show source|open source|evidence source/i.test(question)){const se=evidence.find(x=>x.class==='ATLAS_SOURCE');if(se?.content?.id)fallbackCommands.push({type:'open_source',args:{sourceId:se.content.id}})}
  const system=`You are Ask Atlas, the governed natural-language intelligence layer shared by the Supply Chain Atlas Universe, Daughter modules, Canvas and protected Admin Execution surface. You may reason only from EVIDENCE supplied in this request. Do not add general logistics knowledge. If evidence is incomplete, say so. Respect coverage depth: never synthesize unpublished A4/A5 execution. Atlas Reference, Client evidence and Protected WorkDefinition evidence are different epistemic classes. Never treat a deviation as a gap, a diagnostic signal as a validated risk, or a proposed TO-BE as source fact. Protected WorkDefinition evidence may only appear on an Admin-authorized request; never imply it exists on a public surface. You may PROPOSE Atlas UI commands, but deterministic code validates and executes them. Return strict JSON with keys: answer (string), citationIds (array of evidence IDs), commands (array of {type,args}), needsMoreEvidence (boolean). Every substantive claim in answer must be supported by citationIds. Use only evidence IDs and entity/process/module IDs supplied in EVIDENCE or AVAILABLE GOVERNED OPTIONS. Do not invent IDs.`;
  const history=Array.isArray(b.history)?b.history.slice(-8).map(x=>({role:String(x.role||''),text:String(x.text||'').slice(0,1200)})):[];
  const contextOptions=(atlasData().overlays.overlays||[]).map(o=>({dimension:o.dimension,optionId:o.sourceContextId,name:o.name,scope:o.scope,moduleId:o.moduleId}));
  const user=`QUESTION:\n${question}\n\nRECENT CONVERSATION:\n${JSON.stringify(history)}\n\nATLAS SURFACE STATE:\n${JSON.stringify(state)}\n\nAVAILABLE GOVERNED CONTEXT OPTIONS:\n${JSON.stringify(contextOptions)}\n\nEVIDENCE:\n${JSON.stringify(evidence)}\n\nDETERMINISTIC COMMAND HINTS:\n${JSON.stringify(fallbackCommands)}`;
  let raw=null,providerError=null;if(pstat.configured){try{raw=await generateAtlasJson(system,user)}catch(e){providerError=e.message}}
  const fb=raw?null:fallbackAnswer(question,evidence,state);let base=raw?safeResult(raw,evidence,fallbackCommands):{...fb,commands:fallbackCommands};
  let providerAnswerRejected=false;if(raw&&evidence.length&&base.citationIds.length===0){const safe=fallbackAnswer(question,evidence,state);base={...safe,commands:base.commands?.length?base.commands:fallbackCommands};providerAnswerRejected=true}
  const vc=validateCommands(base.commands,state);const citations=base.citationIds.map(id=>{const e=evidence.find(x=>x.id===id);return e?{id:e.id,class:e.class,title:e.title,sourceIds:e.sourceIds||[],moduleId:e.moduleId||null,content:e.content}:null}).filter(Boolean),protectedUsed=citations.some(x=>x.class==='PROTECTED_WORK_DEFINITION');
  const headers=protectedContext||protectedUsed?{'Cache-Control':'private, no-store, max-age=0'}:{'Cache-Control':'no-store, max-age=0'};
  send(res,200,{ok:true,stage:'atlas-2.0-universal-ask',surface:state.surface,answer:base.answer,citations,commands:vc.valid,rejectedCommands:vc.rejected,needsMoreEvidence:base.needsMoreEvidence,provider:{...pstat,used:!!raw,error:providerError||null,answerRejectedForMissingCitations:providerAnswerRejected},grounding:{retrieved:evidence.length,cited:citations.length,clientEvidenceUsed:citations.some(x=>x.class.startsWith('CLIENT_')),protectedEvidenceUsed:protectedUsed,clientWorkspaceRequested:!!b.workspaceId,scope:{surface:state.surface,moduleId:state.moduleId||null,selectedProcess:state.selectedProcess||null}}},headers)
 }catch(e){err(res,e)}
}
