import {body,send,supabase,requireUser,err} from './_utils.js';
import {extractCandidateFacts} from './_documents.js';
import {documentDomainRuntime} from './_document-domain.js';
export default async function handler(req,res){try{const {token,user}=await requireUser(req);if(req.method==='GET'){const wid=String(req.query?.workspaceId||'');if(!wid)return send(res,400,{ok:false,error:'workspaceId is required'});const q=`/rest/v1/atlas_client_documents?workspace_id=eq.${encodeURIComponent(wid)}&select=id,original_filename,mime_type,size_bytes,sha256,document_type,ingestion_status,validation_class,validation_reason,extraction_method,extracted_chars,relevance_score,relevance_terms,metadata,created_at,updated_at&order=created_at.desc&limit=100`;const {data}=await supabase(q,{token});return send(res,200,{ok:true,documents:data||[]})}
 if(req.method==='PATCH'){const b=await body(req);if(!b.workspaceId||!b.documentId||!['ACCEPT_RELEVANCE','REJECT_IRRELEVANT'].includes(b.action))return send(res,400,{ok:false,error:'workspaceId, documentId and action ACCEPT_RELEVANCE|REJECT_IRRELEVANT are required'});const q=`/rest/v1/atlas_client_documents?id=eq.${encodeURIComponent(b.documentId)}&workspace_id=eq.${encodeURIComponent(b.workspaceId)}&select=id,original_filename,mime_type,document_type,ingestion_status,validation_class,metadata&limit=1`;const d=(await supabase(q,{token})).data?.[0];if(!d)return send(res,404,{ok:false,error:'Document not found in workspace'});if(d.validation_class==='GARBAGE'||d.validation_class==='SECURITY_REJECTED')return send(res,409,{ok:false,error:'A technical/security rejection cannot be manually promoted. Upload a valid source document.'});const meta={...(d.metadata||{}),manualRelevanceReview:{action:b.action,actor:user.id,at:new Date().toISOString(),note:String(b.note||'').slice(0,800)}};
   if(b.action==='REJECT_IRRELEVANT'){await supabase(`/rest/v1/atlas_client_documents?id=eq.${d.id}`,{method:'PATCH',token,headers:{Prefer:'return=minimal'},data:{ingestion_status:'REJECTED',validation_class:'IRRELEVANT',validation_reason:`Consultant rejected document as irrelevant. ${String(b.note||'').slice(0,800)}`.trim(),metadata:meta}});return send(res,200,{ok:true,documentId:d.id,status:'REJECTED',validationClass:'IRRELEVANT',candidateCount:0,clientTwinChanged:false})}
   const cq=`/rest/v1/atlas_document_chunks?document_id=eq.${encodeURIComponent(d.id)}&workspace_id=eq.${encodeURIComponent(b.workspaceId)}&select=chunk_index,locator,content,char_count&order=chunk_index.asc&limit=100`;const chunks=(await supabase(cq,{token})).data||[];const domain=documentDomainRuntime({domainPackId:d.metadata?.domainPackId||'supply-chain',moduleId:d.metadata?.moduleId||'road-ltl'});let candidates=[];if(chunks.length){const ext=await extractCandidateFacts(chunks.map(x=>({chunkIndex:x.chunk_index,locator:x.locator,content:x.content,charCount:x.char_count})),{fileName:d.original_filename,mimeType:d.mime_type,documentType:d.document_type,validationClass:'VALID',domainPackId:domain.domainPackId,moduleId:domain.moduleId},domain);candidates=ext.facts||[];if(candidates.length){const existing=(await supabase(`/rest/v1/atlas_candidate_facts?document_id=eq.${encodeURIComponent(d.id)}&workspace_id=eq.${encodeURIComponent(b.workspaceId)}&select=fact_key`,{token})).data||[],seen=new Set(existing.map(x=>x.fact_key)),rows=candidates.filter(f=>!seen.has(f.factKey)).map(f=>({workspace_id:b.workspaceId,document_id:d.id,fact_key:f.factKey,fact_type:f.factType,statement:f.statement,process_id:f.processId,canonical_type:f.canonicalType,canonical_id:f.canonicalId,canonical_label:f.canonicalLabel,evidence_quote:f.evidenceQuote,evidence_locator:f.evidenceLocator,confidence:f.confidence,extraction_method:f.extractionMethod,mapping_status:f.mappingStatus,proposed_patch:f.proposedPatch||{}}));if(rows.length)await supabase('/rest/v1/atlas_candidate_facts',{method:'POST',token,data:rows});meta.factExtraction={method:ext.method,provider:ext.provider}}}
   await supabase(`/rest/v1/atlas_client_documents?id=eq.${d.id}`,{method:'PATCH',token,headers:{Prefer:'return=minimal'},data:{ingestion_status:'ACCEPTED',validation_class:'VALID',validation_reason:`Consultant accepted document relevance. ${String(b.note||'').slice(0,800)}`.trim(),metadata:meta}});return send(res,200,{ok:true,documentId:d.id,status:'ACCEPTED',validationClass:'VALID',candidateCount:candidates.length,clientTwinChanged:false})}
 return send(res,405,{ok:false,error:'Method not allowed'});}catch(e){err(res,e)}}
