import {body,send,supabase,requireUser,err} from './_utils.js';
function safeEvidenceId(id){return 'DOC-'+String(id).replace(/[^a-zA-Z0-9-]/g,'').slice(0,48)}
export default async function handler(req,res){
 try{const {token,user}=await requireUser(req);if(req.method==='GET'){const wid=String(req.query?.workspaceId||''),doc=String(req.query?.documentId||'');if(!wid)return send(res,400,{ok:false,error:'workspaceId is required'});let q=`/rest/v1/atlas_candidate_facts?workspace_id=eq.${encodeURIComponent(wid)}`;if(doc)q+=`&document_id=eq.${encodeURIComponent(doc)}`;q+='&select=id,document_id,fact_key,fact_type,statement,process_id,canonical_type,canonical_id,canonical_label,evidence_quote,evidence_locator,confidence,extraction_method,mapping_status,review_status,proposed_patch,review_note,created_at,reviewed_at&order=created_at.asc&limit=300';const {data}=await supabase(q,{token});return send(res,200,{ok:true,facts:data||[]})}
   if(req.method!=='PATCH')return send(res,405,{ok:false,error:'Method not allowed'});const b=await body(req);if(!b.workspaceId||!b.factId||!['CONFIRM','REJECT'].includes(b.action))return send(res,400,{ok:false,error:'workspaceId, factId and action CONFIRM|REJECT are required'});const q=`/rest/v1/atlas_candidate_facts?id=eq.${encodeURIComponent(b.factId)}&workspace_id=eq.${encodeURIComponent(b.workspaceId)}&select=*&limit=1`;const fact=(await supabase(q,{token})).data?.[0];if(!fact)return send(res,404,{ok:false,error:'Candidate fact not found in workspace'});
   if(b.action==='REJECT'){await supabase(`/rest/v1/atlas_candidate_facts?id=eq.${fact.id}`,{method:'PATCH',token,headers:{Prefer:'return=minimal'},data:{review_status:'REJECTED',reviewed_by:user.id,reviewed_at:new Date().toISOString(),review_note:String(b.note||'').slice(0,1200)}});return send(res,200,{ok:true,status:'REJECTED',factId:fact.id,clientTwinChanged:false})}
   const stateQ=`/rest/v1/atlas_client_states?workspace_id=eq.${encodeURIComponent(b.workspaceId)}&select=*&limit=1`;const current=(await supabase(stateQ,{token})).data?.[0];const ws=structuredClone(current?.state||{schemaVersion:'client-as-is-mapping-v0.4',name:'Client Workspace',moduleId:'road-ltl',mappings:{},evidence:{}});ws.mappings=ws.mappings||{};ws.evidence=ws.evidence||{};ws.confirmedDocumentFacts=ws.confirmedDocumentFacts||{};
   const eid=safeEvidenceId(fact.id);ws.evidence[eid]={id:eid,type:'PROCESS_DOCUMENT',title:`Document evidence · ${fact.canonical_label||fact.fact_type}`,note:fact.evidence_quote,fileName:'Private client document',createdAt:new Date().toISOString(),processId:fact.process_id||null,documentFactId:fact.id,documentId:fact.document_id,locator:fact.evidence_locator};ws.confirmedDocumentFacts[fact.id]={id:fact.id,factType:fact.fact_type,statement:fact.statement,processId:fact.process_id,canonicalId:fact.canonical_id,confirmedAt:new Date().toISOString(),evidenceId:eid,reviewNote:String(b.note||'').slice(0,1200)};
   if(fact.process_id){const m=ws.mappings[fact.process_id]||{processId:fact.process_id,status:'UNKNOWN',clientLabel:'',clientOwner:'',clientSystems:'',alignment:'NOT_ASSESSED',deviationNote:'',rationale:'',evidenceIds:[],updatedAt:null};m.evidenceIds=[...new Set([...(m.evidenceIds||[]),eid])];const pp=fact.proposed_patch||{};if(fact.fact_type==='PROCESS_EXISTS'||pp.confirmProcess===true)m.status='CLIENT_CONFIRMED';if(fact.fact_type==='PROCESS_LABEL'&&pp.clientLabel)m.clientLabel=String(pp.clientLabel).slice(0,300);if(fact.fact_type==='OWNER'&&pp.clientOwner)m.clientOwner=String(pp.clientOwner).slice(0,300);if(fact.fact_type==='SYSTEM'&&pp.clientSystem){const a=String(m.clientSystems||'').split(/[,;]\s*/).filter(Boolean);a.push(String(pp.clientSystem));m.clientSystems=[...new Set(a)].join(', ')}m.updatedAt=new Date().toISOString();ws.mappings[fact.process_id]=m}
   ws.updatedAt=new Date().toISOString();const revision=Number(current?.revision||0)+1;const row={workspace_id:b.workspaceId,schema_version:ws.schemaVersion||'client-as-is-mapping-v0.4',module_id:ws.moduleId||current?.module_id||'road-ltl',module_version:current?.module_version||null,state:ws,revision,updated_by:user.id};await supabase('/rest/v1/atlas_client_states?on_conflict=workspace_id',{method:'POST',token,headers:{Prefer:'resolution=merge-duplicates,return=minimal'},data:row});await supabase(`/rest/v1/atlas_candidate_facts?id=eq.${fact.id}`,{method:'PATCH',token,headers:{Prefer:'return=minimal'},data:{review_status:'CONFIRMED',reviewed_by:user.id,reviewed_at:new Date().toISOString(),review_note:String(b.note||'').slice(0,1200)}});send(res,200,{ok:true,status:'CONFIRMED',factId:fact.id,clientTwinChanged:true,processId:fact.process_id||null,evidenceId:eid,guardrail:'Promotion occurred only because an authenticated consultant explicitly confirmed this candidate fact.'});
 }catch(e){err(res,e)}
}
