import crypto from 'node:crypto';
import {body,send,supabase,requireUser,safeName,err} from './_utils.js';
import {extractDocument,sha256,validateExtractedText,relevance,chunkText,extractCandidateFacts} from './_documents.js';
import {documentDomainRuntime} from './_document-domain.js';
const ALLOWED=new Set(['application/pdf','text/plain','text/markdown','text/csv','application/json','image/png','image/jpeg','image/webp','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/vnd.openxmlformats-officedocument.presentationml.presentation']);
function b64(s){if(!/^[A-Za-z0-9+/=\r\n]+$/.test(String(s||'')))throw Object.assign(new Error('Invalid base64 payload'),{status:400});return Buffer.from(s,'base64')}
export default async function handler(req,res){
 try{if(req.method!=='POST')return send(res,405,{ok:false,error:'Method not allowed'});const {token,user}=await requireUser(req),b=await body(req);if(!b.workspaceId||!b.fileName||!b.base64)return send(res,400,{ok:false,error:'workspaceId, fileName and base64 are required'});const domain=documentDomainRuntime({domainPackId:String(b.domainPackId||'supply-chain'),moduleId:String(b.moduleId||'road-ltl')});const mime=String(b.mimeType||'application/octet-stream');if(!ALLOWED.has(mime))return send(res,415,{ok:false,error:'Unsupported client document type'});const bytes=b64(b.base64);if(bytes.length>3*1024*1024)return send(res,413,{ok:false,error:'Stage 19 inline ingestion is capped at 3 MB because of serverless request limits. Store larger documents through the private evidence path and ingest them through the planned signed-upload worker.'});if(bytes.length<20)return send(res,400,{ok:false,error:'File is empty or too small to be a meaningful client document.'});
   const hash=sha256(bytes);const dupQ=`/rest/v1/atlas_client_documents?workspace_id=eq.${encodeURIComponent(b.workspaceId)}&sha256=eq.${hash}&select=id,original_filename,ingestion_status&limit=1`;const dup=(await supabase(dupQ,{token})).data?.[0];if(dup)return send(res,409,{ok:false,error:'This exact document already exists in the workspace.',duplicate:dup});
   const objectName=`${b.workspaceId}/documents/${new Date().toISOString().slice(0,7)}/${crypto.randomUUID()}-${safeName(b.fileName)}`;await supabase(`/storage/v1/object/atlas-client-documents/${encodeURI(objectName)}`,{method:'POST',token,headers:{'Content-Type':mime,'x-upsert':'false'},rawBody:bytes});
   const extracted=await extractDocument(bytes,mime,b.fileName),tech=validateExtractedText(extracted.text,extracted),rel=tech.status==='ACCEPTED'?relevance(extracted.text,domain):{status:tech.status,class:tech.class,reason:tech.reason,score:0,terms:[]};const finalStatus=tech.status==='REJECTED'?'REJECTED':rel.status;const validationClass=tech.status==='REJECTED'?tech.class:rel.class;const reason=tech.status==='REJECTED'?tech.reason:(extracted.supported?rel.reason:tech.reason);
   const docRow={workspace_id:b.workspaceId,object_name:objectName,original_filename:b.fileName,mime_type:mime,size_bytes:bytes.length,sha256:hash,document_type:b.documentType||null,ingestion_status:finalStatus,validation_class:validationClass,validation_reason:reason,extraction_method:extracted.method,extraction_version:'stage19-v1',extracted_chars:extracted.text?.length||0,relevance_score:Number(rel.score||0),relevance_terms:rel.terms||[],metadata:{extractorMeta:extracted.meta||{},originalNote:b.note||'',providerRequested:true,domainPackId:domain.domainPackId,moduleId:domain.moduleId},uploaded_by:user.id};const saved=(await supabase('/rest/v1/atlas_client_documents',{method:'POST',token,headers:{Prefer:'return=representation'},data:docRow})).data?.[0]||docRow;
   let candidates=[];if(finalStatus!=='REJECTED'&&extracted.supported&&extracted.text){const chunks=chunkText(extracted.text);if(chunks.length){await supabase('/rest/v1/atlas_document_chunks',{method:'POST',token,data:chunks.map(c=>({workspace_id:b.workspaceId,document_id:saved.id,chunk_index:c.chunkIndex,locator:c.locator,content:c.content,char_count:c.charCount}))});if(finalStatus==='ACCEPTED'){const ext=await extractCandidateFacts(chunks,{fileName:b.fileName,mimeType:mime,documentType:b.documentType||null,validationClass,domainPackId:domain.domainPackId,moduleId:domain.moduleId},domain);candidates=ext.facts||[];if(candidates.length)await supabase('/rest/v1/atlas_candidate_facts',{method:'POST',token,data:candidates.map(f=>({workspace_id:b.workspaceId,document_id:saved.id,fact_key:f.factKey,fact_type:f.factType,statement:f.statement,process_id:f.processId,canonical_type:f.canonicalType,canonical_id:f.canonicalId,canonical_label:f.canonicalLabel,evidence_quote:f.evidenceQuote,evidence_locator:f.evidenceLocator,confidence:f.confidence,extraction_method:f.extractionMethod,mapping_status:f.mappingStatus,proposed_patch:f.proposedPatch||{}}))});docRow.metadata.factExtraction={method:ext.method,provider:ext.provider};await supabase(`/rest/v1/atlas_client_documents?id=eq.${saved.id}`,{method:'PATCH',token,headers:{Prefer:'return=minimal'},data:{metadata:docRow.metadata}})}else{docRow.metadata.factExtraction={method:'QUARANTINED_PENDING_RELEVANCE_REVIEW',provider:null};await supabase(`/rest/v1/atlas_client_documents?id=eq.${saved.id}`,{method:'PATCH',token,headers:{Prefer:'return=minimal'},data:{metadata:docRow.metadata}})}}}
   send(res,201,{ok:true,document:{...saved,ingestion_status:finalStatus,validation_class:validationClass,validation_reason:reason,extracted_chars:extracted.text?.length||0,relevance_score:rel.score||0,relevance_terms:rel.terms||[]},candidateCount:candidates.length,guardrail:'Candidate facts are unconfirmed client evidence. Nothing from this upload has been written into the Client Twin.'});
 }catch(e){err(res,e)}
}
