/* Stage 20 · Product Completion Pack
   Investigation Collections · Executive Summary · Presentation Mode
   Transformation Pack exports · lifecycle completion
*/
(function(){
'use strict';
try{ if(typeof S!=='undefined') window.S=S; }catch(e){}
const LATE={PILOT:'Pilot',IMPLEMENTED:'Implemented',MEASURED:'Measured'};
const R={open:false,tab:'collections',selectedCollection:null,presentation:false,presentationStep:0};
const esc20=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const now=()=>new Date().toISOString();
const arr=x=>Array.isArray(x)?x:[];
function ensure(){
  if(typeof S==='undefined'||!S.client?.workspace)return false;
  const w=S.client.workspace;
  w.investigationCollections=w.investigationCollections||{};
  w.stage20=w.stage20||{version:'20.0',createdAt:now()};
  if(typeof OPPORTUNITY_STATUS==='object')Object.assign(OPPORTUNITY_STATUS,LATE);
  return true;
}
function style(){if(document.getElementById('stage20Style'))return;const s=document.createElement('style');s.id='stage20Style';s.textContent=`
.stage20-deliver{display:none}.transform-mode .stage20-deliver{display:inline-flex!important;align-items:center;gap:5px}
.stage20-drawer{position:fixed;z-index:176;right:9px;top:70px;bottom:9px;width:min(560px,calc(100vw - 18px));background:#fff;border:1px solid #d7e3e6;border-radius:15px;box-shadow:0 22px 70px rgba(9,34,43,.22);transform:translateX(calc(100% + 28px));transition:transform .22s;display:flex;flex-direction:column;overflow:hidden}.stage20-drawer.open{transform:translateX(0)}
.stage20-head{display:flex;gap:10px;align-items:flex-start;padding:13px 14px;border-bottom:1px solid #e4ecee;background:linear-gradient(135deg,#f8fbfc,#fff)}.stage20-head>div{flex:1}.stage20-head h3{font-size:14px;margin:0;color:#173b49}.stage20-head p{font-size:9px;color:#75888f;line-height:1.45;margin:3px 0 0}.stage20-close{border:0;background:#f0f5f6;width:30px;height:30px;border-radius:50%;font-size:18px;color:#60757c}
.stage20-tabs{display:flex;gap:3px;padding:7px 9px;border-bottom:1px solid #e7edef;overflow-x:auto;scrollbar-width:none}.stage20-tabs button{white-space:nowrap;border:1px solid transparent;background:transparent;border-radius:7px;padding:6px 8px;font:800 8px ui-monospace;color:#73888f}.stage20-tabs button.active{background:#edf8fa;border-color:#c6e5eb;color:#087c94}
.stage20-body{overflow:auto;padding:11px;display:grid;gap:9px}.stage20-card{border:1px solid #dce6e8;border-radius:10px;padding:10px;background:#fff}.stage20-card h4{font-size:10px;margin:0 0 6px;color:#315763}.stage20-card p,.stage20-note{font-size:8.5px;line-height:1.5;color:#70848b}.stage20-note{border-left:3px solid #81bdc8;background:#f4fafb;padding:8px 9px}.stage20-warn{border-left-color:#d29a31;background:#fff9ea}
.stage20-row{display:flex;gap:6px;align-items:center;flex-wrap:wrap}.stage20-row input,.stage20-row select,.stage20-card textarea{border:1px solid #cfdee1;border-radius:7px;padding:7px 8px;font:10px system-ui;background:#fff;color:#294a54}.stage20-row input{flex:1;min-width:150px}.stage20-card textarea{width:100%;min-height:68px;resize:vertical}.stage20-row button,.stage20-card button{border:1px solid #c9dade;background:#fff;border-radius:7px;padding:6px 8px;font:800 8px ui-monospace;color:#315964}.stage20-row button.primary,.stage20-card button.primary{background:#0d91a8;border-color:#0d91a8;color:#fff}.stage20-row button.danger{color:#a13c45;border-color:#ecc9cc}
.stage20-list{display:grid;gap:6px}.stage20-item{border:1px solid #e0e8ea;border-radius:8px;padding:8px;background:#fafcfc}.stage20-item b{display:block;font-size:9px;color:#365b66}.stage20-item small{display:block;font-size:7.5px;color:#829198;line-height:1.4;margin-top:2px}.stage20-item .stage20-row{margin-top:6px}.stage20-badge{display:inline-flex;border:1px solid #cfe0e4;border-radius:99px;padding:2px 5px;font:850 7px ui-monospace;color:#476d77;background:#f7fbfb;margin-right:4px}.stage20-badge.ok{color:#24714a;border-color:#b9dcc9;background:#eff9f3}.stage20-badge.warn{color:#8a6719;border-color:#efd9a7;background:#fff9e8}
.stage20-summary-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}.stage20-stat{border:1px solid #e1e9eb;border-radius:8px;padding:8px;background:#fafcfc}.stage20-stat b{font-size:15px;color:#087f99;display:block}.stage20-stat span{font:750 7px ui-monospace;color:#7b8d94}.stage20-exec{font-size:10px;line-height:1.55;color:#334f58}.stage20-exec h3{font-size:14px;margin:3px 0 6px}.stage20-exec ul{padding-left:17px}.stage20-exec li{margin:3px 0}
.stage20-export-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.stage20-export{padding:10px!important;text-align:left}.stage20-export b{font-size:9px;display:block}.stage20-export small{font-size:7px;color:#84949a;display:block;margin-top:2px}
.stage20-lifecycle{margin-top:9px;border-top:1px solid #e5ecee;padding-top:9px}.stage20-lifecycle label{display:grid;gap:3px;font:800 8px ui-monospace;color:#60767e;margin-top:7px}.stage20-lifecycle input,.stage20-lifecycle textarea{width:100%;border:1px solid #cedde0;border-radius:7px;padding:7px;font:10px system-ui}.stage20-lifecycle textarea{min-height:58px}.stage20-measured{border-left:3px solid #48a77c;background:#f0faf5;padding:7px 8px;font-size:8px;color:#4e7162;margin-top:7px}
body.stage20-present .top-right,body.stage20-present .sidebar,body.stage20-present .canvas-toolbar button,body.stage20-present .stage-label,body.stage20-present .mesh-note152,body.stage20-present .semantic-zoom152,body.stage20-present .mini-map,body.stage20-present .mobile-dock,body.stage20-present .signal-legend,body.stage20-present .context-chip13,body.stage20-present .lens-chip12,body.stage20-present .path-chip14,body.stage20-present .transform-legend{display:none!important}body.stage20-present .shell{grid-template-columns:1fr!important}body.stage20-present .top{grid-template-columns:1fr!important;padding-right:14px}body.stage20-present .primary{display:none!important}body.stage20-present .canvas-wrap{height:calc(100dvh - 48px)}
.stage20-presenter{display:none;position:fixed;z-index:205;left:50%;transform:translateX(-50%);bottom:12px;width:min(760px,calc(100vw - 18px));background:rgba(255,255,255,.96);backdrop-filter:blur(12px);border:1px solid #cfdee2;border-radius:13px;box-shadow:0 14px 50px rgba(10,32,41,.2);padding:9px 10px}.stage20-presenter.open{display:grid;grid-template-columns:auto 1fr auto;gap:9px;align-items:center}.stage20-presenter button{border:1px solid #cbdcdf;background:#fff;border-radius:8px;padding:7px 9px;font:800 8px ui-monospace;color:#315964}.stage20-presenter b{font-size:11px;color:#294b56}.stage20-presenter small{display:block;font-size:8px;color:#72878e;margin-top:2px}.stage20-presenter .steps{font:800 7px ui-monospace;color:#83949a;margin-top:3px}
@media(max-width:760px){.stage20-drawer{left:8px;right:8px;top:auto;bottom:8px;width:auto;max-height:82dvh;height:auto;border-radius:16px 16px 12px 12px;transform:translateY(calc(100% + 30px))}.stage20-drawer.open{transform:translateY(0)}.stage20-summary-grid{grid-template-columns:repeat(2,1fr)}.stage20-export-grid{grid-template-columns:1fr}.stage20-presenter.open{grid-template-columns:auto 1fr auto;bottom:58px}.stage20-presenter small{display:none}}
`;document.head.appendChild(s)}
function inject(){if(document.getElementById('stage20DeliverBtn'))return;style();const tb=document.querySelector('.canvas-toolbar');if(tb){const b=document.createElement('button');b.id='stage20DeliverBtn';b.className='stage20-deliver';b.textContent='▤ Deliver';const reset=document.getElementById('resetBtn');tb.insertBefore(b,reset||null);b.onclick=open}
 const dock=document.getElementById('mobileDock');if(dock){const b=document.createElement('button');b.id='stage20MobileBtn';b.textContent='▤ Deliver';b.style.display='none';dock.insertBefore(b,dock.lastElementChild);b.onclick=open}
 const d=document.createElement('aside');d.id='stage20Drawer';d.className='stage20-drawer';d.setAttribute('role','dialog');d.setAttribute('aria-hidden','true');d.setAttribute('aria-labelledby','stage20Title');d.innerHTML=`<div class="stage20-head"><div><h3 id="stage20Title">Deliver & Transformation Workbench</h3><p>Collections, executive narrative, presentation and export. No new Atlas knowledge is created here.</p></div><button class="stage20-close" id="stage20Close" aria-label="Close Deliver workbench">×</button></div><div class="stage20-tabs"><button data-s20tab="collections" class="active">Collections</button><button data-s20tab="executive">Executive</button><button data-s20tab="export">Export Pack</button><button data-s20tab="presentation">Presentation</button></div><div class="stage20-body" id="stage20Body"></div>`;document.body.appendChild(d);document.getElementById('stage20Close').onclick=close;d.querySelectorAll('[data-s20tab]').forEach(x=>x.onclick=()=>{R.tab=x.dataset.s20tab;render()});
 const p=document.createElement('div');p.id='stage20Presenter';p.className='stage20-presenter';p.innerHTML=`<button id="s20Prev">←</button><div><b id="s20PresentTitle">Context</b><small id="s20PresentText"></small><div class="steps" id="s20PresentSteps"></div></div><div class="stage20-row"><button id="s20Next">→</button><button id="s20ExitPresent">Exit</button></div>`;document.body.appendChild(p);document.getElementById('s20Prev').onclick=()=>stepPresentation(-1);document.getElementById('s20Next').onclick=()=>stepPresentation(1);document.getElementById('s20ExitPresent').onclick=exitPresentation;
}
function open(){if(typeof S==='undefined'||!S.transform?.enabled){window.enterTransform?.();setTimeout(open,40);return}ensure();try{window.v152CloseSurfaces?.('stage20Drawer')}catch(e){}document.querySelectorAll('.ask-drawer,.trace-drawer,.findings-drawer,.client-drawer,.discovery-drawer,.validation-drawer,.opportunity-drawer,.future-drawer,.compare-drawer,.context-drawer13,.lens-drawer12,.saved-drawer').forEach(x=>x.classList.remove('open'));R.open=true;document.getElementById('stage20Drawer')?.classList.add('open');document.getElementById('stage20Drawer')?.setAttribute('aria-hidden','false');render()}
function close(){R.open=false;document.getElementById('stage20Drawer')?.classList.remove('open');document.getElementById('stage20Drawer')?.setAttribute('aria-hidden','true')}
function collections(){ensure();return Object.values(S.client.workspace.investigationCollections||{}).filter(x=>!x.archived).sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||''))}
function collection(id){return S.client.workspace.investigationCollections?.[id]||null}
function createCollection(){ensure();const i=document.getElementById('s20CollectionName'),name=(i?.value||'').trim();if(!name)return;const id='COL-'+Date.now()+'-'+Math.random().toString(36).slice(2,5).toUpperCase();S.client.workspace.investigationCollections[id]={id,name,items:[],createdAt:now(),updatedAt:now()};R.selectedCollection=id;persistClientWorkspace?.();render()}
function addItem(type,id,label){const c=collection(R.selectedCollection);if(!c)return;const key=type+':'+id;if(!c.items.some(x=>x.key===key))c.items.push({key,type,id,label,addedAt:now()});c.updatedAt=now();persistClientWorkspace?.();render()}
function removeItem(key){const c=collection(R.selectedCollection);if(!c)return;c.items=c.items.filter(x=>x.key!==key);c.updatedAt=now();persistClientWorkspace?.();render()}
function archiveCollection(id){const c=collection(id);if(!c)return;c.archived=true;c.updatedAt=now();if(R.selectedCollection===id)R.selectedCollection=null;persistClientWorkspace?.();render()}
function selectedCandidates(){const out=[];if(S.selectedProcess){const p=S.module?.processes?.find(x=>x.id===S.selectedProcess);out.push({type:'PROCESS',id:S.selectedProcess,label:p?.label||S.selectedProcess})}if(S.transform?.selectedFinding){const f=S.transform.findings?.find(x=>x.id===S.transform.selectedFinding);if(f)out.push({type:'FINDING',id:f.id,label:`${f.label} · ${f.processLabel}`})}if(S.opportunity?.selectedId){const o=opportunityById?.(S.opportunity.selectedId);if(o)out.push({type:'OPPORTUNITY',id:o.id,label:o.title})}return out}
function renderCollections(){const cs=collections();if(!R.selectedCollection&&cs.length)R.selectedCollection=cs[0].id;const c=collection(R.selectedCollection);return `<div class="stage20-card"><h4>Investigation collections</h4><p>Bookmark related tasks, findings and opportunities without duplicating Atlas knowledge. Collections are client-workspace objects.</p><div class="stage20-row" style="margin-top:7px"><input id="s20CollectionName" placeholder="e.g. Revenue leakage investigation"><button class="primary" id="s20CreateCollection">Create</button></div></div><div class="stage20-card"><div class="stage20-row">${cs.length?`<select id="s20CollectionSelect">${cs.map(x=>`<option value="${esc20(x.id)}" ${x.id===R.selectedCollection?'selected':''}>${esc20(x.name)} · ${x.items.length}</option>`).join('')}</select>`:'<span class="stage20-note">No collection yet.</span>'}${c?'<button id="s20ArchiveCollection" class="danger">Archive</button>':''}</div>${c?`<div class="stage20-list" style="margin-top:8px">${c.items.length?c.items.map(x=>`<div class="stage20-item"><span class="stage20-badge">${esc20(x.type)}</span><b>${esc20(x.label)}</b><small>${esc20(x.id)}</small><div class="stage20-row"><button data-s20remove="${esc20(x.key)}">Remove</button></div></div>`).join(''):'<div class="stage20-note">This collection is empty. Select something on the canvas or in Transform, then add it below.</div>'}</div><div class="stage20-card" style="margin-top:8px"><h4>Add current selection</h4><div class="stage20-list">${selectedCandidates().length?selectedCandidates().map(x=>`<div class="stage20-item"><span class="stage20-badge">${x.type}</span><b>${esc20(x.label)}</b><div class="stage20-row"><button class="primary" data-s20add="${esc20(x.type)}|${esc20(x.id)}|${esc20(x.label)}">Add to collection</button></div></div>`).join(''):'<div class="stage20-note">No A5 task, finding or opportunity is currently selected.</div>'}</div></div><div class="stage20-row" style="margin-top:8px"><button id="s20ExportCollectionMd">Markdown</button><button id="s20ExportCollectionJson">JSON</button><button id="s20ExportCollectionCsv">CSV</button></div>`:''}</div>`}
function validationValues(){return Object.values(S.client?.workspace?.findingValidations||{})}
function findings20(){return arr(S.transform?.findings)}
function opps20(){try{return opportunities?.()||[]}catch(e){return Object.values(S.client?.workspace?.opportunities||{})}}
function summary(){ensure();const fs=findings20(),vs=validationValues(),os=opps20(),futures=Object.values(S.client.workspace.futureStates||{}),high=fs.filter(f=>String(f.severity||'').toUpperCase()==='HIGH').length,validated=vs.filter(v=>v.status==='VALIDATED_ISSUE').length,measured=os.filter(o=>o.status==='MEASURED').length,implemented=os.filter(o=>o.status==='IMPLEMENTED').length,pilot=os.filter(o=>o.status==='PILOT').length,prioritized=os.filter(o=>o.status==='PRIORITIZED').length;const byCat={};fs.forEach(f=>byCat[f.category]=(byCat[f.category]||0)+1);const topCat=Object.entries(byCat).sort((a,b)=>b[1]-a[1])[0]||['—',0];const byTerr={};fs.forEach(f=>{const p=S.module?.processes?.find(x=>x.id===f.processId);const k=p?.page0DomainId||p?.territoryId||p?.a3ParentId||'Unmapped';byTerr[k]=(byTerr[k]||0)+1});const topTerr=Object.entries(byTerr).sort((a,b)=>b[1]-a[1])[0]||['—',0];return {findings:fs.length,high,validated,opportunities:os.length,prioritized,pilot,implemented,measured,futureStates:futures.length,collections:collections().length,topCat,topTerr,module:S.module?.module?.name||S.activeModule||'Active module',workspace:S.client?.workspace?.name||'Client Workspace'} }
function executiveMarkdown(){const s=summary();return `# Executive Transformation Summary\n\n- Workspace: ${s.workspace}\n- Atlas module: ${s.module}\n- Generated: ${now()}\n\n> This summary distinguishes Atlas-derived diagnostic signals from client-validated issues and consultant-authored opportunities. It does not infer ROI, savings or business impact not supported by evidence.\n\n## Portfolio at a glance\n- Diagnostic signals: ${s.findings}\n- High-severity diagnostic signals: ${s.high}\n- Client-validated issues: ${s.validated}\n- Opportunity work products: ${s.opportunities}\n- Prioritized: ${s.prioritized}\n- In pilot: ${s.pilot}\n- Implemented: ${s.implemented}\n- Measured: ${s.measured}\n- TO-BE proposals: ${s.futureStates}\n- Investigation collections: ${s.collections}\n\n## Concentration\n- Largest diagnostic category: ${s.topCat[0]} (${s.topCat[1]})\n- Largest current territory/group concentration: ${s.topTerr[0]} (${s.topTerr[1]})\n\n## Executive interpretation\n${s.validated?`${s.validated} diagnostic signal(s) have been explicitly validated against client evidence. Only those validated issues are eligible to support active transformation opportunities.`:'No diagnostic signal has yet been validated as a client issue; the current transformation view remains hypothesis-led.'}\n${s.opportunities?`${s.opportunities} opportunity work product(s) exist. ${s.prioritized} are prioritized; ${s.pilot+s.implemented+s.measured} have moved beyond solution design.`:'No opportunity work products exist yet.'}\n${s.measured?`${s.measured} opportunity work product(s) are marked Measured. Measured-outcome text remains consultant/client evidence and is not treated as Atlas truth.`:'No opportunity is yet marked Measured.'}\n\n## Governance\n- Difference from Atlas is not automatically a problem.\n- Diagnostic signal is not automatically a validated risk.\n- Opportunity is not source-native Atlas knowledge.\n- TO-BE content remains proposed until client/consultant governance advances it.\n`}
function renderExecutive(){const s=summary();return `<div class="stage20-summary-grid">${[[s.findings,'DIAGNOSTIC SIGNALS'],[s.validated,'VALIDATED ISSUES'],[s.opportunities,'OPPORTUNITIES'],[s.prioritized,'PRIORITIZED'],[s.pilot+s.implemented+s.measured,'DELIVERY / MEASURE'],[s.collections,'COLLECTIONS']].map(([n,l])=>`<div class="stage20-stat"><b>${n}</b><span>${l}</span></div>`).join('')}</div><div class="stage20-card stage20-exec"><span class="stage20-badge">EXECUTIVE SUMMARY</span><h3>${esc20(s.module)}</h3><p>Current transformation work for <b>${esc20(s.workspace)}</b>.</p><ul><li>${s.validated?`${s.validated} issue(s) are client-validated.`:'No issue is yet client-validated; diagnostics remain hypotheses.'}</li><li>${s.opportunities?`${s.opportunities} opportunity work product(s); ${s.prioritized} prioritized.`:'No opportunity work products yet.'}</li><li>${s.pilot} in Pilot, ${s.implemented} Implemented, ${s.measured} Measured.</li><li>Largest diagnostic category: ${esc20(s.topCat[0])} (${s.topCat[1]}).</li><li>Largest current concentration: ${esc20(s.topTerr[0])} (${s.topTerr[1]}).</li></ul><div class="stage20-note">No financial benefit, ROI or outcome is manufactured by this summary. It compresses existing governed work-state only.</div><div class="stage20-row" style="margin-top:8px"><button class="primary" id="s20ExportExecutive">Export executive Markdown</button></div></div>`}
function packObject(scope='full'){const s=summary(),w=S.client.workspace;return {schemaVersion:'enterprise-transformation-pack-v1.0',generatedAt:now(),scope,domainPackId:S.activeDomainPackId||S.module?.domainPackId||'supply-chain',module:{id:S.module?.module?.id||S.activeModule,name:S.module?.module?.name,version:S.module?.module?.version,depth:S.module?.module?.depth},governancePin:window.AtlasVersionManager16?.capture?.()||null,workspace:{name:w.name,schemaVersion:w.schemaVersion},executive:s,findings:findings20(),validations:w.findingValidations||{},opportunities:w.opportunities||{},futureStates:w.futureStates||{},collections:w.investigationCollections||{},evidenceIndex:Object.values(w.evidence||{}).map(e=>({id:e.id,type:e.type,title:e.title,processId:e.processId||null,createdAt:e.createdAt||e.updatedAt||null}))}}
function collectionMarkdown(c){let md=`# Investigation Collection — ${c.name}\n\n- Collection ID: ${c.id}\n- Workspace: ${S.client.workspace.name}\n- Updated: ${c.updatedAt}\n\n> A collection is a bookmark set over existing Atlas/client work objects. It does not create new Atlas knowledge.\n\n`;for(const x of c.items)md+=`- **${x.type}** · ${x.id} — ${x.label}\n`;return md}
function csvEscape(v){v=String(v??'');return /[",\n]/.test(v)?`"${v.replace(/"/g,'""')}"`:v}
function collectionCsv(c){return ['type,id,label,added_at',...c.items.map(x=>[x.type,x.id,x.label,x.addedAt].map(csvEscape).join(','))].join('\n')}
function packCsv(){const rows=[['record_type','id','status','process_id','title','category','priority','owner','note']];findings20().forEach(f=>rows.push(['finding',f.id,validationFor?.(f.id)?.status||'NEEDS_VALIDATION',f.processId,f.processLabel||f.label,f.category||'',f.severity||'','',f.rationale||'']));opps20().forEach(o=>rows.push(['opportunity',o.id,o.status,o.processId,o.title,o.interventionPattern||'',o.priority||'',o.owner||'',o.rationale||'']));return rows.map(r=>r.map(csvEscape).join(',')).join('\n')}
function dl(name,data,type='text/plain;charset=utf-8'){const b=new Blob([data],{type}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},0)}
async function serverExport(format){const pack=packObject('full');try{const r=await fetch(`api/transformation-export?format=${encodeURIComponent(format)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pack})});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).error||`HTTP ${r.status}`);const blob=await r.blob(),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`atlas-transformation-pack.${format}`;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},0)}catch(e){stage11Toast?.(`${format.toUpperCase()} export requires deployed Stage-20 API`);return false}return true}
function printPack(){const md=executiveMarkdown()+'\n\n'+(typeof transformationMarkdown==='function'?transformationMarkdown():'');const w=window.open('','_blank');if(!w)return;w.document.write(`<!doctype html><meta charset="utf-8"><title>Transformation Pack</title><style>body{font:14px Arial;max-width:900px;margin:36px auto;line-height:1.5;color:#172f38}pre{white-space:pre-wrap;font:13px Arial}</style><pre>${esc20(md)}</pre><script>setTimeout(()=>print(),250)<\/script>`);w.document.close()}
function renderExport(){return `<div class="stage20-card"><h4>Transformation Pack</h4><p>Exports the currently governed work-state. Markdown/JSON/CSV work locally. XLSX/PDF/PPTX use the production export API.</p><div class="stage20-note">Exported packs preserve module/version context and epistemic separation. They do not promote hypotheses into Atlas facts.</div></div><div class="stage20-export-grid"><button class="stage20-export" id="s20PackMd"><b>Markdown</b><small>Human + machine readable assessment</small></button><button class="stage20-export" id="s20PackJson"><b>JSON</b><small>Structured downstream tooling</small></button><button class="stage20-export" id="s20PackCsv"><b>CSV / Excel</b><small>Flat register for analysis</small></button><button class="stage20-export" id="s20PackXlsx"><b>Excel .xlsx</b><small>Production Office workbook</small></button><button class="stage20-export" id="s20PackPdf"><b>PDF</b><small>Portable executive pack</small></button><button class="stage20-export" id="s20PackPptx"><b>PowerPoint .pptx</b><small>Boardroom-ready editable text outline</small></button><button class="stage20-export" id="s20PackPrint"><b>Print / Save PDF</b><small>Browser-native fallback</small></button></div>`}
const presentationSteps=()=>{const s=summary();return [
 {t:'1 · Context',x:`${s.module} · ${s.workspace}. The underlying Atlas reference remains separate from client evidence and transformation hypotheses.`},
 {t:'2 · Execution',x:'Use the persistent canvas to orient the audience to the active operating context. Semantic depth remains available without exposing every A5 task at once.'},
 {t:'3 · Critical friction',x:`${s.findings} diagnostic signals are currently available; ${s.validated} have been explicitly validated as client issues.`},
 {t:'4 · Opportunity portfolio',x:`${s.opportunities} opportunity work products exist; ${s.prioritized} are prioritized. Intervention patterns remain consultant hypotheses.`},
 {t:'5 · Future state & delivery',x:`${s.futureStates} TO-BE proposal(s); ${s.pilot} Pilot, ${s.implemented} Implemented, ${s.measured} Measured.`},
 {t:'6 · Executive close',x:`Largest diagnostic category: ${s.topCat[0]} (${s.topCat[1]}). No unsupported ROI or benefit is inferred.`}
]}
function renderPresentation(){return `<div class="stage20-card"><h4>Presentation Mode</h4><p>Turns the working canvas into a clean narrative surface without creating a second presentation model.</p><div class="stage20-note">Presentation Mode hides secondary controls and development metadata. The underlying canvas and evidence remain unchanged.</div><div class="stage20-row" style="margin-top:8px"><button class="primary" id="s20StartPresent">Start presentation</button></div></div><div class="stage20-list">${presentationSteps().map((x,i)=>`<div class="stage20-item"><span class="stage20-badge">STEP ${i+1}</span><b>${esc20(x.t.replace(/^\d · /,''))}</b><small>${esc20(x.x)}</small></div>`).join('')}</div>`}
function render(){if(!ensure())return;document.querySelectorAll('[data-s20tab]').forEach(x=>x.classList.toggle('active',x.dataset.s20tab===R.tab));const b=document.getElementById('stage20Body');if(!b)return;b.innerHTML=R.tab==='collections'?renderCollections():R.tab==='executive'?renderExecutive():R.tab==='export'?renderExport():renderPresentation();wire()}
function wire(){
 document.getElementById('s20CreateCollection')?.addEventListener('click',createCollection);document.getElementById('s20CollectionSelect')?.addEventListener('change',e=>{R.selectedCollection=e.target.value;render()});document.getElementById('s20ArchiveCollection')?.addEventListener('click',()=>archiveCollection(R.selectedCollection));
 document.querySelectorAll('[data-s20remove]').forEach(x=>x.onclick=()=>removeItem(x.dataset.s20remove));document.querySelectorAll('[data-s20add]').forEach(x=>x.onclick=()=>{const [t,id,...l]=x.dataset.s20add.split('|');addItem(t,id,l.join('|'))});const c=collection(R.selectedCollection);document.getElementById('s20ExportCollectionMd')?.addEventListener('click',()=>c&&dl('atlas-investigation-collection.md',collectionMarkdown(c),'text/markdown;charset=utf-8'));document.getElementById('s20ExportCollectionJson')?.addEventListener('click',()=>c&&dl('atlas-investigation-collection.json',JSON.stringify(c,null,2),'application/json'));document.getElementById('s20ExportCollectionCsv')?.addEventListener('click',()=>c&&dl('atlas-investigation-collection.csv',collectionCsv(c),'text/csv;charset=utf-8'));
 document.getElementById('s20ExportExecutive')?.addEventListener('click',()=>dl('atlas-executive-summary.md',executiveMarkdown(),'text/markdown;charset=utf-8'));
 document.getElementById('s20PackMd')?.addEventListener('click',()=>dl('atlas-transformation-pack.md',executiveMarkdown()+'\n\n'+(typeof transformationMarkdown==='function'?transformationMarkdown():''),'text/markdown;charset=utf-8'));document.getElementById('s20PackJson')?.addEventListener('click',()=>dl('atlas-transformation-pack.json',JSON.stringify(packObject(),null,2),'application/json'));document.getElementById('s20PackCsv')?.addEventListener('click',()=>dl('atlas-transformation-pack.csv',packCsv(),'text/csv;charset=utf-8'));document.getElementById('s20PackXlsx')?.addEventListener('click',()=>serverExport('xlsx'));document.getElementById('s20PackPdf')?.addEventListener('click',()=>serverExport('pdf'));document.getElementById('s20PackPptx')?.addEventListener('click',()=>serverExport('pptx'));document.getElementById('s20PackPrint')?.addEventListener('click',printPack);document.getElementById('s20StartPresent')?.addEventListener('click',startPresentation)
}
function startPresentation(){close();R.presentation=true;R.presentationStep=0;document.body.classList.add('stage20-present');document.getElementById('stage20Presenter')?.classList.add('open');updatePresentation()}
function exitPresentation(){R.presentation=false;document.body.classList.remove('stage20-present');document.getElementById('stage20Presenter')?.classList.remove('open')}
function stepPresentation(delta){const n=presentationSteps().length;R.presentationStep=Math.max(0,Math.min(n-1,R.presentationStep+delta));updatePresentation()}
function updatePresentation(){const xs=presentationSteps(),x=xs[R.presentationStep];document.getElementById('s20PresentTitle').textContent=x.t;document.getElementById('s20PresentText').textContent=x.x;document.getElementById('s20PresentSteps').textContent=`${R.presentationStep+1} / ${xs.length}`}
function appendLifecycle(){if(!S.transform?.enabled||S.client?.submode==='client'||S.transform?.showContract)return;const f=S.transform?.findings?.find(x=>x.id===S.transform.selectedFinding);if(!f)return;const o=opportunityForFinding?.(f.id);if(!o)return;const host=document.querySelector('#inspectorBody .opportunity-panel');if(!host||host.querySelector('.stage20-lifecycle'))return;const late=['PILOT','IMPLEMENTED','MEASURED'].includes(o.status);host.insertAdjacentHTML('beforeend',`<div class="stage20-lifecycle"><h3>Delivery & measurement lifecycle</h3><div class="stage20-note">Pilot / Implemented / Measured are client transformation work-state, not Atlas knowledge. Advancing these stages requires an owner and delivery evidence note.</div><label>Delivery / validation note<textarea id="oppLifecycleNote" placeholder="Pilot scope, implementation evidence, validation note…">${esc20(o.lifecycleNote||'')}</textarea></label><label>Measured outcome${o.status==='MEASURED'?' · required':''}<textarea id="oppMeasuredOutcome" placeholder="Observed outcome and measurement basis; do not enter unsupported estimates.">${esc20(o.measuredOutcome||'')}</textarea></label>${late?`<div class="stage20-measured"><b>${esc20(LATE[o.status]||o.status)}</b> · ${esc20(o.lifecycleUpdatedAt||o.updatedAt||'')}</div>`:''}</div>`)}
function patchLifecycle(){if(typeof OPPORTUNITY_STATUS==='object')Object.assign(OPPORTUNITY_STATUS,LATE);const f0=window.saveOpportunity||((typeof saveOpportunity==='function')?saveOpportunity:null);if(f0&&!window.__stage20SavePatched){window.__stage20SavePatched=true;window.saveOpportunity=function(id){const o=opportunityById?.(id);if(!o)return;const requested=document.getElementById('oppStatus')?.value||o.status,owner=(document.getElementById('oppOwner')?.value||o.owner||'').trim(),note=(document.getElementById('oppLifecycleNote')?.value||o.lifecycleNote||'').trim(),measured=(document.getElementById('oppMeasuredOutcome')?.value||o.measuredOutcome||'').trim();if(['PILOT','IMPLEMENTED','MEASURED'].includes(requested)&&(!owner||!note)){S.opportunity.message='Pilot / Implemented / Measured requires an owner and delivery/validation note.';renderInspector?.();return}if(requested==='MEASURED'&&!measured){S.opportunity.message='Measured requires an observed outcome and measurement basis. Unsupported estimates are not accepted.';renderInspector?.();return}const r=f0.apply(this,arguments);const n=opportunityById?.(id);if(n){n.lifecycleNote=note;n.measuredOutcome=measured;n.lifecycleUpdatedAt=now();persistClientWorkspace?.();}return r};try{saveOpportunity=window.saveOpportunity}catch(e){}
 }
 const ri=window.renderInspector||((typeof renderInspector==='function')?renderInspector:null);if(ri&&!window.__stage20InspectorPatched){window.__stage20InspectorPatched=true;window.renderInspector=function(){const r=ri.apply(this,arguments);setTimeout(appendLifecycle,0);return r};try{renderInspector=window.renderInspector}catch(e){}}
}

function installLifecycleGate(){if(window.__stage20LifecycleGate)return;window.__stage20LifecycleGate=true;document.addEventListener('click',e=>{const b=e.target.closest?.('#saveOpportunity');if(!b)return;const id=S.opportunity?.selectedId||opportunityForFinding?.(S.transform?.selectedFinding)?.id;if(!id)return;const o=opportunityById?.(id);if(!o)return;const requested=document.getElementById('oppStatus')?.value||o.status,owner=(document.getElementById('oppOwner')?.value||o.owner||'').trim(),note=(document.getElementById('oppLifecycleNote')?.value||o.lifecycleNote||'').trim(),measured=(document.getElementById('oppMeasuredOutcome')?.value||o.measuredOutcome||'').trim();if(['PILOT','IMPLEMENTED','MEASURED'].includes(requested)&&(!owner||!note)){e.preventDefault();e.stopImmediatePropagation();S.opportunity.message='Pilot / Implemented / Measured requires an owner and delivery/validation note.';renderInspector?.();return}if(requested==='MEASURED'&&!measured){e.preventDefault();e.stopImmediatePropagation();S.opportunity.message='Measured requires an observed outcome and measurement basis. Unsupported estimates are not accepted.';renderInspector?.();return}setTimeout(()=>{const n=opportunityById?.(id);if(!n)return;n.status=requested;n.owner=owner;n.lifecycleNote=note;n.measuredOutcome=measured;n.lifecycleUpdatedAt=now();n.updatedAt=now();persistClientWorkspace?.();S.opportunity.message='Opportunity lifecycle saved as client transformation work-state. Atlas knowledge is unchanged.';renderOpportunityDrawer?.();renderInspector?.();renderTransformUI?.()},30)},true)}
function extendFilters(){const f=document.getElementById('opportunityFilter');if(f&&!f.querySelector('[data-ofilter="PILOT"]'))for(const [k,v] of Object.entries(LATE)){const b=document.createElement('button');b.dataset.ofilter=k;b.textContent=v;b.onclick=()=>{S.opportunity.filter=k;renderOpportunityDrawer?.()};f.appendChild(b)}}
function patchTransform(){const rt=window.renderTransformUI||((typeof renderTransformUI==='function')?renderTransformUI:null);if(rt&&!window.__stage20TransformPatched){window.__stage20TransformPatched=true;window.renderTransformUI=function(){const r=rt.apply(this,arguments);const on=!!S.transform?.enabled;const b=document.getElementById('stage20DeliverBtn'),m=document.getElementById('stage20MobileBtn');if(b)b.style.display=on?'inline-flex':'none';if(m)m.style.display=on?'inline-flex':'none';if(!on)close();return r};try{renderTransformUI=window.renderTransformUI}catch(e){}}}
function patchCommands(){const run=window.AtlasCommandBus?.execute;if(!run||window.__stage20CommandPatched)return;window.__stage20CommandPatched=true;window.AtlasCommandBus.execute=function(q){const l=String(q||'').toLowerCase();if(/executive summary/.test(l)){if(!S.transform?.enabled)enterTransform?.();R.tab='executive';open();return true}if(/investigation collection|collection/.test(l)){if(!S.transform?.enabled)enterTransform?.();R.tab='collections';open();return true}if(/presentation mode|present transformation/.test(l)){if(!S.transform?.enabled)enterTransform?.();startPresentation();return true}if(/export transformation pack|deliverable pack/.test(l)){if(!S.transform?.enabled)enterTransform?.();R.tab='export';open();return true}return run.apply(this,arguments)} }
function boot(){if(typeof S==='undefined'||!document.body||!S.module){setTimeout(boot,80);return}window.S=S;ensure();inject();patchLifecycle();installLifecycleGate();extendFilters();patchTransform();patchCommands();const title=document.querySelector('.brand small');if(title)title.textContent='Enterprise Operations Platform · Supply Chain · Stage 20';document.title='Supply Chain Atlas · Stage 20 Product Completion';setTimeout(()=>{const t=document.querySelector('.brand small');if(t)t.textContent='Enterprise Operations Platform · Supply Chain · Stage 20';document.title='Supply Chain Atlas · Stage 20 Product Completion'},900);renderTransformUI?.();window.AtlasStage20={runtime:R,open,close,summary,executiveMarkdown,packObject,startPresentation,exitPresentation,collections,createCollection,lifecycleStatuses:()=>({...LATE})};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,220));else setTimeout(boot,220);
document.addEventListener('keydown',e=>{if(!R.presentation)return;if(e.key==='ArrowRight'||e.key==='PageDown'){e.preventDefault();stepPresentation(1)}if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();stepPresentation(-1)}if(e.key==='Escape'){e.preventDefault();exitPresentation()}},true);
})();
