'use client';
import {useMemo,useState} from 'react';

const S={
  panel:{border:'1px solid #d9e3e8',borderRadius:12,background:'#fff',boxShadow:'0 1px 2px rgba(16,42,67,.04)'},
  small:{fontSize:11,color:'#526875',lineHeight:1.45},
  btn:{border:'1px solid #bdccd4',background:'#fff',borderRadius:6,padding:'7px 10px',fontSize:12,cursor:'pointer'},
  tag:{display:'inline-flex',alignItems:'center',gap:4,padding:'3px 7px',border:'1px solid #d6e2e7',borderRadius:999,fontSize:10,background:'#f8fbfc'}
};
function text(v){return v||'NOT_MODELED'}
function Item({label,value,mono=false}){return <div style={{display:'grid',gridTemplateColumns:'130px minmax(0,1fr)',gap:8,padding:'6px 0',borderBottom:'1px solid #edf2f4',fontSize:12}}><b style={{color:'#45606d'}}>{label}</b><span style={{whiteSpace:'pre-wrap',fontFamily:mono?'ui-monospace,monospace':'inherit'}}>{Array.isArray(value)?(value.join(' · ')||'NOT_MODELED'):text(value)}</span></div>}
function Status({children}){return <span style={S.tag}>{children}</span>}
function FlowRow({label,enabled,playing,detail}){return <div style={{display:'grid',gridTemplateColumns:'92px minmax(0,1fr)',gap:8,alignItems:'center',opacity:enabled?1:.32}}><b style={{fontSize:11}}>{label}</b><div style={{position:'relative',height:28,border:'1px solid #d8e4e8',borderRadius:999,background:'#f8fbfc',overflow:'hidden'}}><div style={{position:'absolute',left:8,right:8,top:13,borderTop:'1px dashed #9fb4be'}}/><span data-atlas-moving-token="true" aria-hidden="true" style={{position:'absolute',top:5,left:8,animation:playing&&enabled?'atlasFlow 1.1s linear infinite':'none',fontSize:14}}>●</span><span style={{position:'absolute',left:34,top:5,right:8,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis',fontSize:10,color:'#536b78'}}>{detail}</span></div></div>}
function SourceDrawer({step}){return <details style={{marginTop:8,borderTop:'1px solid #edf2f4',paddingTop:8}}><summary style={{cursor:'pointer',fontSize:12,fontWeight:700}}>Source & provenance</summary><div style={{paddingTop:6}}><Item label="Provenance" value={step?.provenance?.provenance}/><Item label="Source relationship" value={step?.provenance?.sourceRelationship}/><Item label="Claim boundary" value={step?.provenance?.claimBoundary}/><Item label="Supporting sources" value={(step?.provenance?.sources||[]).map(s=>`${s.id} — ${s.title}`)}/></div></details>}
function StepInspector({step}){if(!step)return <div style={S.small}>Select a step.</div>;return <div><div style={{display:'flex',justifyContent:'space-between',gap:8,alignItems:'flex-start'}}><div><div style={{fontSize:10,fontWeight:800,color:'#0785a0',letterSpacing:'.08em'}}>{step.id} · {step.phase?.toUpperCase()} · {step.pathType}</div><h3 style={{margin:'4px 0 2px',fontSize:17}}>{step.label}</h3></div><Status>{step.applicability?.state}</Status></div><Item label="Before" value={step.state?.before}/><Item label="Trigger" value={step.trigger}/><Item label="Event" value={step.event}/><Item label="Decision" value={step.decision}/><Item label="Rule" value={step.rule}/><Item label="Control" value={step.control}/><Item label="Action" value={step.action}/><Item label="Evidence" value={step.evidence}/><Item label="After" value={step.state?.after}/><Item label="Outcome" value={step.outcome}/><SourceDrawer step={step}/></div>}
function HandoffInspector({handoff}){if(!handoff)return <div style={S.small}>Select a handoff between two governed processes.</div>;return <div><div style={{display:'flex',alignItems:'center',gap:6,flexWrap:'wrap'}}><Status>{handoff.edge.type}</Status><b>{handoff.from.id} → {handoff.to.id}</b></div><p style={{...S.small,margin:'8px 0'}}>{handoff.edge.semantic}</p><Item label="From actor" value={handoff.from.actor}/><Item label="To actor" value={handoff.to.actor}/><Item label="Producer systems" value={handoff.from.producerSystems}/><Item label="Consumer systems" value={handoff.to.consumerSystems}/><Item label="Shared objects" value={handoff.information?.sharedObjects}/><Item label="Shared identifiers" value={handoff.data?.sharedIdentifiers}/><Item label="Field-level status" value={handoff.data?.fieldLevelStatus}/><Item label="State handoff" value={`${text(handoff.from.stateAfter)} → ${text(handoff.to.stateBefore)}`}/><Item label="Evidence" value={handoff.evidence?.generated}/><Item label="Control" value={handoff.controls?.control}/><Item label="Financial context" value={`${text(handoff.financial?.from)} → ${text(handoff.financial?.to)}`}/>{(handoff.risks||[]).length>0&&<details style={{marginTop:8}}><summary style={{cursor:'pointer',fontSize:12,fontWeight:700}}>Risk signals at this handoff ({handoff.risks.length})</summary><div style={{paddingTop:6}}>{handoff.risks.slice(0,8).map(r=><div key={r.id} style={{padding:'6px 0',borderBottom:'1px solid #edf2f4',fontSize:11}}><Status>{r.status}</Status><b style={{display:'block',marginTop:3}}>{r.title}</b><span style={S.small}>Basis: {r.basis}</span></div>)}</div></details>}<details style={{marginTop:8}}><summary style={{cursor:'pointer',fontSize:12,fontWeight:700}}>Handoff provenance</summary><div style={{paddingTop:6}}><Item label="From provenance" value={handoff.provenance?.from?.provenance}/><Item label="From sources" value={(handoff.provenance?.from?.sources||[]).map(x=>`${x.id} — ${x.title}`)}/><Item label="To provenance" value={handoff.provenance?.to?.provenance}/><Item label="To sources" value={(handoff.provenance?.to?.sources||[]).map(x=>`${x.id} — ${x.title}`)}/><Item label="Client status" value={`${handoff.client?.fromStatus} → ${handoff.client?.toStatus}`}/><div style={{...S.small,paddingTop:7}}>{handoff.client?.guardrail}</div></div></details></div>}

export default function SimulationStudio({simulation,loading,error,activeIndex,setActiveIndex,playing,setPlaying,speed,setSpeed,view,setView,flowLayers,setFlowLayers,selectedHandoffId,setSelectedHandoffId,twinLayer,setTwinLayer,branchPreview,setBranchPreview,onRefresh,onBack,onFocusProcess,onEvent=()=>{}}){
  const [swimlane,setSwimlane]=useState('Process');
  const steps=simulation?.standardJourney||[],handoffs=simulation?.standardHandoffs||[];
  const step=steps[activeIndex]||steps[0]||null,next=steps[activeIndex+1]||null;
  const defaultHandoff=handoffs[Math.min(activeIndex,handoffs.length-1)]||null;
  const handoff=(simulation?.allHandoffs||[]).find(h=>h.edge.id===selectedHandoffId)||defaultHandoff;
  const branchOptions=step?simulation?.branches?.[step.id]||[]:[];
  const exception=step?simulation?.exceptions?.[step.id]:null;
  const compareRows=useMemo(()=>simulation?.compare||[],[simulation]);
  const views=['Journey','Handoffs','Data','Risks & Controls','Systems & Actors','Compare'];
  const laneValue=s=>swimlane==='Actor'?(s.actor?.performer||'Actor not modeled'):swimlane==='System'?(s.systems?.authoritySystem||'System not modeled'):swimlane==='Node'?(()=>{const n=s.applicability?.dimensionResults?.find(x=>x.dimension==='node');return n?`Applicable node context: ${n.value}`:'Node context unresolved';})():'Standard process spine';
  const laneGroups=[...new Set(steps.map(laneValue))];
  if(loading)return <div style={{padding:24}}>Building deterministic simulation from the governed Road LTL graph…</div>;
  if(error)return <div style={{padding:24}}><b>Simulation failed safely.</b><div>{error}</div><button style={S.btn} onClick={onRefresh}>Retry</button></div>;
  if(!simulation)return <div style={{padding:24}}><button style={S.btn} onClick={onRefresh}>Load Simulation Studio</button></div>;
  return <div style={{height:'100%',display:'flex',flexDirection:'column',background:'#f3f7f8',minWidth:0}}>
    <style>{`@keyframes atlasFlow{0%{left:8px}100%{left:calc(100% - 28px)}}@media (prefers-reduced-motion: reduce){[data-atlas-moving-token]{transition:none!important;animation:none!important}}`}</style>
    <div style={{padding:'10px 14px',borderBottom:'1px solid #d9e3e8',background:'#fff',display:'flex',justifyContent:'space-between',gap:10,alignItems:'center',flexWrap:'wrap'}}>
      <div><b style={{fontSize:14}}>Simulation Studio</b><div style={S.small}>Reference Execution Digital Twin · deterministic Atlas graph · no LLM path selection</div></div>
      <div style={{display:'flex',gap:5,flexWrap:'wrap'}}><button style={S.btn} onClick={onRefresh}>Refresh</button><button style={S.btn} onClick={onBack}>Back to Atlas</button></div>
    </div>
    <div style={{padding:'8px 12px',borderBottom:'1px solid #d9e3e8',background:'#fbfdfe',display:'flex',gap:5,overflowX:'auto'}}>{views.map(v=><button key={v} style={{...S.btn,whiteSpace:'nowrap',background:view===v?'#0b7890':'#fff',color:view===v?'#fff':'#234'}} onClick={()=>{setView(v);onEvent('SIMULATION_VIEW',{view:v})}}>{v}</button>)}</div>
    <div style={{padding:'8px 12px',borderBottom:'1px solid #d9e3e8',background:'#fff',display:'flex',gap:7,alignItems:'center',flexWrap:'wrap'}}>
      <button style={S.btn} onClick={()=>{setActiveIndex(i=>Math.max(0,i-1));onEvent('SIMULATION_STEP',{direction:'PREVIOUS'})}}>◀ Previous</button><button style={{...S.btn,fontWeight:800}} onClick={()=>{setPlaying(x=>{const n=!x;onEvent(n?'SIMULATION_STARTED':'SIMULATION_PAUSED',{step:step?.id||''});return n})}}>{playing?'⏸ Pause':'▶ Play'}</button><button style={S.btn} onClick={()=>{setActiveIndex(i=>Math.min(steps.length-1,i+1));onEvent('SIMULATION_STEP',{direction:'NEXT'})}}>Next ▶</button><button style={S.btn} onClick={()=>{setPlaying(false);setActiveIndex(0);setBranchPreview(null)}}>Reset</button>
      <span style={S.tag}>Step {Math.min(activeIndex+1,steps.length)} / {steps.length}</span><select value={speed} onChange={e=>setSpeed(Number(e.target.value))} style={{...S.btn,padding:'6px'}}><option value={1800}>Slow</option><option value={1000}>Normal</option><option value={550}>Fast</option></select>
      <select value={swimlane} onChange={e=>setSwimlane(e.target.value)} style={{...S.btn,padding:'6px'}}>{['Process','Actor','System','Node'].map(x=><option key={x}>{x}</option>)}</select>
      <div style={{display:'flex',gap:4,flexWrap:'wrap'}}>{Object.entries(flowLayers).map(([k,on])=><button key={k} aria-pressed={on} style={{...S.btn,padding:'5px 7px',background:on?'#eaf7fa':'#fff'}} onClick={()=>setFlowLayers(x=>{const n=!x[k];onEvent('FLOW_LAYER_TOGGLED',{layer:k,enabled:n});return {...x,[k]:n}})}>{on?'✓ ':''}{k[0].toUpperCase()+k.slice(1)}</button>)}</div>
    </div>
    <div style={{flex:1,overflow:'auto',padding:12}}>
      {view==='Journey'&&<div style={{display:'grid',gap:10}}>
        <div style={{...S.panel,padding:10,overflowX:'auto'}}>{swimlane==='Process'?<div style={{display:'flex',alignItems:'stretch',minWidth:Math.max(900,steps.length*150),gap:5}}>{steps.map((s,i)=><div key={s.id} style={{display:'contents'}}><button onClick={()=>{setActiveIndex(i);setBranchPreview(null);onFocusProcess?.(s.id)}} style={{width:135,minHeight:78,textAlign:'left',padding:8,border:i===activeIndex?'2px solid #0785a0':'1px solid #cfdbdf',borderRadius:8,background:i===activeIndex?'#edfafd':'#fff',cursor:'pointer',opacity:['INCOMPATIBLE','NOT_DIRECT'].includes(s.applicability?.state)?.55:1}}><b style={{fontSize:11}}>{s.id}</b><div style={{fontSize:11,lineHeight:1.25,marginTop:4}}>{s.label}</div><small>{s.applicability?.state}</small></button>{i<steps.length-1&&<div style={{alignSelf:'center',fontSize:18,color:'#728a95'}}>→</div>}</div>)}</div>:<div style={{minWidth:Math.max(1100,steps.length*105)}}>{laneGroups.map(lane=><div key={lane} style={{display:'grid',gridTemplateColumns:`170px repeat(${steps.length},minmax(92px,1fr))`,gap:3,alignItems:'stretch',borderTop:'1px solid #edf2f4',padding:'5px 0'}}><div style={{fontSize:10,fontWeight:800,padding:6,position:'sticky',left:0,background:'#fff',zIndex:1}}>{lane}</div>{steps.map((s,i)=>laneValue(s)===lane?<button key={s.id} onClick={()=>{setActiveIndex(i);setBranchPreview(null)}} style={{minHeight:52,textAlign:'left',padding:5,border:i===activeIndex?'2px solid #0785a0':'1px solid #d7e2e6',borderRadius:6,background:i===activeIndex?'#edfafd':'#fff',fontSize:10}}><b>{s.id}</b><br/>{s.label.slice(0,42)}{s.label.length>42?'…':''}</button>:<div key={s.id} style={{borderBottom:'1px dashed #e3eaed'}}/> )}</div>)}</div>}</div>
        <div style={{...S.panel,padding:10}}><div style={{display:'flex',justifyContent:'space-between',gap:8,alignItems:'center',marginBottom:8}}><b>Live execution threads</b><span style={S.small}>{swimlane} view · current → next</span></div>{swimlane==='Node'&&<div style={{...S.small,marginBottom:7,padding:'6px 8px',border:'1px solid #e2eaed',borderRadius:6}}>Node lanes show the selected node <b>applicability context</b> for each process. They do not imply a live shipment location unless actual telemetry is connected.</div>}<div style={{display:'grid',gap:6}}><FlowRow label="Physical" enabled={flowLayers.physical} playing={playing} detail={`${step?.actor?.custody||'NOT_MODELED'} → ${next?.actor?.custody||'end'}`}/><FlowRow label="Information" enabled={flowLayers.information} playing={playing} detail={`${(step?.data?.outputs||[]).join(' · ')||'NOT_MODELED'} → ${(next?.data?.inputs||[]).join(' · ')||'end'}`}/><FlowRow label="Financial" enabled={flowLayers.financial} playing={playing} detail={`${step?.financial||'NOT_MODELED'} → ${next?.financial||'end'}`}/><FlowRow label="Controls" enabled={flowLayers.controls} playing={playing} detail={step?.control||'NOT_MODELED'}/><FlowRow label="Evidence" enabled={flowLayers.evidence} playing={playing} detail={step?.evidence||'NOT_MODELED'}/></div></div>
        <div style={{display:'grid',gridTemplateColumns:'minmax(0,1.2fr) minmax(300px,.8fr)',gap:10}}><div style={{...S.panel,padding:12}}><StepInspector step={branchPreview?.step||step}/></div><div style={{display:'grid',gap:10,alignContent:'start'}}><div style={{...S.panel,padding:12}}><b>Governed branches from {step?.id}</b>{branchOptions.length===0?<p style={S.small}>No non-standard outgoing relationship at this step.</p>:branchOptions.map(b=><button key={b.id} style={{...S.btn,display:'block',width:'100%',textAlign:'left',marginTop:6}} onClick={()=>{const h=(simulation.allHandoffs||[]).find(x=>x.edge.id===b.id);setSelectedHandoffId(b.id);setBranchPreview({edge:b,step:simulation.processMap?.[b.to],handoff:h})}}><b>{b.type}</b> → {b.to}<br/><small>{b.semantic}</small></button>)}</div>
        {exception&&<div style={{...S.panel,padding:12}}><b>Exception simulation</b><p style={S.small}>Inject the explicit variance route. Recovery is not auto-selected when multiple governed re-entry points exist.</p><button style={S.btn} onClick={()=>{setBranchPreview({kind:'exception',step:exception.detection,exception});onEvent('EXCEPTION_SIMULATED',{from:step?.id||''})}}>Simulate exception</button>{branchPreview?.kind==='exception'&&<div style={{marginTop:8,fontSize:11}}><div>1. Detect: {exception.detection?.id} — {exception.detection?.label}</div><div>2. Escalate: {exception.recovery?.id} — {exception.recovery?.label}</div><div style={{marginTop:5}}><b>Choose governed recovery point:</b></div>{exception.recoveryOptions.map(r=><button key={r.id} style={{...S.btn,display:'block',width:'100%',textAlign:'left',marginTop:4}} onClick={()=>{const idx=steps.findIndex(x=>x.id===r.to);setBranchPreview({kind:'recovery',step:r.target,edge:r});if(idx>=0)setActiveIndex(idx)}}>{r.to} — {r.target?.label}</button>)}<div style={{...S.small,marginTop:5}}>{exception.guardrail}</div></div>}</div>}</div></div>
      </div>}
      {view==='Handoffs'&&<div style={{display:'grid',gridTemplateColumns:'minmax(260px,.65fr) minmax(0,1.35fr)',gap:10}}><div style={{...S.panel,padding:10,maxHeight:'calc(100vh - 250px)',overflow:'auto'}}><b>Governed handoffs</b><p style={S.small}>All 39 process-flow relationships remain distinct; they are not all treated as “next”.</p>{(simulation.allHandoffs||[]).map(h=><button key={h.edge.id} onClick={()=>{setSelectedHandoffId(h.edge.id);onEvent('HANDOFF_INSPECTED',{edgeId:h.edge.id,type:h.edge.type})}} style={{...S.btn,width:'100%',textAlign:'left',marginTop:4,background:h.edge.id===(handoff?.edge?.id)?'#edfafd':'#fff'}}><b>{h.edge.id} · {h.edge.type}</b><br/><small>{h.from.id} → {h.to.id}</small></button>)}</div><div style={{...S.panel,padding:12}}><HandoffInspector handoff={handoff}/></div></div>}
      {view==='Data'&&<div style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) minmax(300px,.8fr)',gap:10}}><div style={{...S.panel,padding:12}}><h3 style={{marginTop:0}}>Data Exchange Registry</h3><p style={S.small}>The simulator distinguishes explicit canonical objects and explicit model identifiers from unmodeled field-level payloads.</p><HandoffInspector handoff={handoff}/></div><div style={{...S.panel,padding:12}}><b>Lineage at current step</b><Item label="Identifiers" value={step?.data?.identifiers}/><Item label="Inputs" value={step?.data?.inputs}/><Item label="Outputs" value={step?.data?.outputs}/><Item label="Lineage" value={step?.data?.lineage}/><div style={{...S.small,marginTop:8}}>{step?.data?.fieldLevelGuardrail}</div></div></div>}
      {view==='Risks & Controls'&&<div style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) minmax(300px,.8fr)',gap:10}}><div style={{...S.panel,padding:12}}><h3 style={{marginTop:0}}>Risk signals · {step?.id}</h3><p style={S.small}>No probability, severity, SLA or monetary impact is generated without evidence.</p>{(step?.risks||[]).length?(step.risks||[]).map(r=><div key={r.id} style={{padding:9,border:'1px solid #e1e9ed',borderRadius:8,marginTop:6}}><Status>{r.status}</Status><b style={{display:'block',marginTop:5,fontSize:12}}>{r.title}</b><div style={S.small}>{r.explanation}</div><div style={{...S.small,marginTop:4}}><b>Basis:</b> {r.basis}</div></div>):<div style={S.small}>No risk signal beyond the modeled rule/control.</div>}</div><div style={{...S.panel,padding:12}}><b>Controls</b><Item label="Decision" value={step?.decision}/><Item label="Rule" value={step?.rule}/><Item label="Control" value={step?.control}/><Item label="Evidence" value={step?.evidence}/><Item label="Exception owner" value={step?.actor?.exceptionOwner}/></div></div>}
      {view==='Systems & Actors'&&<div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:10}}><div style={{...S.panel,padding:12}}><h3 style={{marginTop:0}}>Actors · {step?.id}</h3><Item label="Performer" value={step?.actor?.performer}/><Item label="Owner" value={step?.actor?.owner}/><Item label="Decision authority" value={step?.actor?.decisionAuthority}/><Item label="Custody" value={step?.actor?.custody}/><Item label="Exception owner" value={step?.actor?.exceptionOwner}/></div><div style={{...S.panel,padding:12}}><h3 style={{marginTop:0}}>Systems</h3><Item label="Authority system" value={step?.systems?.authoritySystem}/><Item label="Authority object" value={step?.systems?.authorityObject}/><Item label="Producer" value={step?.systems?.producer}/><Item label="Consumers" value={step?.systems?.consumers}/><Item label="Interface" value={step?.systems?.interface}/></div></div>}
      {view==='Compare'&&<div style={{...S.panel,padding:12}}><div style={{display:'flex',justifyContent:'space-between',gap:8,flexWrap:'wrap'}}><div><h3 style={{margin:'0 0 4px'}}>Reference ↔ Client AS-IS ↔ TO-BE</h3><div style={S.small}>Difference from the reference is not automatically a gap. Unknown client execution remains UNKNOWN / REFERENCE_ONLY.</div></div><div style={{display:'flex',gap:4}}>{['REFERENCE','AS_IS','TO_BE'].map(x=><button key={x} style={{...S.btn,background:twinLayer===x?'#0b7890':'#fff',color:twinLayer===x?'#fff':'#234'}} onClick={()=>{setTwinLayer(x);onEvent('TWIN_LAYER_CHANGED',{layer:x})}}>{x.replace('_',' ')}</button>)}</div></div><div style={{overflowX:'auto',marginTop:10}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:11}}><thead><tr><th style={{textAlign:'left',padding:6}}>Process</th><th style={{textAlign:'left'}}>Reference</th><th style={{textAlign:'left'}}>AS-IS</th><th style={{textAlign:'left'}}>TO-BE</th><th style={{textAlign:'left'}}>Delta state</th></tr></thead><tbody>{compareRows.map(r=><tr key={r.processId} style={{borderTop:'1px solid #e5ecef'}}><td style={{padding:7}}><b>{r.processId}</b><br/>{r.label}</td><td>{r.reference}</td><td>{r.asIs.status}{r.asIs.label?<><br/>{r.asIs.label}</>:null}</td><td>{r.toBe.status}{r.toBe.label?<><br/>{r.toBe.label}</>:null}</td><td>{r.change}</td></tr>)}</tbody></table></div></div>}
    </div>
  </div>
}
