const fs=require('fs');const assert=require('assert');
const p=JSON.parse(fs.readFileSync('data/generated/malkom-domain-warehouse/road-ltl-ltl04-projection-boundary-v1.json','utf8'));
const s=JSON.parse(fs.readFileSync('data/contracts/atlas-malkom-projection-boundary-v1.schema.json','utf8'));
assert.equal(p.schemaVersion,'atlas-malkom-projection-boundary-v1.0');
assert.equal(p.consumer,'MALKOM');
assert.equal(p.sourcePackage.packageId,'malkom-dw::road-ltl::LTL-04::v1');
assert.equal(p.sourcePackage.workDefinitionId,'wd::road-ltl::LTL-04::v1');
assert.equal(p.sourcePackage.sourceReleaseTip,'a57ad4d4f9488f190737701736beb5f807a19867');
assert.equal(p.canonicalBoundary.canonicalMutation,false);
assert.equal(p.canonicalBoundary.failClosed,true);
assert.equal(p.release.deterministic,true);
assert.equal(p.release.interface.apiEndpoint,null);
assert.equal(p.release.interface.apiEndpointDisposition,'REQUIREMENT_NOT_CONFIRMED');
assert.equal(p.release.readiness,'CLIENT_BINDING_REQUIRED');
for(const state of ['CLIENT_BINDING_REQUIRED','UNKNOWN','LOSS_OR_UNSUPPORTED','REQUIREMENT_NOT_CONFIRMED'])assert(p.capabilityMap.some(x=>x.state===state));
assert.equal(p.stopBoundary.requiredConsumer,'MALKOM');
assert.equal(p.stopBoundary.productionPromotionAuthorized,false);
for(const x of ['AGENTIC_AI','RPA_BPM_WORKFLOW','SAP','TMS','WMS','OTHER_RUNTIME_PACKAGES'])assert(p.stopBoundary.excludedConsumers.includes(x));
assert(p.trace.canonicalWorkDefinition&&p.trace.clientBindings&&p.trace.malkomPackage);
assert.equal(s.properties.consumer.const,'MALKOM');
console.log('ATL-169 Malkom projection boundary: PASS');
