import assert from 'node:assert/strict';
import fs from 'node:fs';import crypto from 'node:crypto';
import {getIntegrityManifest,verifyModelIntegrity} from '../lib/atlas/store.js';
import {capabilityManifest} from '../lib/runtime/capabilities.js';
import {retrieveFullAtlas} from '../lib/atlas/full-search.js';
const h=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'),m=getIntegrityManifest();
const v=verifyModelIntegrity();assert.equal(v.ok,true);assert.equal(v.checks.strippedFoundation,true);assert.equal(v.checks.publicFrozenV622,true);assert.equal(v.checks.page0Frozen,true);assert.equal(v.checks.constitution,true);
assert.equal(h('public/atlas-v6.2.2-frozen.html'),m.integratedRoadLtl.sha256);assert.equal(h(`frozen/${m.integratedRoadLtl.name}`),m.integratedRoadLtl.sha256);assert.equal(h(`frozen/${m.frozenPage0.name}`),m.frozenPage0.sha256);
const atlas=fs.readFileSync('public/atlas.html','utf8');assert.match(atlas,/V6\.2\.3 ADDITIVE GUIDE START/);assert.match(atlas,/How to Read the Atlas · V6\.2\.3/);assert.match(atlas,/window\.__ATLAS_GUIDE_V623__/);assert.ok(retrieveFullAtlas('How Page 0 and Road LTL came to life').length>0);
const c=capabilityManifest();assert.equal(c.version,'0.6.6');assert.equal(c.integration.atlasRelease,'V6.2.3');assert.equal(c.integration.frozenFoundation,'V6.2.2');assert.equal(c.integration.roadLtl,'V1.2');assert.equal(c.integration.constitution,'atlas-constitution-v6.2.3');assert.equal(c.runtime.plainEnglishLLMExplanation,true);assert.equal(m.automaticAtlasCorrection,false);
const page=fs.readFileSync('app/page.js','utf8');assert.match(page,/Atlas Intelligence v0\.6\.6/);assert.match(page,/How to read Atlas/);assert.match(page,/Minimize Atlas Intelligence/);assert.match(page,/LLM OFF · deterministic fallback/);
console.log('integration: PASS');
