const cp=require('child_process'),fs=require('fs'),assert=require('assert');
const run=()=>cp.execFileSync(process.execPath,['scripts/materialize-workdefinition-v1.cjs','--plan'],{encoding:'utf8'});
const a=run(),b=run();assert.strictEqual(a,b);
const p=JSON.parse(a),s=JSON.parse(fs.readFileSync('data/contracts/atlas-workdefinition-v1.schema.json','utf8'));
assert.strictEqual(p.status,'S8_2E_CONFORMED_NOT_REGENERATED');
assert.strictEqual(p.effectiveModuleVersion,'1.5');
assert.strictEqual(p.semanticRecordId,'road-ltl::LTL-04::operational-semantics::v1');
assert.strictEqual(p.governingContracts.decomposition.commit,'c72b50025d38c6ba103a98e6b698ac2181d5017b');
assert.strictEqual(p.governingContracts.decomposition.blob,'046885c71dc9fb24532b398cacd47ffc522f3a1b');
assert.strictEqual(p.governingContracts.workDefinition.blob,'c074489f2cf7edacde962f7e0260e2b240d24b87');
assert.strictEqual(p.compilerPolicy.compilationUnit,'EXECUTOR_READY_TERMINAL_DECOMPOSITION_LEAF_ONLY');
assert.strictEqual(p.compilerPolicy.blockedLeafCompilation,false);
assert.strictEqual(p.compilerPolicy.canonicalClientValues,false);
assert.strictEqual(p.compilerPolicy.runtimeSpecificStructure,false);
assert.strictEqual(p.regeneration.performed,false);
assert.strictEqual(p.regeneration.stage,'S8-3');
for(const k of ['schemaVersion','workDefinitionId','contractVersion','version','status','title','purpose','lineage','provenance','executability']) assert.ok(s.required.includes(k));
assert.strictEqual(s.properties.contractVersion.const,'1.0.0');
assert.strictEqual(s.properties.executability.properties.status.const,'EXECUTOR_READY');
assert.strictEqual(s.properties.executability.properties.independentExecutorProofStatus.const,'NOT_INDEPENDENTLY_PROVEN');
console.log('PASS S8-2E historical lineage-plan compatibility only; regeneration=false; leaf compiler QA is separate');
