import assert from 'node:assert/strict';
import cp from 'node:child_process';
import {reconstructTask} from '../lib/compile/source-task-decomposition.js';
import {compileCorrectedTask} from '../lib/compile/s8-workdefinition-compiler.js';
import {canonicalHash,stableStringify} from '../lib/compile/workdefinition-compiler.js';

const SOURCE_COMMIT='662c7847d3839c1ffd95dc8589d3d0d6ac100d67';
const SOURCE_PATH='data/modules/road-ltl-v1.4.json';
const SOURCE_BLOB='d06974e9ee86cea59227e0866a98ad5d1367bfad';
const git=args=>cp.execFileSync('git',['-c',`safe.directory=${process.cwd()}`,...args],{encoding:'utf8',maxBuffer:20_000_000}).trim();
assert.equal(git(['rev-parse',`${SOURCE_COMMIT}:${SOURCE_PATH}`]),SOURCE_BLOB);
const source=JSON.parse(git(['show',`${SOURCE_COMMIT}:${SOURCE_PATH}`]));
const task=source.tasks.find(task=>task.taskId==='LTL-04');
const donor=script=>JSON.parse(cp.execFileSync(process.execPath,[script],{encoding:'utf8'}));
const semantics=donor('scripts/materialize-operational-semantics-v1.cjs');
const binding=donor('scripts/materialize-client-binding-v1.cjs');
const record=semantics.records.find(record=>record.processId==='LTL-04');
const sourcePin={commit:SOURCE_COMMIT,path:SOURCE_PATH,blob:SOURCE_BLOB,taskHash:canonicalHash(task),semanticSourceVersion:'1.4'};
const inputsBefore=stableStringify({task,semantics,binding});
const envelope=reconstructTask(task,sourcePin,record,binding);
const repeat=reconstructTask(task,sourcePin,record,binding);
assert.equal(stableStringify(envelope),stableStringify(repeat));
assert.equal(stableStringify({task,semantics,binding}),inputsBefore);
const inputHash=canonicalHash(envelope.decomposition);
const compiled=compileCorrectedTask(envelope,inputHash,semantics,binding);
const compiledAgain=compileCorrectedTask(repeat,inputHash,semantics,binding);
assert.equal(stableStringify(compiled),stableStringify(compiledAgain));
assert.equal(compiled.definitions.length,1);
assert.equal(compiled.totals.leafCount,5);
assert.equal(compiled.totals.notCompiledLeafCount,4);
assert.equal(compiled.totals.blockedByClientBindingLeafCount,2);
assert.equal(compiled.totals.blockedByKnowledgeGapLeafCount,2);
assert.equal(compiled.definitions[0].lineage.sourceWorkUnitId,'LTL-04::ACT::02');
assert.deepEqual(compiled.definitions[0].executability.requiredClientBindings,['binding::road-ltl::LTL-04::execution-parameters']);
assert.equal(compiled.definitions[0].executability.independentExecutorProofStatus,'NOT_INDEPENDENTLY_PROVEN');
assert.ok(!stableStringify(compiled).includes('pickup-planner'));
assert.ok(!stableStringify(compiled).includes('malkom-demo'));
const changedTask=structuredClone(task);changedTask.baseline.rule='unsupported';
assert.throws(()=>reconstructTask(changedTask,sourcePin,record,binding),/HASH_MISMATCH/);
const changedRecord=structuredClone(record);changedRecord.rule='unsupported';
assert.throws(()=>reconstructTask(task,sourcePin,changedRecord,binding),/SOURCE_MISMATCH/);
console.log('PASS S8-3B LTL-04: 1 protected WD, deterministic/schema-valid, 4 blocked leaves preserved, no client values, 2 rejection cases.');

