import assert from 'node:assert/strict';
import {emptyWorkspace,FACT_STATUS} from '../lib/scenario/contracts.js';
import {validateWorkspace,validateProcessOrder} from '../lib/scenario/validator.js';
import {analyzeWorkspace,deltaView} from '../lib/scenario/analyzer.js';
import {suggestFutureState} from '../lib/scenario/transformer.js';
import {getModel,verifyModelIntegrity} from '../lib/atlas/store.js';
const model=getModel(); const ws=emptyWorkspace(); ws.client.name='Test Client'; ws.client.geography='US'; ws.reference.processIds=model.processes.map(p=>p.id);
ws.asIs.facts=ws.reference.processIds.map(id=>({processId:id,status:FACT_STATUS.REFERENCE_ONLY}));
ws.asIs.facts[0]={processId:'LTL-01',status:FACT_STATUS.CONFIRMED,clientLabel:'Client Shipment Intake',systemName:'Client OMS',evidenceText:'Workshop 1',manualHandoff:'Email intake'};
ws.asIs.facts[1]={processId:'LTL-02',status:FACT_STATUS.UNKNOWN};
let v=validateWorkspace(ws); assert.equal(v.passed,true); assert.equal(verifyModelIntegrity().ok,true);
let a=analyzeWorkspace(ws); assert.equal(a.summary.mapped,1); assert.ok(a.summary.referenceOnly>0); assert.ok(a.potentialGaps.some(g=>g.type==='MANUAL_HANDOFF')); assert.ok(a.discoveryQuestions.some(q=>q.processId==='LTL-02'));
const f=suggestFutureState(ws,a); assert.ok(f.suggestions.some(s=>s.processId==='LTL-01'));
ws.toBe.facts=JSON.parse(JSON.stringify(ws.asIs.facts)); ws.toBe.facts[0].clientLabel='Digital Shipment Intake'; assert.ok(deltaView(ws).some(d=>d.processId==='LTL-01'&&d.change==='CHANGED'));
const bad=JSON.parse(JSON.stringify(ws)); bad.asIs.facts[0].status='CONFIRMED'; bad.asIs.facts[0].evidenceText=''; bad.asIs.facts.push({processId:'BAD-99',status:'CONFIRMED',evidenceText:'x'}); assert.equal(validateWorkspace(bad).passed,false);
const refOnly=JSON.parse(JSON.stringify(ws)); refOnly.asIs.facts[3]={processId:'LTL-04',status:'REFERENCE_ONLY',clientValue:'pretend truth'}; assert.equal(validateWorkspace(refOnly).passed,false);
const mut=JSON.parse(JSON.stringify(ws)); mut.client.notes='please edit atlas and change atlas'; assert.equal(validateWorkspace(mut).passed,false);
const order=validateProcessOrder(['LTL-01','LTL-02','LTL-03','LTL-04']); assert.equal(order.passed,true);
console.log('scenario-smoke: PASS');
