import fs from 'node:fs';import path from 'node:path';import health from '../../api/health.js';import version from '../../api/version.js';import readiness from '../../api/readiness.js';import pilotReadiness from '../../api/pilot-readiness.js';import integrity from '../../api/release-integrity.js';import ask from '../../api/ask-atlas.js';import validate from '../../api/command-validate.js';import {root} from './common.mjs';
function req(method='GET',body=undefined){return {method,query:{},headers:{},body,async *[Symbol.asyncIterator](){}}}
function res(){return {statusCode:0,headers:{},setHeader(k,v){this.headers[k]=v},end(v){this.payload=v?JSON.parse(v):null}}}
async function call(fn,r){const s=res();await fn(r,s);return s}
const checks=[];const add=(name,ok,detail='')=>checks.push({name,ok,detail});
process.env.ATLAS_RELEASE_CHANNEL='lab';process.env.SUPABASE_URL='https://example.supabase.co';process.env.SUPABASE_PUBLISHABLE_KEY='publishable-test-only';process.env.ATLAS_LLM_PROVIDER='none';
let x=await call(health,req());add('liveness 200',x.statusCode===200&&x.payload.ok,x.payload);x=await call(version,req());add('version stage23',x.statusCode===200&&x.payload.stage==='23'&&x.payload.releaseId==='stage23-2026.08.23-r1',x.payload);
x=await call(integrity,req());add('release core integrity',x.statusCode===200&&x.payload.coreFrozen===true,x.payload?.files?.filter?.(y=>!y.ok));
const originalFetch=global.fetch;global.fetch=async()=>({ok:true,status:200});x=await call(readiness,req());add('readiness success with dependency',x.statusCode===200&&x.payload.ok,x.payload);global.fetch=originalFetch;
const oldUrl=process.env.SUPABASE_URL;delete process.env.SUPABASE_URL;x=await call(readiness,req());add('readiness fails missing required config',x.statusCode===503&&!x.payload.ok,x.payload?.checks);process.env.SUPABASE_URL=oldUrl;
process.env.ATLAS_EPHEMERAL_DOCUMENTS='true';process.env.ATLAS_EPHEMERAL_DOCUMENT_LLM='true';process.env.ATLAS_EPHEMERAL_DOCUMENT_REQUIRE_LLM='true';process.env.ATLAS_EPHEMERAL_DOCUMENT_PROVIDER_APPROVED='false';process.env.ATLAS_PILOT_LIVE_EVAL_PASSED='false';x=await call(pilotReadiness,req());add('pilot readiness fails before Gemini approval/eval',x.statusCode===503&&!x.payload.ok,x.payload?.checks?.filter(y=>!y.ok));process.env.ATLAS_LLM_PROVIDER='gemini';process.env.ATLAS_LLM_API_KEY='synthetic-key';process.env.ATLAS_LLM_MODEL='gemini-test';process.env.ATLAS_EPHEMERAL_DOCUMENT_PROVIDER_APPROVED='true';process.env.ATLAS_EPHEMERAL_DOCUMENT_ALLOWED_PROVIDERS='gemini';process.env.ATLAS_PILOT_LIVE_EVAL_PASSED='true';x=await call(pilotReadiness,req());add('pilot readiness passes after configured synthetic gate',x.statusCode===200&&x.payload.ok,x.payload?.checks);process.env.ATLAS_LLM_PROVIDER='none';delete process.env.ATLAS_LLM_API_KEY;delete process.env.ATLAS_LLM_MODEL;
x=await call(ask,req('POST',{question:'What happens at origin service centre receipt?',canvasState:{moduleId:'road-ltl'}}));add('Ask Atlas deterministic grounded response',x.statusCode===200&&x.payload.ok&&x.payload.citations?.length>0,{status:x.statusCode,citations:x.payload?.citations?.length});
x=await call(validate,req('POST',{canvasState:{moduleId:'road-ltl'},commands:[{type:'activate_module',args:{moduleId:'road-ftl'}}]}));add('command gate rejects unpublished A5 module',x.statusCode===200&&x.payload.rejected?.length===1,x.payload);
const stable=path.join(root,'release/packages/stable'),lab=path.join(root,'release/packages/lab');add('stable package excludes AP standalone',!fs.existsSync(path.join(stable,'accounts-payable-fixture-standalone.html')));add('lab package retains AP standalone',fs.existsSync(path.join(lab,'accounts-payable-fixture-standalone.html')));add('stable package excludes pilot corpus',!fs.existsSync(path.join(stable,'pilot')));add('lab package includes pilot evaluator',fs.existsSync(path.join(lab,'pilot/evaluation-harness.html')));add('stable package has API',fs.existsSync(path.join(stable,'api/ask-atlas.js')));add('stable package has Supply Chain module',fs.existsSync(path.join(stable,'data/modules/road-ltl-v1.2.json')));
const status=checks.every(x=>x.ok)?'PASS':'FAIL',out={stage:'23',status,checks};fs.writeFileSync(path.join(root,'release/evidence/release-smoke.json'),JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));if(status!=='PASS')process.exit(1);
