create table if not exists public.atlas_collaboration_comments(
 id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.atlas_workspaces(id) on delete cascade,
 entity_type text not null, entity_key text not null, comment_text text not null, created_by uuid not null references auth.users(id), resolved_at timestamptz, resolved_by uuid references auth.users(id), created_at timestamptz not null default now()
);
create table if not exists public.atlas_review_requests(
 id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.atlas_workspaces(id) on delete cascade,
 entity_type text not null, entity_key text not null, request_type text not null, request_text text, status text not null default 'OPEN', requested_by uuid not null references auth.users(id), assigned_to uuid references auth.users(id), resolution_note text, resolved_at timestamptz, created_at timestamptz not null default now()
);
create table if not exists public.atlas_usage_events(
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.atlas_workspaces(id) on delete cascade,
 user_id uuid not null references auth.users(id), event_name text not null, session_id text, module_id text, entity_key text, metadata jsonb not null default '{}'::jsonb, occurred_at timestamptz not null default now()
);
alter table public.atlas_collaboration_comments enable row level security;alter table public.atlas_review_requests enable row level security;alter table public.atlas_usage_events enable row level security;
create policy atlas_comments_member on public.atlas_collaboration_comments for all using(public.atlas_is_workspace_member(workspace_id)) with check(public.atlas_is_workspace_member(workspace_id));
create policy atlas_reviews_member on public.atlas_review_requests for all using(public.atlas_is_workspace_member(workspace_id)) with check(public.atlas_is_workspace_member(workspace_id));
create policy atlas_usage_insert on public.atlas_usage_events for insert with check(public.atlas_is_workspace_member(workspace_id) and user_id=auth.uid());
create policy atlas_usage_manager_select on public.atlas_usage_events for select using(public.atlas_is_workspace_manager(workspace_id));
