const PROVIDERS=['gemini','openai','anthropic'];
export function llmCapability(){const provider=(process.env.LLM_PROVIDER||'none').toLowerCase();const enabled=PROVIDERS.includes(provider);const model=process.env.LLM_MODEL||({gemini:'gemini-2.5-flash',openai:'gpt-5-mini',anthropic:'claude-sonnet-4-5'}[provider]||'none');const hasKey=provider==='gemini'?!!process.env.GEMINI_API_KEY:provider==='openai'?!!process.env.OPENAI_API_KEY:provider==='anthropic'?!!process.env.ANTHROPIC_API_KEY:false;return {enabled:enabled&&hasKey,provider,model,hasKey,requiredEnvironmentVariables:{provider:'LLM_PROVIDER',model:'LLM_MODEL',geminiKey:'GEMINI_API_KEY',openaiKey:'OPENAI_API_KEY',anthropicKey:'ANTHROPIC_API_KEY'},guardrail:'LLM receives an evidence packet only. Frozen Atlas and client evidence provenance remain authoritative.'}}
function systemPrompt(){return `You are the Atlas Intelligence explanation layer. You are NOT the classifier and you are NOT a source of Atlas/client facts.
Rules:
1. Answer ONLY from the supplied EVIDENCE PACKET for Atlas/client claims. Never replace the packet with pretrained knowledge.
2. Start with a useful SIMPLE-ENGLISH explanation of what the process/term/tab/state means in real operations. Then explain WHY IT MATTERS and WHERE IT FITS when evidence supports those points.
3. After the practical explanation, preserve the governed Atlas classification, origin/provenance, source relationship, evidence/source IDs, applicability/confidence where available.
4. SOURCE-NATIVE, ATLAS CROSSWALK, ATLAS CHILD SYNTHESIS and RUNTIME/PRESENTATION STATE are different. Never collapse them. A supporting source does not make an Atlas-synthesized process source-native.
5. If the resolver says the term is ambiguous, do not choose a meaning; ask the clarification question.
6. Never imply REFERENCE_ONLY, INFERRED, OBSERVED or PUBLICLY_EVIDENCED is CLIENT CONFIRMED.
7. If evidence is insufficient, say so explicitly.
8. Never propose or perform a mutation to frozen Page 0 V6.2.2 or Road LTL V1.2. Corrections are advisory and manually governed.
9. You MAY give a generic real-world logistics example to help a novice understand a grounded concept, but clearly label it as an illustrative example and do not present it as an Atlas source claim or client fact.
10. Keep answers compact by default. Suggested order: In simple English -> Why it matters -> Where it fits -> Atlas classification -> Origin/provenance -> Evidence/source -> Applicability/confidence -> optional next action.
Return plain text only.`}
async function gemini({prompt,model}){const url=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(process.env.GEMINI_API_KEY)}`;const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text:systemPrompt()+"\n\n"+prompt}]}],generationConfig:{temperature:0.1}})});if(!r.ok)throw new Error(`Gemini ${r.status}`);const j=await r.json();return j.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join('')||''}
async function openai({prompt,model}){const r=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{'content-type':'application/json','authorization':`Bearer ${process.env.OPENAI_API_KEY}`},body:JSON.stringify({model,messages:[{role:'system',content:systemPrompt()},{role:'user',content:prompt}],temperature:0.1})});if(!r.ok)throw new Error(`OpenAI ${r.status}`);const j=await r.json();return j.choices?.[0]?.message?.content||''}
async function anthropic({prompt,model}){const r=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'content-type':'application/json','x-api-key':process.env.ANTHROPIC_API_KEY,'anthropic-version':'2023-06-01'},body:JSON.stringify({model,max_tokens:1400,temperature:0.1,system:systemPrompt(),messages:[{role:'user',content:prompt}]})});if(!r.ok)throw new Error(`Anthropic ${r.status}`);const j=await r.json();return j.content?.map(x=>x.text||'').join('')||''}
export async function synthesize({question,evidencePacket,deterministicAnswer}){const cap=llmCapability();if(!cap.enabled)return {status:'DETERMINISTIC_FALLBACK',text:deterministicAnswer,capability:cap};const prompt=`QUESTION:\n${question}\n\nEVIDENCE PACKET:\n${JSON.stringify(evidencePacket,null,2)}\n\nDETERMINISTIC BASELINE:\n${deterministicAnswer}`;try{const text=cap.provider==='gemini'?await gemini({prompt,model:cap.model}):cap.provider==='openai'?await openai({prompt,model:cap.model}):await anthropic({prompt,model:cap.model});if(!text.trim())throw new Error('Empty LLM response');return {status:'LLM_SYNTHESIZED',text,capability:cap}}catch(error){return {status:'LLM_FAILED_SAFE',text:deterministicAnswer,capability:cap,error:String(error.message||error)}}}
