/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackageRouteImport } from './routes/package'
import { Route as FieldsFieldIdRouteImport } from './routes/fields.$fieldId'
import { Route as ApiBolIntelligencePackageRouteImport } from './routes/api/bol/intelligence-package'
import { Route as ApiBolFieldsIndexRouteImport } from './routes/api/bol/fields/index'
import { Route as ApiBolFieldsFieldIdRouteImport } from './routes/api/bol/fields/$fieldId'
import { Route as ApiBolFieldsFieldIdIntelligenceRouteImport } from './routes/api/bol/fields/$fieldId/intelligence'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageRoute = PackageRouteImport.update({
  id: '/package',
  path: '/package',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldsFieldIdRoute = FieldsFieldIdRouteImport.update({
  id: '/fields/$fieldId',
  path: '/fields/$fieldId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBolIntelligencePackageRoute =
  ApiBolIntelligencePackageRouteImport.update({
    id: '/api/bol/intelligence-package',
    path: '/api/bol/intelligence-package',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiBolFieldsIndexRoute = ApiBolFieldsIndexRouteImport.update({
  id: '/api/bol/fields/',
  path: '/api/bol/fields/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBolFieldsFieldIdRoute = ApiBolFieldsFieldIdRouteImport.update({
  id: '/api/bol/fields/$fieldId',
  path: '/api/bol/fields/$fieldId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBolFieldsFieldIdIntelligenceRoute =
  ApiBolFieldsFieldIdIntelligenceRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => ApiBolFieldsFieldIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/package': typeof PackageRoute
  '/fields/$fieldId': typeof FieldsFieldIdRoute
  '/api/bol/intelligence-package': typeof ApiBolIntelligencePackageRoute
  '/api/bol/fields/$fieldId': typeof ApiBolFieldsFieldIdRouteWithChildren
  '/api/bol/fields/': typeof ApiBolFieldsIndexRoute
  '/api/bol/fields/$fieldId/intelligence': typeof ApiBolFieldsFieldIdIntelligenceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/package': typeof PackageRoute
  '/fields/$fieldId': typeof FieldsFieldIdRoute
  '/api/bol/intelligence-package': typeof ApiBolIntelligencePackageRoute
  '/api/bol/fields/$fieldId': typeof ApiBolFieldsFieldIdRouteWithChildren
  '/api/bol/fields': typeof ApiBolFieldsIndexRoute
  '/api/bol/fields/$fieldId/intelligence': typeof ApiBolFieldsFieldIdIntelligenceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/package': typeof PackageRoute
  '/fields/$fieldId': typeof FieldsFieldIdRoute
  '/api/bol/intelligence-package': typeof ApiBolIntelligencePackageRoute
  '/api/bol/fields/$fieldId': typeof ApiBolFieldsFieldIdRouteWithChildren
  '/api/bol/fields/': typeof ApiBolFieldsIndexRoute
  '/api/bol/fields/$fieldId/intelligence': typeof ApiBolFieldsFieldIdIntelligenceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/package'
    | '/fields/$fieldId'
    | '/api/bol/intelligence-package'
    | '/api/bol/fields/$fieldId'
    | '/api/bol/fields/'
    | '/api/bol/fields/$fieldId/intelligence'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/package'
    | '/fields/$fieldId'
    | '/api/bol/intelligence-package'
    | '/api/bol/fields/$fieldId'
    | '/api/bol/fields'
    | '/api/bol/fields/$fieldId/intelligence'
  id:
    | '__root__'
    | '/'
    | '/package'
    | '/fields/$fieldId'
    | '/api/bol/intelligence-package'
    | '/api/bol/fields/$fieldId'
    | '/api/bol/fields/'
    | '/api/bol/fields/$fieldId/intelligence'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PackageRoute: typeof PackageRoute
  FieldsFieldIdRoute: typeof FieldsFieldIdRoute
  ApiBolIntelligencePackageRoute: typeof ApiBolIntelligencePackageRoute
  ApiBolFieldsFieldIdRoute: typeof ApiBolFieldsFieldIdRouteWithChildren
  ApiBolFieldsIndexRoute: typeof ApiBolFieldsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package': {
      id: '/package'
      path: '/package'
      fullPath: '/package'
      preLoaderRoute: typeof PackageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fields/$fieldId': {
      id: '/fields/$fieldId'
      path: '/fields/$fieldId'
      fullPath: '/fields/$fieldId'
      preLoaderRoute: typeof FieldsFieldIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bol/intelligence-package': {
      id: '/api/bol/intelligence-package'
      path: '/api/bol/intelligence-package'
      fullPath: '/api/bol/intelligence-package'
      preLoaderRoute: typeof ApiBolIntelligencePackageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bol/fields/': {
      id: '/api/bol/fields/'
      path: '/api/bol/fields'
      fullPath: '/api/bol/fields/'
      preLoaderRoute: typeof ApiBolFieldsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bol/fields/$fieldId': {
      id: '/api/bol/fields/$fieldId'
      path: '/api/bol/fields/$fieldId'
      fullPath: '/api/bol/fields/$fieldId'
      preLoaderRoute: typeof ApiBolFieldsFieldIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bol/fields/$fieldId/intelligence': {
      id: '/api/bol/fields/$fieldId/intelligence'
      path: '/intelligence'
      fullPath: '/api/bol/fields/$fieldId/intelligence'
      preLoaderRoute: typeof ApiBolFieldsFieldIdIntelligenceRouteImport
      parentRoute: typeof ApiBolFieldsFieldIdRoute
    }
  }
}

interface ApiBolFieldsFieldIdRouteChildren {
  ApiBolFieldsFieldIdIntelligenceRoute: typeof ApiBolFieldsFieldIdIntelligenceRoute
}

const ApiBolFieldsFieldIdRouteChildren: ApiBolFieldsFieldIdRouteChildren = {
  ApiBolFieldsFieldIdIntelligenceRoute: ApiBolFieldsFieldIdIntelligenceRoute,
}

const ApiBolFieldsFieldIdRouteWithChildren =
  ApiBolFieldsFieldIdRoute._addFileChildren(ApiBolFieldsFieldIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PackageRoute: PackageRoute,
  FieldsFieldIdRoute: FieldsFieldIdRoute,
  ApiBolIntelligencePackageRoute: ApiBolIntelligencePackageRoute,
  ApiBolFieldsFieldIdRoute: ApiBolFieldsFieldIdRouteWithChildren,
  ApiBolFieldsIndexRoute: ApiBolFieldsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}