import { workSourceBindingSchema, type WorkSourceBinding } from '../config/schemas.js';
import { UnsupportedError } from '../domain/errors.js';
import type { FilterExpr, Scalar } from '../domain/filter.js';
import type { SqlDialect } from '../sql/dialect.js';

/**
 * The default work table — a shipped CONVENTION, not a core dependency.
 *
 * Hosts that already have a work table bind it; hosts that don't can provision
 * `workEvents` and get a ready-made queue surface: an upstream producer INSERTs
 * work rows, the engine punches in allocatedTo/allocatedOn through the same
 * guarded-claim machinery as any other binding, and the front end fills
 * completedOn/taskStartTime/taskEndTime as agents work.
 *
 * Nothing in the core engine knows these column names — this module just
 * manufactures a standard WorkSourceBinding, and every name here is overridable.
 */
export const WORK_EVENTS_TABLE = 'workEvents';

export interface WorkEventsTableOptions {
  /** Physical table name; default 'workEvents'. */
  table?: string | undefined;
  schema?: string | undefined;
}

/**
 * Dialect-specific DDL for the workEvents table + indexes tuned for the
 * engine's candidate query (unallocated rows per queue/state, id order) and
 * load query (allocated-but-not-completed per worker).
 *
 * - `id` — incremental PK; arrival order, so FIFO needs no extra column.
 * - `queueId` / `subqueueId` — one physical table serves many queues.
 * - `transactionStateId` — HOST vocabulary (Indexed, Processed, Parked, ...).
 * - `allocatedTo` / `allocatedOn` — the only columns the engine ever writes.
 * - `completedOn`, `taskStartTime`, `taskEndTime` — front-end-owned; stamping
 *   completedOn automatically frees the worker's capacity on the next run.
 *
 * Cross-table FK constraints are deliberately omitted — the engine cannot know
 * the host's users/queues tables; add them yourself if you want enforcement.
 */
export function workEventsStatements(dialect: SqlDialect, opts: WorkEventsTableOptions = {}): string[] {
  const name = opts.table ?? WORK_EVENTS_TABLE;
  const t = dialect.qualifyTable(opts.schema !== undefined ? { schema: opts.schema, name } : { name });
  const q = (c: string) => dialect.quoteIdent(c);
  const ix = (suffix: string) => dialect.quoteIdent(`${name}_${suffix}`);

  switch (dialect.name) {
    case 'sqlite':
      return [
        `CREATE TABLE IF NOT EXISTS ${t} (
          ${q('id')} INTEGER PRIMARY KEY AUTOINCREMENT,
          ${q('queueId')} TEXT NOT NULL,
          ${q('subqueueId')} TEXT,
          ${q('transactionStateId')} TEXT NOT NULL,
          ${q('allocatedTo')} TEXT,
          ${q('allocatedOn')} TEXT,
          ${q('completedOn')} TEXT,
          ${q('taskStartTime')} TEXT,
          ${q('taskEndTime')} TEXT
        )`,
        `CREATE INDEX IF NOT EXISTS ${ix('alloc_idx')} ON ${t} (${q('queueId')}, ${q('transactionStateId')}, ${q('id')}) WHERE ${q('allocatedTo')} IS NULL`,
        `CREATE INDEX IF NOT EXISTS ${ix('load_idx')} ON ${t} (${q('allocatedTo')}) WHERE ${q('completedOn')} IS NULL`,
      ];
    case 'postgres':
      return [
        `CREATE TABLE IF NOT EXISTS ${t} (
          ${q('id')} BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          ${q('queueId')} TEXT NOT NULL,
          ${q('subqueueId')} TEXT,
          ${q('transactionStateId')} TEXT NOT NULL,
          ${q('allocatedTo')} TEXT,
          ${q('allocatedOn')} TIMESTAMPTZ,
          ${q('completedOn')} TIMESTAMPTZ,
          ${q('taskStartTime')} TIMESTAMPTZ,
          ${q('taskEndTime')} TIMESTAMPTZ
        )`,
        `CREATE INDEX IF NOT EXISTS ${ix('alloc_idx')} ON ${t} (${q('queueId')}, ${q('transactionStateId')}, ${q('id')}) WHERE ${q('allocatedTo')} IS NULL`,
        `CREATE INDEX IF NOT EXISTS ${ix('load_idx')} ON ${t} (${q('allocatedTo')}) WHERE ${q('completedOn')} IS NULL`,
      ];
    case 'mysql':
      // MySQL: no partial indexes, no IF NOT EXISTS on CREATE INDEX — the
      // provisioner tolerates duplicate-index errors to stay idempotent.
      return [
        `CREATE TABLE IF NOT EXISTS ${t} (
          ${q('id')} BIGINT AUTO_INCREMENT PRIMARY KEY,
          ${q('queueId')} VARCHAR(191) NOT NULL,
          ${q('subqueueId')} VARCHAR(191) NULL,
          ${q('transactionStateId')} VARCHAR(191) NOT NULL,
          ${q('allocatedTo')} VARCHAR(191) NULL,
          ${q('allocatedOn')} DATETIME(3) NULL,
          ${q('completedOn')} DATETIME(3) NULL,
          ${q('taskStartTime')} DATETIME(3) NULL,
          ${q('taskEndTime')} DATETIME(3) NULL
        )`,
        `CREATE INDEX ${ix('alloc_idx')} ON ${t} (${q('queueId')}, ${q('transactionStateId')}, ${q('id')})`,
        `CREATE INDEX ${ix('load_idx')} ON ${t} (${q('allocatedTo')}, ${q('completedOn')})`,
      ];
    default:
      throw new UnsupportedError(`no workEvents DDL for dialect ${JSON.stringify(dialect.name)}`);
  }
}

export interface WorkEventsBindingOptions {
  connectionRef: string;
  /** Value scoping this binding's rows in the shared table's queueId column. */
  queueId: string;
  /** Optional sub-queue scope (subqueueId column). */
  subqueueId?: Scalar | undefined;
  /** Which transactionStateId values are allocatable. Default ['Indexed'] — override with YOUR vocabulary. */
  allocatableStates?: string[] | undefined;
  /** Extra writes applied atomically with the claim, e.g. { transactionStateId: 'Allocated' }. */
  onAssignSet?: Record<string, Scalar> | undefined;
  /** Writes applied on release/stale-sweep, e.g. { transactionStateId: 'Indexed' }. */
  onReleaseSet?: Record<string, Scalar> | undefined;
  /** Columns surfaced to strategies/matching; default ['queueId', 'subqueueId']. */
  attributes?: string[] | undefined;
  batchLimit?: number | undefined;
  table?: string | undefined;
  schema?: string | undefined;
}

/**
 * Manufacture a standard WorkSourceBinding over the workEvents convention.
 * The result is validated through the exact same schema as any host binding —
 * this factory has no privileged path into the engine.
 */
export function workEventsBinding(opts: WorkEventsBindingOptions): WorkSourceBinding {
  const name = opts.table ?? WORK_EVENTS_TABLE;
  return workSourceBindingSchema.parse({
    connectionRef: opts.connectionRef,
    table: opts.schema !== undefined ? { schema: opts.schema, name } : { name },
    fields: {
      id: 'id',
      assignee: 'allocatedTo',
      state: 'transactionStateId',
      ...(opts.subqueueId !== undefined ? { subQueue: { column: 'subqueueId', value: opts.subqueueId } } : {}),
      assignedAt: { column: 'allocatedOn' }, // db-now, UTC
      attributes: opts.attributes ?? ['queueId', 'subqueueId'],
    },
    allocatableWhen: {
      op: 'and',
      args: [
        { op: 'eq', column: 'queueId', value: opts.queueId },
        { op: 'in', column: 'transactionStateId', values: opts.allocatableStates ?? ['Indexed'] },
      ],
    },
    // The incremental PK is the arrival order — FIFO's source of truth.
    ordering: [{ column: 'id', dir: 'asc' }],
    ...(opts.onAssignSet !== undefined ? { onAssign: { set: opts.onAssignSet } } : {}),
    ...(opts.onReleaseSet !== undefined ? { onRelease: { set: opts.onReleaseSet } } : {}),
    ...(opts.batchLimit !== undefined ? { batchLimit: opts.batchLimit } : {}),
  });
}

/**
 * Drop-in load spec for the workers binding: "open" = allocated but not yet
 * completed — the front end stamping completedOn frees capacity automatically.
 */
export const workEventsOpenLoad: { kind: 'count-open-items'; countWhere: FilterExpr } = {
  kind: 'count-open-items',
  countWhere: { op: 'isNull', column: 'completedOn' },
};
