/* Stage 21 · Collaboration + Product Telemetry
   Lightweight review workflow; sanitized usage analytics.
   No Atlas knowledge is created or mutated by this layer.
*/
(function(){
'use strict';
const API={collab:'/api/collaboration',telemetry:'/api/telemetry'};
const R={open:false,tab:'thread',entity:null,comments:[],reviews:[],openReviews:[],members:[],loading:false,message:'',analytics:null,analyticsLoading:false};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const now=()=>new Date().toISOString();
const uid=()=>window.AtlasStage17?.runtime?.user?.id||null;
const prodWorkspace=()=>window.AtlasStage17?.runtime?.user&&window.AtlasStage17?.runtime?.workspace?window.AtlasStage17.runtime.workspace:null;
const workspace=()=>window.S?.client?.workspace||null;
const uuid=()=>{try{if(globalThis.crypto?.randomUUID)return globalThis.crypto.randomUUID()}catch{}return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==='x'?r:(r&3|8);return v.toString(16)})};
const sessionId=(()=>{try{let x=sessionStorage.getItem('atlas-stage21-session');if(!x){x='S21-'+uuid();sessionStorage.setItem('atlas-stage21-session',x)}return x}catch{return 'S21-'+Math.random().toString(36).slice(2)+Date.now()}})();
const queue=[];
let flushTimer=null;
const SAFE_CONTEXT=new Set(['view','semanticLevel','lens','action','commandType','result','coverageDepth','signal','compareMode','durationMs','count','format','sourceClass','status','deviceClass','contextDimension','contextState','providerMode','grounded','citationCount']);
function deviceClass(){return innerWidth<640?'mobile':innerWidth<1024?'tablet':'desktop'}
function safeContext(o={}){const x={};for(const [k,v] of Object.entries(o||{})){if(SAFE_CONTEXT.has(k)&&['string','number','boolean'].includes(typeof v))x[k]=typeof v==='string'?v.slice(0,80):v}return x}
function ensureLocal(){const w=workspace();if(!w)return null;w.collaboration21=w.collaboration21||{comments:[],reviews:[],createdAt:now()};return w.collaboration21}
async function call(url,{method='GET',body}={}){const r=await fetch(url,{method,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,credentials:'same-origin'});const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{}if(!r.ok)throw new Error(d.error||d.message||`HTTP ${r.status}`);return d}
function currentEntity(){
 const S=window.S;if(!S)return {type:'WORKSPACE',key:'workspace',label:'Workspace'};
 const oid=S.opportunity?.selectedId;if(oid){const o=typeof opportunityById==='function'?opportunityById(oid):null;return {type:'OPPORTUNITY',key:oid,label:o?.title||oid}}
 const fid=S.transform?.selectedFinding;if(fid){const f=S.transform?.findings?.find(x=>x.id===fid);return {type:'FINDING',key:fid,label:f?.label||fid}}
 const cid=window.AtlasStage20?.runtime?.selectedCollection;if(cid){const c=workspace()?.investigationCollections?.[cid];if(c)return {type:'COLLECTION',key:cid,label:c.name||cid}}
 if(S.selectedProcess){const p=S.module?.processes?.find(x=>x.id===S.selectedProcess);return {type:'PROCESS',key:S.selectedProcess,label:p?.label||S.selectedProcess}}
 return {type:'WORKSPACE',key:prodWorkspace()?.id||'local-workspace',label:workspace()?.name||'Client Workspace'};
}
function keyOf(e){return `${e.type}:${e.key}`}
function localLoad(e){const s=ensureLocal();if(!s)return {comments:[],reviews:[]};return {comments:s.comments.filter(x=>x.entityType===e.type&&x.entityKey===e.key),reviews:s.reviews.filter(x=>x.entityType===e.type&&x.entityKey===e.key)}}
function memberLabel(id){if(!id)return 'Workspace / unassigned';if(id===uid())return 'You';const m=R.members.find(x=>x.user_id===id);return `${m?.role||'MEMBER'} · …${String(id).slice(-6)}`}
function localActorLabel(id){return id?memberLabel(id):'Local user'}
function isProd(){return !!prodWorkspace()}
function style(){if(document.getElementById('stage21Style'))return;const s=document.createElement('style');s.id='stage21Style';s.textContent=`
.stage21-review-btn{display:none}.transform-mode .stage21-review-btn{display:inline-flex!important;align-items:center;gap:4px}
.stage21-drawer{position:fixed;z-index:184;right:9px;top:70px;bottom:9px;width:min(470px,calc(100vw - 18px));background:#fff;border:1px solid #d4e1e4;border-radius:15px;box-shadow:0 22px 70px rgba(9,34,43,.22);transform:translateX(calc(100% + 28px));transition:transform .22s;display:flex;flex-direction:column;overflow:hidden}.stage21-drawer.open{transform:translateX(0)}
.stage21-head{display:flex;align-items:flex-start;gap:9px;padding:12px 13px;border-bottom:1px solid #e2eaec;background:linear-gradient(135deg,#f8fbfc,#fff)}.stage21-head>div{flex:1}.stage21-head h3{font-size:13px;margin:0;color:#183f4d}.stage21-head p{font-size:8px;color:#71868d;line-height:1.45;margin:3px 0 0}.stage21-close{border:0;background:#eef4f5;width:30px;height:30px;border-radius:50%;font-size:18px;color:#60767d}
.stage21-context{padding:8px 11px;border-bottom:1px solid #e5ecee;background:#fbfdfd}.stage21-context b{font-size:9px;color:#285461}.stage21-context small{display:block;font:750 7px ui-monospace;color:#849399;margin-top:2px}.stage21-boundary{font-size:7.5px;line-height:1.45;color:#637b83;padding:6px 8px;border-left:3px solid #82bdc9;background:#f2f9fa;margin-top:6px}.stage21-boundary.local{border-left-color:#c89b44;background:#fff9eb}
.stage21-tabs{display:flex;gap:3px;padding:6px 9px;border-bottom:1px solid #e6edef}.stage21-tabs button{border:1px solid transparent;background:transparent;border-radius:7px;padding:6px 8px;font:800 8px ui-monospace;color:#71878e}.stage21-tabs button.active{background:#edf8fa;border-color:#c6e5eb;color:#087c94}
.stage21-body{padding:10px;overflow:auto;display:grid;gap:8px}.stage21-card{border:1px solid #dce6e8;border-radius:10px;padding:9px;background:#fff}.stage21-card h4{font-size:9px;margin:0 0 6px;color:#315762}.stage21-card p{font-size:8px;line-height:1.45;color:#73868c}.stage21-card textarea,.stage21-card select{width:100%;border:1px solid #cedde0;border-radius:7px;padding:7px;font:10px system-ui;color:#294b55;background:#fff}.stage21-card textarea{min-height:70px;resize:vertical}.stage21-row{display:flex;gap:6px;align-items:center;flex-wrap:wrap;margin-top:6px}.stage21-row button{border:1px solid #c9dade;background:#fff;border-radius:7px;padding:6px 8px;font:800 8px ui-monospace;color:#315964}.stage21-row button.primary{background:#0d91a8;border-color:#0d91a8;color:#fff}.stage21-row button.ok{color:#256b4b;border-color:#bcdacb;background:#f2faf5}.stage21-row button.warn{color:#856219;border-color:#ead49d;background:#fff9e9}.stage21-empty{font-size:8px;color:#829298;padding:9px;border:1px dashed #dce5e7;border-radius:8px;background:#fafcfc}
.stage21-comment,.stage21-review{border:1px solid #e1e9eb;border-radius:8px;padding:8px;background:#fafcfc}.stage21-comment b,.stage21-review b{font-size:8px;color:#385d67}.stage21-comment small,.stage21-review small{display:block;font-size:7px;color:#89979c;margin:2px 0 5px}.stage21-comment p,.stage21-review p{white-space:pre-wrap;font-size:8.5px;line-height:1.45;color:#425d65;margin:0}.stage21-badge{display:inline-flex;border:1px solid #cfdfe2;border-radius:99px;padding:2px 5px;font:850 7px ui-monospace;color:#54727b;background:#f7fbfb;margin-right:4px}.stage21-badge.open{color:#8a6619;border-color:#ead59e;background:#fff8e8}.stage21-badge.done{color:#287050;border-color:#b9dbc9;background:#eff9f3}
.stage21-inspector{border-top:1px solid #dfe8ea;margin-top:9px;padding-top:9px}.stage21-inspector button{border:1px solid #c8dadd;background:#f8fbfb;border-radius:7px;padding:6px 8px;font:800 8px ui-monospace;color:#32606b}
.stage21-analytics{margin-top:10px;border-top:1px solid #dbe5e7;padding-top:10px}.stage21-analytics .gov-grid16{margin-top:7px}.stage21-analytics-list{display:grid;gap:4px;margin-top:7px}.stage21-analytics-row{display:flex;justify-content:space-between;gap:12px;font-size:8px;color:#5f767e;border-bottom:1px solid #edf1f2;padding:4px 0}.stage21-analytics-row b{color:#315763}.stage21-privacy{font-size:7.5px;line-height:1.45;background:#eff8f9;border-left:3px solid #69abb8;padding:7px;margin-top:7px;color:#5e7780}
@media(max-width:760px){.stage21-drawer{left:8px;right:8px;top:auto;bottom:8px;width:auto;max-height:82dvh;border-radius:16px 16px 12px 12px;transform:translateY(calc(100% + 30px))}.stage21-drawer.open{transform:translateY(0)}}
`;document.head.appendChild(s)}
function inject(){style();if(!document.getElementById('stage21ReviewBtn')){const tb=document.querySelector('.canvas-toolbar');const b=document.createElement('button');b.id='stage21ReviewBtn';b.className='stage21-review-btn';b.textContent='☏ Review';const d=document.getElementById('stage20DeliverBtn');tb?.insertBefore(b,d||document.getElementById('resetBtn')||null);b.onclick=()=>open()}
 if(!document.getElementById('stage21Drawer')){const d=document.createElement('aside');d.id='stage21Drawer';d.className='stage21-drawer';d.setAttribute('role','dialog');d.setAttribute('aria-hidden','true');d.setAttribute('aria-labelledby','stage21Title');d.innerHTML=`<div class="stage21-head"><div><h3 id="stage21Title">Review & Collaboration</h3><p>Comments and validation requests are client-workspace objects. They never modify Atlas Reference.</p></div><button class="stage21-close" id="stage21Close" aria-label="Close collaboration">×</button></div><div class="stage21-context" id="stage21Context"></div><div class="stage21-tabs"><button data-s21tab="thread" class="active">Thread</button><button data-s21tab="requests">Open requests</button></div><div class="stage21-body" id="stage21Body"></div>`;document.body.appendChild(d);document.getElementById('stage21Close').onclick=close;d.querySelectorAll('[data-s21tab]').forEach(x=>x.onclick=()=>{R.tab=x.dataset.s21tab;if(R.tab==='requests')loadOpenRequests();else loadEntity()})}
 injectAnalyticsCard();
}
function injectAnalyticsCard(){const host=document.querySelector('#govDrawer16 .gov-body16')||document.querySelector('#govDrawer16');if(!host||document.getElementById('stage21Analytics'))return;const sec=document.createElement('section');sec.id='stage21Analytics';sec.className='gov-card16 stage21-analytics';sec.innerHTML=`<h3>Product telemetry</h3><div id="stage21AnalyticsBody"><div class="gov-empty16">Telemetry initializes with Stage 21.</div></div><div class="gov-actions16" style="margin-top:7px"><button id="stage21RefreshAnalytics">Refresh analytics</button></div><div class="stage21-privacy"><b>Privacy boundary:</b> telemetry stores event types and sanitized product metadata only. Ask text, document content, client evidence, comments, names and other free text are excluded.</div>`;host.appendChild(sec);document.getElementById('stage21RefreshAnalytics').onclick=refreshAnalytics}
function open(entity=currentEntity()){R.entity=entity;R.open=true;R.message='';try{window.v152CloseSurfaces?.('stage21Drawer')}catch{}document.getElementById('stage20Drawer')?.classList.remove('open');const d=document.getElementById('stage21Drawer');d?.classList.add('open');d?.setAttribute('aria-hidden','false');track('collaboration_open',{entityType:entity.type,entityKey:entity.key});loadEntity()}
function close(){R.open=false;const d=document.getElementById('stage21Drawer');d?.classList.remove('open');d?.setAttribute('aria-hidden','true')}
async function loadEntity(){if(!R.entity)R.entity=currentEntity();R.loading=true;render();if(isProd()){try{const w=prodWorkspace();const q=`${API.collab}?workspaceId=${encodeURIComponent(w.id)}&entityType=${encodeURIComponent(R.entity.type)}&entityKey=${encodeURIComponent(R.entity.key)}`;const d=await call(q);R.comments=d.comments||[];R.reviews=d.reviews||[];R.members=d.members||[];R.message=''}catch(e){R.message=e.message}}else{const x=localLoad(R.entity);R.comments=x.comments;R.reviews=x.reviews;R.members=[]}R.loading=false;render()}
async function loadOpenRequests(){R.loading=true;render();if(isProd()){try{const w=prodWorkspace(),d=await call(`${API.collab}?workspaceId=${encodeURIComponent(w.id)}&mode=open`);R.openReviews=d.reviews||[];R.members=d.members||[];R.message=''}catch(e){R.message=e.message}}else{R.openReviews=(ensureLocal()?.reviews||[]).filter(x=>x.status==='OPEN').sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||''))}R.loading=false;render()}
function renderContext(){const e=R.entity||currentEntity(),p=isProd();const el=document.getElementById('stage21Context');if(!el)return;el.innerHTML=`<b>${esc(e.label)}</b><small>${esc(e.type)} · ${esc(e.key)}</small><div class="stage21-boundary ${p?'':'local'}">${p?'Shared production workspace · tenant RLS active.':'LOCAL REVIEW MODE · useful for preview/testing only; comments are not shared with other users.'}</div>`}
function threadHtml(){if(R.loading)return '<div class="stage21-empty">Loading collaboration…</div>';const comments=R.comments.map(c=>`<div class="stage21-comment"><span class="stage21-badge ${c.status==='OPEN'?'open':'done'}">${esc(c.status)}</span><b>${esc(isProd()?memberLabel(c.created_by):localActorLabel(c.createdBy))}</b><small>${esc(c.created_at||c.createdAt||'')}</small><p>${esc(c.body)}</p>${c.status==='OPEN'?`<div class="stage21-row"><button class="ok" data-s21-resolve-comment="${esc(c.id)}">Resolve</button></div>`:''}</div>`).join('')||'<div class="stage21-empty">No comments on this item.</div>';
 const reviews=R.reviews.map(x=>`<div class="stage21-review"><span class="stage21-badge ${x.status==='OPEN'?'open':'done'}">${esc(x.request_type||x.requestType||'VALIDATION')} · ${esc(x.status)}</span><b>${esc(isProd()?memberLabel(x.assigned_to):localActorLabel(x.assignedTo))}</b><small>Requested ${esc(x.created_at||x.createdAt||'')}</small><p>${esc(x.message)}</p>${x.resolution_note?`<p style="margin-top:5px"><b>Resolution:</b> ${esc(x.resolution_note)}</p>`:''}${x.status==='OPEN'?`<div class="stage21-row"><button class="ok" data-s21-complete-review="${esc(x.id)}">Complete</button></div>`:''}</div>`).join('')||'<div class="stage21-empty">No validation/review request on this item.</div>';
 return `<div class="stage21-card"><h4>Add comment</h4><textarea id="s21Comment" maxlength="4000" placeholder="Observation, workshop note, review comment…"></textarea><div class="stage21-row"><button class="primary" id="s21AddComment">Add comment</button></div></div><div class="stage21-card"><h4>Request validation</h4><select id="s21ReviewType"><option value="VALIDATION">Validation</option><option value="EVIDENCE">Evidence</option><option value="REVIEW">Review</option></select><textarea id="s21ReviewMessage" maxlength="4000" placeholder="What needs to be validated or reviewed?"></textarea><select id="s21Assignee"><option value="">Workspace / unassigned</option>${R.members.map(m=>`<option value="${esc(m.user_id)}">${esc(memberLabel(m.user_id))}</option>`).join('')}</select><div class="stage21-row"><button class="primary" id="s21RequestReview">Create request</button></div></div><div class="stage21-card"><h4>Comments</h4>${comments}</div><div class="stage21-card"><h4>Review requests</h4>${reviews}</div>`}
function requestsHtml(){if(R.loading)return '<div class="stage21-empty">Loading open requests…</div>';return `<div class="stage21-card"><h4>Workspace review queue</h4><p>Lightweight validation queue only. This is not a project-management system.</p></div>${R.openReviews.map(x=>`<div class="stage21-review"><span class="stage21-badge open">${esc(x.request_type||x.requestType||'REVIEW')}</span><b>${esc(x.entity_type||x.entityType)} · ${esc(x.entity_key||x.entityKey)}</b><small>Assignee: ${esc(isProd()?memberLabel(x.assigned_to):localActorLabel(x.assignedTo))} · ${esc(x.created_at||x.createdAt||'')}</small><p>${esc(x.message)}</p><div class="stage21-row"><button data-s21-open-entity="${esc(x.entity_type||x.entityType)}|${esc(x.entity_key||x.entityKey)}">Open item</button><button class="ok" data-s21-complete-review="${esc(x.id)}">Complete</button></div></div>`).join('')||'<div class="stage21-empty">No open review requests.</div>'}`}
function render(){renderContext();document.querySelectorAll('[data-s21tab]').forEach(x=>x.classList.toggle('active',x.dataset.s21tab===R.tab));const b=document.getElementById('stage21Body');if(!b)return;b.innerHTML=(R.message?`<div class="stage21-boundary local">${esc(R.message)}</div>`:'')+(R.tab==='thread'?threadHtml():requestsHtml());wire()}
function wire(){document.getElementById('s21AddComment')?.addEventListener('click',addComment);document.getElementById('s21RequestReview')?.addEventListener('click',requestReview);document.querySelectorAll('[data-s21-resolve-comment]').forEach(b=>b.onclick=()=>resolveComment(b.dataset.s21ResolveComment));document.querySelectorAll('[data-s21-complete-review]').forEach(b=>b.onclick=()=>completeReview(b.dataset.s21CompleteReview));document.querySelectorAll('[data-s21-open-entity]').forEach(b=>b.onclick=()=>{const [type,key]=b.dataset.s21OpenEntity.split('|');R.tab='thread';open({type,key,label:key})})}
async function addComment(){const text=(document.getElementById('s21Comment')?.value||'').trim();if(!text)return;const e=R.entity||currentEntity();if(isProd()){try{await call(API.collab,{method:'POST',body:{kind:'COMMENT',workspaceId:prodWorkspace().id,entityType:e.type,entityKey:e.key,body:text}});track('comment_add',{entityType:e.type,entityKey:e.key});await loadEntity()}catch(err){R.message=err.message;render()}}else{const s=ensureLocal(),x={id:'LC-'+Date.now(),entityType:e.type,entityKey:e.key,body:text,status:'OPEN',createdBy:'local',createdAt:now()};s.comments.push(x);persistClientWorkspace?.();track('comment_add',{entityType:e.type,entityKey:e.key});loadEntity()}}
async function requestReview(){const msg=(document.getElementById('s21ReviewMessage')?.value||'').trim();if(!msg)return;const type=document.getElementById('s21ReviewType')?.value||'VALIDATION',assigned=document.getElementById('s21Assignee')?.value||null,e=R.entity||currentEntity();if(isProd()){try{await call(API.collab,{method:'POST',body:{kind:'REVIEW',workspaceId:prodWorkspace().id,entityType:e.type,entityKey:e.key,requestType:type,message:msg,assignedTo:assigned}});track('review_request',{entityType:e.type,entityKey:e.key,status:type});await loadEntity()}catch(err){R.message=err.message;render()}}else{const s=ensureLocal(),x={id:'LR-'+Date.now(),entityType:e.type,entityKey:e.key,requestType:type,status:'OPEN',message:msg,assignedTo:assigned,createdAt:now()};s.reviews.push(x);persistClientWorkspace?.();track('review_request',{entityType:e.type,entityKey:e.key,status:type});loadEntity()}}
async function resolveComment(id){if(isProd()){try{await call(API.collab,{method:'PATCH',body:{kind:'COMMENT',workspaceId:prodWorkspace().id,id,status:'RESOLVED'}});track('comment_resolve');await loadEntity()}catch(err){R.message=err.message;render()}}else{const x=ensureLocal()?.comments.find(v=>v.id===id);if(x){x.status='RESOLVED';x.resolvedAt=now();persistClientWorkspace?.()}track('comment_resolve');loadEntity()}}
async function completeReview(id){const note=prompt('Resolution note (required to complete):')?.trim();if(!note)return;if(isProd()){try{await call(API.collab,{method:'PATCH',body:{kind:'REVIEW',workspaceId:prodWorkspace().id,id,status:'COMPLETED',resolutionNote:note}});track('review_complete');R.tab==='requests'?await loadOpenRequests():await loadEntity()}catch(err){R.message=err.message;render()}}else{const x=ensureLocal()?.reviews.find(v=>v.id===id);if(x){x.status='COMPLETED';x.resolutionNote=note;x.completedAt=now();persistClientWorkspace?.()}track('review_complete');R.tab==='requests'?loadOpenRequests():loadEntity()}}
function appendInspector(){const body=document.getElementById('inspectorBody');if(!body||body.querySelector('.stage21-inspector')||body.dataset.sourceView==='1')return;const e=currentEntity();if(e.type==='WORKSPACE')return;body.insertAdjacentHTML('beforeend',`<div class="stage21-inspector"><h3>Review & collaboration</h3><div class="stage21-boundary">Comments and review requests are client-workspace metadata. They do not alter this Atlas task/finding.</div><div class="stage21-row"><button id="s21ReviewSelected">Open review thread</button></div></div>`);document.getElementById('s21ReviewSelected')?.addEventListener('click',()=>open(currentEntity()))}
function patchInspector(){const f=window.renderInspector;if(typeof f!=='function'||window.__stage21InspectorPatched)return;window.__stage21InspectorPatched=true;window.renderInspector=function(){const r=f.apply(this,arguments);setTimeout(appendInspector,0);return r};try{renderInspector=window.renderInspector}catch{}}
function eventRecord(eventName,context={},entityType=null,entityKey=null){return {clientEventId:uuid(),sessionId,eventName,domainPackId:window.S?.activeDomainPackId||window.S?.module?.domainPackId||null,moduleId:window.S?.module?.module?.id||window.S?.activeModule||null,entityType:entityType||null,entityKey:entityKey||null,context:{deviceClass:deviceClass(),...safeContext(context)},occurredAt:now()}}
function track(eventName,context={},entityType=null,entityKey=null){const ev=eventRecord(eventName,context,entityType,entityKey);queue.push(ev);try{const local=JSON.parse(sessionStorage.getItem('atlas-stage21-events')||'[]');local.push(ev);sessionStorage.setItem('atlas-stage21-events',JSON.stringify(local.slice(-500)))}catch{}if(queue.length>=15)flush();else{clearTimeout(flushTimer);flushTimer=setTimeout(flush,12000)}return ev}
async function flush(){clearTimeout(flushTimer);if(!isProd()||!queue.length)return;const batch=queue.splice(0,50);try{await call(API.telemetry,{method:'POST',body:{workspaceId:prodWorkspace().id,events:batch}})}catch{queue.unshift(...batch);if(queue.length>300)queue.splice(0,queue.length-300)}}
function patchTelemetry(){
 const wrap=(name,event,ctxFn,entityFn)=>{const old=window[name];if(typeof old!=='function'||old.__s21)return;const n=function(){const r=old.apply(this,arguments);try{const c=ctxFn?ctxFn(arguments):{},e=entityFn?entityFn(arguments):null;track(event,c,e?.type,e?.key)}catch{}return r};n.__s21=true;window[name]=n;try{eval(`${name}=window[name]`)}catch{}};
 wrap('activateModule','module_activate',a=>({result:'activated'}),a=>({type:'MODULE',key:String(a[0]||'')}));
 wrap('selectProcess','process_select',()=>({semanticLevel:window.S?.visual152?.level??null}),a=>({type:'PROCESS',key:String(a[0]||'')}));
 wrap('v152SetLevel','semantic_zoom',a=>({semanticLevel:Number(a[0])}));
 wrap('startPlayback','playback_start',()=>({signal:window.S?.playback?.followSignal||'all'}));
 wrap('startTrace','trace_start',a=>({result:'started'}),a=>({type:'OBJECT',key:String(a[0]||'')}));
 wrap('openSource','source_open',a=>({sourceClass:'atlas-source'}),a=>({type:'SOURCE',key:String(a[0]||'')}));
 wrap('enterTransform','transform_enter',()=>({view:'transform'}));
 wrap('ctx13Set','context_change',a=>({contextDimension:String(a[0]||''),contextState:'changed'}));
 document.addEventListener('click',e=>{const b=e.target.closest?.('button,[data-open-source],[data-lens12-mode],[data-compare10-mode],[data-s20add]');if(!b)return;const id=b.id||'';if(id==='navExplore')track('view_enter',{view:'explore'});else if(id==='navExecute')track('view_enter',{view:'execute'});else if(id==='navCompare')track('compare_open',{view:'compare'});else if(id==='navTransform')track('view_enter',{view:'transform'});else if(id==='askSend')track('ask_atlas_submit',{view:window.S?.transform?.enabled?'transform':'atlas'});else if(id==='playPause'&&/pause/i.test(b.textContent))track('playback_pause',{action:'pause'});else if(id==='findingsBtn')track('finding_open',{view:'transform'});else if(id==='opportunityBtn')track('opportunity_open',{view:'transform'});else if(id==='futureBtn')track('future_state_open',{view:'transform'});else if(id==='stage20DeliverBtn')track('executive_summary_open',{view:'deliver'});else if(id==='docs19Btn'||id==='mobileDocs19')track('document_workspace_open',{view:'documents'});else if(id==='doc19Upload')track('document_ingest',{view:'documents'});else if(id==='s20StartPresent')track('presentation_start',{view:'presentation'});else if(id==='s20CreateCollection')track('collection_create',{view:'deliver'});else if(b.dataset?.s20add)track('collection_item_add',{view:'deliver'});else if(/^s20Pack(Md|Json|Csv|Xlsx|Pdf|Pptx|Print)$/.test(id)){const format=id.replace('s20Pack','').toLowerCase();track('transformation_export',{format})}else if(b.dataset?.openSource)track('source_open',{sourceClass:'atlas-source'},'SOURCE',b.dataset.openSource);else if(b.dataset?.lens12Mode)track('lens_open',{lens:b.dataset.lens12Mode});else if(b.dataset?.compare10Mode)track('compare_open',{compareMode:b.dataset.compare10Mode});},true);
 const chat=document.getElementById('chatLog');if(chat&&!chat.dataset.s21Observed){chat.dataset.s21Observed='1';new MutationObserver(ms=>{for(const m of ms)for(const n of m.addedNodes){if(n.nodeType!==1||!n.classList?.contains('stage18-answer'))continue;const meta=n.querySelector('.grounded')?.textContent||'',citationCount=n.querySelectorAll('.stage18-ground button').length,providerMode=/DETERMINISTIC FALLBACK/i.test(meta)?'fallback':'provider';track('ask_atlas_result',{providerMode,grounded:true,citationCount,result:'answered'})}}).observe(chat,{childList:true})}
 document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){track('session_end',{durationMs:Math.round(performance.now())});flush()}});
 window.addEventListener('pagehide',()=>{track('session_end',{durationMs:Math.round(performance.now())});flush()});
}
function localAnalytics(){let rows=[];try{rows=JSON.parse(sessionStorage.getItem('atlas-stage21-events')||'[]')}catch{}if(!rows.length)rows=queue.slice();const counts={};rows.forEach(x=>counts[x.eventName]=(counts[x.eventName]||0)+1);return {periodDays:0,eventCount:rows.length,uniqueUsers:isProd()?1:0,uniqueSessions:rows.length?1:0,counts,topModules:[],topViews:Object.entries(counts).filter(([k])=>k==='view_enter').map(([key,count])=>({key,count})),results:[]}}
async function refreshAnalytics(){const body=document.getElementById('stage21AnalyticsBody');if(!body)return;R.analyticsLoading=true;body.innerHTML='<div class="gov-empty16">Loading sanitized usage analytics…</div>';if(isProd()){try{await flush();const d=await call(`${API.telemetry}?workspaceId=${encodeURIComponent(prodWorkspace().id)}&days=30`);R.analytics=d.analytics}catch(e){R.analytics={error:e.message}}}else R.analytics=localAnalytics();R.analyticsLoading=false;renderAnalytics()}
function renderAnalytics(){const b=document.getElementById('stage21AnalyticsBody');if(!b)return;const a=R.analytics||localAnalytics();if(a.error){b.innerHTML=`<div class="gov-note16">Analytics unavailable: ${esc(a.error)}. Workspace OWNER/ADMIN permission is required for aggregate telemetry.</div>`;return}const c=a.counts||{},top=Object.entries(c).sort((x,y)=>y[1]-x[1]).slice(0,8);b.innerHTML=`<div class="gov-grid16">${[[a.eventCount||0,'events'],[a.uniqueSessions||0,'sessions'],[a.uniqueUsers||0,'users'],[c.ask_atlas_submit||0,'Ask Atlas'],[c.trace_start||0,'traces'],[c.transform_enter||0,'Transform']].map(([n,l])=>`<div class="gov-stat16"><b>${n}</b><span>${esc(l)}</span></div>`).join('')}</div><div class="stage21-analytics-list">${top.map(([k,n])=>`<div class="stage21-analytics-row"><b>${esc(k)}</b><span>${n}</span></div>`).join('')||'<div class="gov-empty16">No telemetry events yet.</div>'}</div><div class="stage21-privacy">${isProd()?'30-day workspace aggregate.':'Local preview aggregate only; nothing has been uploaded.'}</div>`}
function patchGovernance(){const g=window.AtlasGovernance16;if(g&&!window.__stage21GovPatched){const old=g.open;g.open=function(){const r=old.apply(this,arguments);setTimeout(refreshAnalytics,50);return r};window.__stage21GovPatched=true}}
function patchWorkspace(){const s17=window.AtlasStage17;if(!s17||window.__stage21WorkspacePatched)return;window.__stage21WorkspacePatched=true;const old=s17.selectWorkspace;s17.selectWorkspace=async function(){const r=await old.apply(this,arguments);track('session_start',{view:'workspace'});setTimeout(flush,500);return r}}
function title(){const e=document.querySelector('.brand small');if(e)e.textContent='Enterprise Operations Platform · Supply Chain · Stage 21';document.title='Supply Chain Atlas · Stage 21 Collaboration & Telemetry'}
function boot(){if(!window.S||!document.body||!window.AtlasStage20){setTimeout(boot,80);return}ensureLocal();inject();patchInspector();patchTelemetry();patchGovernance();patchWorkspace();title();setTimeout(title,1200);setTimeout(title,2800);setTimeout(title,5000);track('session_start',{view:'atlas'});renderAnalytics();window.AtlasStage21={runtime:R,open,close,currentEntity,loadEntity,loadOpenRequests,track,flush,refreshAnalytics,privacy:{freeTextTelemetry:false,sanitizedContextKeys:[...SAFE_CONTEXT]}};setInterval(()=>{if(isProd())flush()},30000);setTimeout(appendInspector,100)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,260));else setTimeout(boot,260);
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&R.open){e.preventDefault();close()}},true);
})();
