(()=>{
'use strict';
const API='api/ask-atlas';const R={history:[],busy:false,online:null};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function state(){const p=window.S?.playback?.enabled?window.S.module?.processes?.find(x=>x.id===window.S.playback.sequence?.[window.S.playback.index]):null;return {moduleId:window.S?.activeModule||null,moduleVersion:window.S?.module?.module?.version||null,depth:window.S?.depth||null,semanticLevel:window.S?.visual152?.level??null,selectedDomain:window.S?.selectedDomain||null,selectedA3:window.S?.selectedA3||null,selectedProcess:window.S?.selectedProcess||null,playback:window.S?.playback?.enabled?{enabled:true,index:window.S.playback.index,processId:p?.id||null,follow:window.S.playback.follow||'all',frozen:!!window.S.playback.frozen}:null,trace:window.S?.trace?.enabled?{target:window.S.trace.target,index:window.S.trace.focusIndex}:null,lens:window.S?.lens12?{type:window.S.lens12.type,itemId:window.S.lens12.itemId}:null,context:window.S?.context13?{role:window.S.context13.role,movements:window.S.context13.movements,node:window.S.context13.node,jurisdictions:window.S.context13.jurisdictions,regimes:window.S.context13.regimes,conditions:window.S.context13.conditions,contract:window.S.context13.contract}:null,transform:window.S?.transform?{enabled:!!window.S.transform.enabled,filter:window.S.transform.filter,selectedFinding:window.S.transform.selectedFinding}:null}}
function workspaceId(){return window.AtlasStage17?.runtime?.workspace?.id||null}
async function call(question){const r=await fetch(API,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,canvasState:state(),workspaceId:workspaceId(),history:R.history.slice(-8)})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}
function style(){const e=document.createElement('style');e.textContent=`.stage18-ground{display:flex;gap:5px;flex-wrap:wrap;margin-top:7px}.stage18-ground button{border:1px solid #d4e2e5!important;background:#f6fafb!important;color:#48656d!important;border-radius:999px!important;padding:4px 7px!important;font:800 7.5px ui-monospace!important}.stage18-mode{display:inline-flex;align-items:center;gap:5px;margin-left:5px;padding:2px 6px;border-radius:999px;background:#eaf7f8;color:#0b7d91;font:800 7px ui-monospace}.stage18-mode.fallback{background:#f4f1e8;color:#866a24}.chat-msg.stage18-answer .grounded{display:block}.stage18-thinking{opacity:.7;font-style:italic}`;document.head.appendChild(e)}
function appendAnswer(d){const log=document.getElementById('chatLog');if(!log)return;const div=document.createElement('div');div.className='chat-msg atlas stage18-answer';div.append(document.createTextNode(d.answer||'No answer returned.'));const meta=document.createElement('span');meta.className='grounded';meta.textContent=d.provider?.used?`GROUNDED · ${String(d.provider.provider).toUpperCase()} · ${d.grounding?.cited||0} CITATION(S)`:`GROUNDED · DETERMINISTIC FALLBACK · ${d.grounding?.cited||0} CITATION(S)`;div.appendChild(meta);if(d.citations?.length){const c=document.createElement('div');c.className='stage18-ground';for(const x of d.citations){const b=document.createElement('button');b.textContent=`${x.id} · ${x.title}`;b.title=x.class;b.onclick=()=>{const sid=(x.sourceIds||[])[0];if(sid&&window.AtlasCommandBus?.openSource)window.AtlasCommandBus.openSource(sid);else if(x.content?.id&&/^LTL-/.test(x.content.id)&&window.selectProcess)window.selectProcess(x.content.id)};c.appendChild(b)}div.appendChild(c)}if(d.commands?.length){const a=document.createElement('div');a.className='chat-actions';for(const cmd of d.commands){const b=document.createElement('button');b.textContent=label(cmd);b.onclick=()=>exec(cmd,true);a.appendChild(b)}div.appendChild(a)}log.appendChild(div);log.scrollTop=log.scrollHeight}
function label(c){const a=c.args||{};return ({activate_module:'Activate module',reset_universe:'Universe',set_semantic_level:'Zoom',select_process:'Inspect task',playback:'Playback',set_follow_signal:'Follow signal',trace_object:'Trace object',open_source:'Open source',open_lens:'Open lens',set_context_option:'Apply context',clear_context:'Clear context',enter_transform:'Transform',open_findings:'Findings',open_opportunities:'Opportunities'})[c.type]||c.type}
function exec(c,announce=false){const a=c.args||{},bus=window.AtlasCommandBus;if(!bus)return false;try{switch(c.type){case'activate_module':bus.activateModule?.(a.moduleId);break;case'reset_universe':bus.reset?.();window.v152FitUniverse?.();break;case'set_semantic_level':window.v152SetLevel?.(Number(a.level));break;case'select_process':window.selectProcess?.(a.processId);break;case'playback':if(a.action==='start')window.startPlayback?.();else if(a.action==='pause')window.pausePlayback?.();else if(a.action==='freeze'){if(window.S?.playback?.enabled&&!window.S.playback.frozen)window.toggleFreeze?.()}else if(a.action==='step_forward')window.movePlayback?.(1);else if(a.action==='step_back')window.movePlayback?.(-1);else if(a.action==='exit')window.exitPlayback?.();break;case'set_follow_signal':window.setFollow?.(a.signal);break;case'trace_object':window.startTrace?.(a.objectId);break;case'open_source':bus.openSource?.(a.sourceId);break;case'open_lens':window.stage12OpenLens?.(a.lens);break;case'set_context_option':window.ctx13Set?.(a.dimension,a.optionId);break;case'clear_context':window.ctx13Clear?.();break;case'enter_transform':bus.enterTransform?.();break;case'open_findings':window.openFindingsDrawer?.();break;case'open_opportunities':bus.openOpportunities?.();break;default:return false}if(announce)window.addChat?.(`Applied validated command: ${label(c)}.`);return true}catch(e){window.addChat?.(`Command was not applied: ${e.message}`,'atlas',true);return false}}
async function ask(question){question=String(question||'').trim();if(!question||R.busy)return;R.busy=true;window.addChat?.(question,'user');const log=document.getElementById('chatLog'),thinking=document.createElement('div');if(log){thinking.className='chat-msg atlas stage18-thinking';thinking.textContent='Retrieving governed Atlas evidence…';log.appendChild(thinking);log.scrollTop=log.scrollHeight}try{const d=await call(question);thinking?.remove();appendAnswer(d);for(const cmd of (d.commands||[]))exec(cmd,false);R.history.push({role:'user',text:question},{role:'assistant',text:d.answer,citations:(d.citations||[]).map(x=>x.id)});R.online=true}catch(e){thinking?.remove();R.online=false;window.addChat?.(`Production Ask Atlas is unavailable (${e.message}). Falling back to the local deterministic command surface.`,'atlas',true);window.runAtlasCommand?.(question)}finally{R.busy=false}}
function patch(){style();const drawer=document.getElementById('askDrawer');if(drawer){const p=drawer.querySelector('.assistant-head p');if(p)p.innerHTML='Grounded retrieval + validated canvas commands <span class="stage18-mode" id="stage18Mode">Stage 18</span>';const note=drawer.querySelector('#askNote');if(note)note.textContent='Guardrail: retrieval happens before generation; the LLM may propose commands, but only deterministic validated Atlas code can execute them.'}
 const send=document.getElementById('askSend'),input=document.getElementById('askInput');if(send){send.addEventListener('click',e=>{if(!input?.value.trim())return;e.preventDefault();e.stopImmediatePropagation();const q=input.value;input.value='';ask(q)},true)}
 window.AtlasAsk18={ask,state,executeCommand:exec,runtime:R};
}
function boot(){if(document.getElementById('askSend')&&window.AtlasCommandBus)patch();else setTimeout(boot,50)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,120));else setTimeout(boot,120);
})();
