'use client';
import {useEffect,useRef,useState} from 'react';
const STATUSES=['CONFIRMED','OBSERVED','PUBLICLY_EVIDENCED','INFERRED','REFERENCE_ONLY','UNKNOWN'];
const blank={id:'local',client:{name:'',geography:'',scope:'Road LTL',notes:''},reference:{mode:'road-ltl',processIds:[]},asIs:{facts:[]},toBe:{facts:[]},evidence:[],metadata:{status:'DRAFT',atlasVersion:'V6.2.3 guide over frozen V6.2.2 + Road LTL V1.2'}};
const inp={padding:7,border:'1px solid #ccd8e0',borderRadius:5,fontSize:12};
const card={padding:9,border:'1px solid #e1e8ec',borderRadius:7,margin:'6px 0',fontSize:12};
export default function Home(){
 const frame=useRef(null);const [tab,setTab]=useState('ask'),[q,setQ]=useState(''),[messages,setMessages]=useState([]),[processes,setProcesses]=useState([]),[ws,setWs]=useState(blank),[analysis,setAnalysis]=useState(null),[future,setFuture]=useState(null),[delta,setDelta]=useState([]),[intake,setIntake]=useState(null),[research,setResearch]=useState(null),[admin,setAdmin]=useState(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[panelOpen,setPanelOpen]=useState(true),[caps,setCaps]=useState(null),[lastAtlasSelection,setLastAtlasSelection]=useState(null);
 useEffect(()=>{fetch('/api/capabilities').then(r=>r.json()).then(setCaps).catch(()=>{});fetch('/api/reference').then(r=>r.json()).then(j=>{setProcesses(j.processes||[]);const saved=localStorage.getItem('atlas-client-workspace-v062');if(saved){try{setWs(JSON.parse(saved));return}catch{}}setWs(w=>({...w,reference:{...w.reference,processIds:(j.processes||[]).map(p=>p.id)},asIs:{facts:(j.processes||[]).map(p=>({processId:p.id,status:'REFERENCE_ONLY'}))}}))})},[]);
 useEffect(()=>{localStorage.setItem('atlas-client-workspace-v062',JSON.stringify(ws))},[ws]);
 function bindAtlasClicks(d,scope='Page 0'){if(!d||d.documentElement?.dataset?.atlasIntelligenceBound)return;d.documentElement.dataset.atlasIntelligenceBound='1';const capture=ev=>{const el=ev.target?.closest?.('[data-process],select,button,a,summary,label,[id]')||ev.target;if(!el)return;const text=(el.tagName==='SELECT'?el.selectedOptions?.[0]?.textContent:el.textContent||el.getAttribute?.('aria-label')||'').replace(/\s+/g,' ').trim().slice(0,240);const id=el.dataset?.process||el.id||'';if(text||id)setLastAtlasSelection({text,id,scope})};d.addEventListener('click',capture,true);d.addEventListener('change',capture,true)}
 function wireAtlasClicks(){const d=atlasDoc();bindAtlasClicks(d,'Page 0 / Integrated Atlas');try{const cd=d?.getElementById('atlas-road-ltl-frame')?.contentDocument;bindAtlasClicks(cd,'Road LTL V1.2')}catch{}}
 function atlasDoc(){try{return frame.current?.contentDocument}catch{return null}}
 async function roadDoc(){const d=atlasDoc();if(!d)return null;try{frame.current?.contentWindow?.__ATLAS_INTEGRATION__?.openRoadLTL({updateHash:true})}catch{}for(let i=0;i<20;i++){const f=d.getElementById('atlas-road-ltl-frame'),cd=f?.contentDocument;if(cd?.querySelector('[data-process]')){bindAtlasClicks(cd,'Road LTL V1.2');return cd;}await new Promise(r=>setTimeout(r,80))}return null}
 async function focus(ids=[]){if(!ids.length)return;const d=await roadDoc();if(!d)return;d.querySelectorAll('[data-process]').forEach(el=>{const on=ids.includes(el.dataset.process);el.style.opacity=on?'1':'.18';el.style.filter=on?'none':'grayscale(.9)';el.style.outline=on?'3px solid #12ABDB':''});d.querySelector(`[data-process="${ids[0]}"]`)?.scrollIntoView({behavior:'smooth',block:'center'})}
 function reset(){const d=atlasDoc(),f=d?.getElementById('atlas-road-ltl-frame'),cd=f?.contentDocument;cd?.querySelectorAll('[data-process]').forEach(el=>{el.style.opacity='';el.style.filter='';el.style.outline=''})}
 function currentAtlasContext(){const d=atlasDoc(),w=frame.current?.contentWindow;if(!d)return {};const visible=el=>{try{const r=el.getBoundingClientRect();return r.bottom>0&&r.top<(w?.innerHeight||900)&&r.width>0&&r.height>0}catch{return false}},txt=el=>(el?.textContent||'').replace(/\s+/g,' ').trim();const headings=[...d.querySelectorAll('h1,h2,h3,.eyebrow,.state-location span')].filter(visible).map(txt).filter(Boolean).slice(0,18);const active=[...d.querySelectorAll('#navigation-state-chips *,#active-state-chips *,#analytical-state-chips *')].map(txt).filter(Boolean).slice(0,24);const selected=[...d.querySelectorAll('select')].map(x=>x.selectedOptions?.[0]?.textContent?.trim()).filter(Boolean).slice(0,20);const labels=[...d.querySelectorAll('label,summary,.native-tag')].filter(visible).map(txt).filter(x=>x&&x.length<120).slice(0,30);let child={};try{const f=d.getElementById('atlas-road-ltl-frame'),cd=f?.contentDocument;if(cd){child={open:true,visibleHeadings:[...cd.querySelectorAll('h1,h2,h3,.phase-title,.view-title')].filter(visible).map(txt).filter(Boolean).slice(0,12),selected:[...cd.querySelectorAll('select')].map(x=>x.selectedOptions?.[0]?.textContent?.trim()).filter(Boolean).slice(0,16)}}}catch{}return {lastSelection:lastAtlasSelection,page:txt(d.querySelector('.state-location span'))||d.title,hash:w?.location?.hash||'',visibleHeadings:headings,activeState:active,selectedValues:selected,visibleLabels:labels,roadLtl:child}}
 async function actions(xs=[]){for(const a of xs){if(a.type==='PLAY_EXISTING_FLOW'){for(const id of a.processIds||[]){await focus([id]);await new Promise(r=>setTimeout(r,500))}await focus(a.processIds||[])}else await focus([a.processId,...(a.processIds||[])].filter(Boolean))}}
 async function ask(e){e.preventDefault();if(!q.trim()||busy)return;const text=q.trim();setQ('');setBusy(true);setMessages(m=>[...m,{role:'user',text}]);try{const r=await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:text,context:{workspaceSummary:{client:ws.client},workspaceFacts:ws.asIs.facts,atlasContext:currentAtlasContext()}})}),j=await r.json();setMessages(m=>[...m,{role:'assistant',text:j.answer||j.error,meta:j.meta}]);if(r.ok)await actions(j.uiActions||[])}finally{setBusy(false)}}
 function fact(id,key,val,layer='asIs'){setWs(w=>{const n=structuredClone(w),arr=n[layer].facts;let f=arr.find(x=>x.processId===id);if(!f){f={processId:id,status:'UNKNOWN'};arr.push(f)}f[key]=val;return n})}
 async function analyze(){const r=await fetch('/api/scenario/analyze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(ws)}),j=await r.json();if(r.ok){setAnalysis(j.analysis);setDelta(j.delta);setTab('analyze')}else setNotice(j.error)}
 async function transform(){const r=await fetch('/api/scenario/transform',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(ws)}),j=await r.json();if(r.ok){setFuture(j.futureState);setAnalysis(j.analysis);setTab('transform')}else setNotice(j.error)}
 async function upload(file){const fd=new FormData();fd.append('file',file);fd.append('clientName',ws.client.name);fd.append('existingClaims',JSON.stringify(ws.evidence));const r=await fetch('/api/intake/file',{method:'POST',body:fd}),j=await r.json();setIntake(j);setNotice(j.gate?.decision==='ACCEPT'?'Evidence extracted; review before commit.':j.error||j.gate?.decision||'Review required')}
 function commitClaim(c){setWs(w=>({...w,evidence:[...w.evidence,{...c,humanReviewed:true,approvedAt:new Date().toISOString()}]}));setIntake(x=>x?({...x,claims:(x.claims||[]).filter(y=>y.id!==c.id)}):x)}
 async function doResearch(){if(!ws.client.name)return setNotice('Add client name first.');setResearch(await (await fetch('/api/research',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({clientName:ws.client.name,scope:ws.client.scope})})).json())}
 async function refreshAdmin(){setAdmin(await (await fetch('/api/admin/summary')).json())}
 async function saveWorkspace(){const r=await fetch('/api/workspace',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({workspace:ws})}),j=await r.json();setNotice(j.status==='SAVED'?'Workspace saved to configured Supabase tenant. Frozen Atlas unchanged.':j.message||'Supabase persistence not connected; local draft remains saved in this browser.')}
 async function loadWorkspace(){const r=await fetch('/api/workspace'),j=await r.json();if(j.workspace){setWs(j.workspace);setNotice('Latest workspace loaded from Supabase.')}else setNotice(j.message||'No persisted workspace found.')}
 async function resolveReview(id,status){await fetch('/api/review',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'resolve',id,status})});await refreshAdmin()}
 return <main style={{display:'grid',gridTemplateColumns:panelOpen?'minmax(0,1fr) minmax(360px,460px)':'minmax(0,1fr)',height:'100vh',fontFamily:'Arial,sans-serif',color:'#102a43',position:'relative'}}>
  <iframe ref={frame} onLoad={wireAtlasClicks} src="/atlas.html" title="Frozen Supply Chain & Logistics Atlas" style={{width:'100%',height:'100%',border:0}}/>
  {panelOpen&&<aside style={{borderLeft:'1px solid #d8e0e6',display:'flex',flexDirection:'column',minWidth:0,background:'#fff'}}>
   <header style={{padding:14,borderBottom:'1px solid #e5eaee'}}><div style={{display:'flex',justifyContent:'space-between',gap:8,alignItems:'flex-start'}}><div><b>Atlas Intelligence v0.6.5</b><div style={{fontSize:11,color:'#667784',marginTop:4}}>V6.2.3 GUIDE · FROZEN V6.2.2 + ROAD LTL V1.2 · READ ONLY</div><div style={{fontSize:10,marginTop:5,padding:'3px 6px',display:'inline-block',borderRadius:10,background:caps?.llm?.enabled?'#e5f6ee':'#fff4df',color:caps?.llm?.enabled?'#17643a':'#8a5a00'}}>{caps?.llm?.enabled?`LLM ON · ${caps.llm.provider} · ${caps.llm.model}`:'LLM OFF · deterministic fallback'}</div></div><button aria-label="Minimize Atlas Intelligence" onClick={()=>setPanelOpen(false)} style={{fontSize:11,padding:'5px 8px'}}>Minimize</button></div><div style={{display:'flex',flexWrap:'wrap',gap:4,marginTop:9}}>{[['ask','Explore / Ask'],['evidence','Evidence'],['map','Map Client'],['analyze','Analyze'],['transform','Transform'],['simulate','Simulate'],['admin','Admin']].map(([x,l])=><button key={x} onClick={()=>{setTab(x);if(x==='admin')refreshAdmin()}} style={{fontSize:11,padding:'6px 8px',background:tab===x?'#0a91ae':'#fff',color:tab===x?'#fff':'#234',border:'1px solid #ccd8e0'}}>{l}</button>)}</div><div style={{display:'flex',gap:5,marginTop:7,flexWrap:'wrap'}}><button onClick={()=>frame.current?.contentWindow?.__ATLAS_INTEGRATION__?.openPage0({updateHash:true})}>Page 0</button><button onClick={()=>frame.current?.contentWindow?.__ATLAS_GUIDE_V623__?.open?.()}>How to read Atlas</button><button onClick={reset}>Reset intelligence view</button><button onClick={saveWorkspace}>Save workspace</button><button onClick={loadWorkspace}>Load workspace</button></div>{notice&&<div style={{marginTop:7,padding:7,background:'#fff7e6',fontSize:11}}>{notice}</div>}</header>
   <section style={{padding:14,overflow:'auto',flex:1}}>
    {tab==='ask'&&<div>{messages.length===0&&<p style={{fontSize:13,color:'#667784'}}>Ask what any Atlas term, process, tab, state, source or relationship means. Atlas classifies provenance first; Gemini explains it in simple operational language. Ambiguity triggers clarification instead of guessing.</p>}{messages.map((m,i)=><div key={i} style={{...card,background:m.role==='user'?'#eef6fb':'#f7f9fa'}}><b>{m.role==='user'?'You':'Atlas'}</b><div style={{whiteSpace:'pre-wrap',lineHeight:1.45,marginTop:5}}>{m.text}</div>{m.meta?.agentPath&&<small>Agents: {m.meta.agentPath.join(' → ')}</small>}</div>)}</div>}
    {tab==='evidence'&&<div><h3>Evidence Intake</h3><p style={{fontSize:12}}>RFP/RFI/SOP evidence is screened and previewed. Nothing enters the client workspace until you approve it.</p><input type="file" accept=".pdf,.docx,.txt,.md,.csv,.json,.html,.htm" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/><button onClick={doResearch} style={{marginLeft:6}}>Research client publicly</button>{intake&&<div style={card}><b>Trust gate: {intake.gate?.decision}</b><div>Candidate claims: {intake.claims?.length||0} · Contradictions: {intake.contradictions?.length||0}</div></div>}{(intake?.claims||[]).map(c=><div key={c.id} style={card}><b>{c.status} · {c.processId||c.claimType}</b><div>{c.statement}</div><small>Confidence: {c.confidence}</small><br/><button onClick={()=>commitClaim(c)}>Approve into workspace</button></div>)}{research&&<div style={card}><b>Research: {research.status}</b><div>{research.message}</div></div>}{(research?.claims||[]).map(c=><div key={c.id} style={card}><b>PUBLICLY_EVIDENCED candidate</b><div>{c.statement}</div><small>{c.evidence?.title||c.evidence?.url||''}</small><br/><button onClick={()=>commitClaim(c)}>Approve public evidence into workspace</button></div>)}<h4>Committed evidence</h4>{ws.evidence.map((c,i)=><div key={i} style={card}>{c.status} · {c.processId||''} · {c.statement}</div>)}</div>}
    {tab==='map'&&<div><h3>Map Client AS-IS</h3><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:6}}><input style={inp} placeholder="Client" value={ws.client.name} onChange={e=>setWs(w=>({...w,client:{...w.client,name:e.target.value}}))}/><input style={inp} placeholder="Geography" value={ws.client.geography} onChange={e=>setWs(w=>({...w,client:{...w.client,geography:e.target.value}}))}/></div><button onClick={analyze} style={{margin:'8px 0'}}>Analyze</button>{processes.map(p=>{const f=ws.asIs.facts.find(x=>x.processId===p.id)||{status:'REFERENCE_ONLY'};return <details key={p.id} style={{borderTop:'1px solid #e5eaee',padding:'7px 0'}}><summary onClick={()=>focus([p.id])}><b>{p.id}</b> {p.label} · {f.status}</summary><div style={{display:'grid',gap:5,paddingTop:6}}><select style={inp} value={f.status} onChange={e=>fact(p.id,'status',e.target.value)}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select><input style={inp} placeholder="Client process name" value={f.clientLabel||''} onChange={e=>fact(p.id,'clientLabel',e.target.value)}/><input style={inp} placeholder={`Client system; Atlas class: ${p.authoritySystem||'not mapped'}`} value={f.systemName||''} onChange={e=>fact(p.id,'systemName',e.target.value)}/><input style={inp} placeholder="Evidence reference" value={f.evidenceText||''} onChange={e=>fact(p.id,'evidenceText',e.target.value)}/><input style={inp} placeholder="Manual handoff?" value={f.manualHandoff||''} onChange={e=>fact(p.id,'manualHandoff',e.target.value)}/><input style={inp} placeholder="Re-keying / duplicate entry?" value={f.rekeying||''} onChange={e=>fact(p.id,'rekeying',e.target.value)}/><input style={inp} placeholder="Exception latency?" value={f.exceptionLatency||''} onChange={e=>fact(p.id,'exceptionLatency',e.target.value)}/><input style={inp} placeholder="Control gap?" value={f.controlGap||''} onChange={e=>fact(p.id,'controlGap',e.target.value)}/></div></details>})}</div>}
    {tab==='analyze'&&<div><h3>AS-IS Analysis</h3>{!analysis?<button onClick={analyze}>Analyze workspace</button>:<><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:5}}>{Object.entries(analysis.summary).map(([k,v])=><div key={k} style={card}><b>{v}</b><br/><small>{k}</small></div>)}</div><h4>Potential gaps</h4>{analysis.potentialGaps.map((x,i)=><div key={i} style={card} onClick={()=>focus([x.processId])}>{x.processId} · {x.type} · {x.detail}</div>)}<h4>Discovery questions</h4>{analysis.discoveryQuestions.slice(0,12).map((x,i)=><div key={i} style={card}>{x.processId} · {x.question}</div>)}</>}</div>}
    {tab==='transform'&&<div><h3>TO-BE</h3><button onClick={()=>setWs(w=>({...w,toBe:{facts:structuredClone(w.asIs.facts)}}))}>Start TO-BE from AS-IS</button><button onClick={transform} style={{marginLeft:6}}>Generate advisory patterns</button>{(future?.suggestions||[]).map((x,i)=><div key={i} style={card}><b>{x.processId} · {x.label}</b><div>{x.pattern}</div><div>{x.proposal}</div></div>)}</div>}
    {tab==='simulate'&&<div><h3>AS-IS ↔ TO-BE Delta</h3><button onClick={analyze}>Refresh delta</button>{delta.map((d,i)=><div key={i} style={card} onClick={()=>focus([d.processId])}><b>{d.processId} · {d.label}</b><span style={{float:'right'}}>{d.change}</span></div>)}</div>}
    {tab==='admin'&&<div><h3>Admin & Human Review</h3><button onClick={refreshAdmin}>Refresh</button>{admin&&<><div style={card}>Runtime v{admin.capabilities?.version} · LLM {admin.capabilities?.llm?.enabled?'connected':'fallback'} · Supabase {admin.capabilities?.supabase?.enabled?'connected':'not connected'}</div><div style={card}>Events: {admin.telemetry?.events||0} · Open reviews: {admin.reviews?.open||0}</div>{(admin.reviews?.items||[]).map((x,i)=><div key={x.id||i} style={card}><b>{x.status} · {x.type}</b><div>{x.summary}</div>{x.status==='OPEN'&&<div style={{display:'flex',gap:4,flexWrap:'wrap',marginTop:5}}>{['APPROVED','REJECTED','NEEDS_EVIDENCE','UNRESOLVED'].map(st=><button key={st} onClick={()=>resolveReview(x.id,st)}>{st}</button>)}</div>}</div>)}</>}</div>}
   </section>
   {tab==='ask'&&<form onSubmit={ask} style={{padding:12,borderTop:'1px solid #e5eaee',display:'flex',gap:7}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Ask Atlas…" style={{...inp,flex:1}}/><button disabled={busy}>{busy?'…':'Ask'}</button></form>}
  </aside>}
  {!panelOpen&&<button onClick={()=>setPanelOpen(true)} aria-label="Open Atlas Intelligence" style={{position:'fixed',right:14,top:14,zIndex:9999,padding:'9px 12px',borderRadius:18,border:'1px solid #0a91ae',background:'#fff',color:'#07566b',fontWeight:700,boxShadow:'0 4px 16px rgba(0,0,0,.16)'}}>Ask Atlas</button>}
 </main>
}
