'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import SimulationStudio from './components/SimulationStudio.js';

const STATUSES=['CONFIRMED','OBSERVED','PUBLICLY_EVIDENCED','INFERRED','REFERENCE_ONLY','UNKNOWN'];
const blank={id:'local',client:{name:'',geography:'',scope:'Road LTL',notes:''},reference:{mode:'road-ltl',processIds:[]},asIs:{facts:[]},toBe:{facts:[]},evidence:[],metadata:{status:'DRAFT',atlasVersion:'V6.2.3 guide over frozen V6.2.2 + Road LTL V1.2',intelligenceVersion:'0.6.6'}};
const inp={padding:7,border:'1px solid #ccd8e0',borderRadius:5,fontSize:12};
const card={padding:9,border:'1px solid #e1e8ec',borderRadius:7,margin:'6px 0',fontSize:12};
const btn={border:'1px solid #c7d4da',background:'#fff',borderRadius:5,padding:'6px 8px',fontSize:11,cursor:'pointer'};
const PREF='atlas-v066-presentation';
function compactText(v=''){return String(v||'').replace(/\s+/g,' ').trim()}

export default function Home(){
  const frame=useRef(null);
  const [tab,setTab]=useState('ask'),[q,setQ]=useState(''),[messages,setMessages]=useState([]),[processes,setProcesses]=useState([]),[ws,setWs]=useState(blank),[analysis,setAnalysis]=useState(null),[future,setFuture]=useState(null),[delta,setDelta]=useState([]),[intake,setIntake]=useState(null),[research,setResearch]=useState(null),[admin,setAdmin]=useState(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[panelOpen,setPanelOpen]=useState(true),[caps,setCaps]=useState(null),[lastAtlasSelection,setLastAtlasSelection]=useState(null),[constitution,setConstitution]=useState(null);
  const [displayMode,setDisplayMode]=useState('work'),[collapsePrefs,setCollapsePrefs]=useState({sourceModels:true,crosswalk:true,navigator:true}),[contextCompacted,setContextCompacted]=useState(false),[contextSnapshot,setContextSnapshot]=useState({ribbon:['Neutral ecosystem'],selectIds:{},activeState:[]});
  const [studioOpen,setStudioOpen]=useState(false),[simulation,setSimulation]=useState(null),[simLoading,setSimLoading]=useState(false),[simError,setSimError]=useState(''),[simView,setSimView]=useState('Journey'),[activeIndex,setActiveIndex]=useState(0),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1000),[flowLayers,setFlowLayers]=useState({physical:true,information:true,financial:true,controls:true,evidence:true}),[selectedHandoffId,setSelectedHandoffId]=useState(''),[twinLayer,setTwinLayer]=useState('REFERENCE'),[branchPreview,setBranchPreview]=useState(null);

  useEffect(()=>{
    try{const p=JSON.parse(localStorage.getItem(PREF)||'{}');if(p.displayMode)setDisplayMode(p.displayMode);if(p.collapsePrefs)setCollapsePrefs(x=>({...x,...p.collapsePrefs}));if(typeof p.contextCompacted==='boolean')setContextCompacted(p.contextCompacted);if(typeof p.panelOpen==='boolean')setPanelOpen(p.panelOpen);if(p.speed)setSpeed(p.speed);if(p.flowLayers)setFlowLayers(x=>({...x,...p.flowLayers}))}catch{}
    fetch('/api/capabilities').then(r=>r.json()).then(setCaps).catch(()=>{});fetch('/api/constitution?full=1').then(r=>r.json()).then(setConstitution).catch(()=>{});
    fetch('/api/reference').then(r=>r.json()).then(j=>{setProcesses(j.processes||[]);const saved=localStorage.getItem('atlas-client-workspace-v062');if(saved){try{setWs(JSON.parse(saved));return}catch{}}setWs(w=>({...w,reference:{...w.reference,processIds:(j.processes||[]).map(p=>p.id)},asIs:{facts:(j.processes||[]).map(p=>({processId:p.id,status:'REFERENCE_ONLY'}))}}))}).catch(()=>{});
  },[]);
  useEffect(()=>{localStorage.setItem('atlas-client-workspace-v062',JSON.stringify(ws))},[ws]);
  useEffect(()=>{try{localStorage.setItem(PREF,JSON.stringify({displayMode,collapsePrefs,contextCompacted,panelOpen,speed,flowLayers}))}catch{}},[displayMode,collapsePrefs,contextCompacted,panelOpen,speed,flowLayers]);
  useEffect(()=>{if(!playing||!simulation?.standardJourney?.length)return;const timer=setTimeout(()=>setActiveIndex(i=>{if(i>=simulation.standardJourney.length-1){setPlaying(false);return i}return i+1}),speed);return()=>clearTimeout(timer)},[playing,activeIndex,speed,simulation]);

  function emitTelemetry(event_type,metadata={}){try{fetch('/api/telemetry',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({event_type,metadata}),keepalive:true}).catch(()=>{})}catch{}}
  function showContextHelp(term){const row=(constitution?.contextDimensions||[]).find(x=>x[0]===term);setPanelOpen(true);setTab('ask');setNotice(row?`${row[0]} — ${row[1]}. In real life: ${row[2]}`:`${term}: open How to read Atlas for the governed definition.`)}
  function atlasDoc(){try{return frame.current?.contentDocument}catch{return null}}
  function selectedInfo(d,id,key){const x=d?.getElementById(id),o=x?.selectedOptions?.[0];return x?{id:x.value||'',label:compactText(o?.textContent),key}:null}
  function readContext(){
    const d=atlasDoc();if(!d)return contextSnapshot;
    const selectIds={};for(const [id,key] of [['mode-select','mode'],['model-select','role'],['movement-pattern-select','movement'],['node-select','node'],['contract-service-select','contract']]){const v=selectedInfo(d,id,key);if(v)selectIds[key]=v}
    const legal=[...d.querySelectorAll('#selected-context-chips [data-remove-context]')].map(el=>{const c=el.cloneNode(true);c.querySelectorAll('small,span').forEach(x=>x.remove());return {id:el.dataset.removeContext,label:compactText(c.textContent)}});
    const activeState=[...d.querySelectorAll('#active-state-chips .statechip')].map(x=>compactText(x.textContent)).filter(Boolean);
    const ribbon=[];const add=x=>{if(x&&!/^(No |Neutral|Add context)/i.test(x)&&!ribbon.includes(x))ribbon.push(x)};
    add(selectIds.mode?.id!=='none'?selectIds.mode?.label:'');add(selectIds.role?.id!=='neutral'?selectIds.role?.label:'');add(selectIds.movement?.id!=='none'?selectIds.movement?.label:'');add(selectIds.node?.id!=='none'?selectIds.node?.label:'');legal.forEach(x=>add(x.label));add(selectIds.contract?.id!=='contract-unresolved'?selectIds.contract?.label:'');
    let childOpen=false;try{const f=d.getElementById('atlas-road-ltl-frame');childOpen=!!(f?.contentDocument?.querySelector('[data-process]')&&d.defaultView?.getComputedStyle(f)?.display!=='none')}catch{}
    const snap={selectIds,legal,activeState,ribbon:ribbon.length?ribbon:['Neutral ecosystem'],roadLtlOpen:childOpen};setContextSnapshot(prev=>JSON.stringify(prev)===JSON.stringify(snap)?prev:snap);return snap
  }
  function bindAtlasClicks(d,scope='Page 0'){
    if(!d)return;if(d.documentElement?.dataset?.atlasIntelligenceBoundV066)return;d.documentElement.dataset.atlasIntelligenceBoundV066='1';
    const capture=ev=>{const el=ev.target?.closest?.('[data-process],select,button,a,summary,label,[id]')||ev.target;if(!el)return;const text=(el.tagName==='SELECT'?el.selectedOptions?.[0]?.textContent:el.textContent||el.getAttribute?.('aria-label')||'').replace(/\s+/g,' ').trim().slice(0,240);const id=el.dataset?.process||el.dataset?.removeContext||el.id||'';if(text||id)setLastAtlasSelection({text,id,scope});setTimeout(()=>{readContext();applyAtlasPresentation()},40)};d.addEventListener('click',capture,true);d.addEventListener('change',capture,true)
  }
  function applyAtlasPresentation(){
    const d=atlasDoc();if(!d)return;
    let style=d.getElementById('atlas-v066-runtime-style');if(!style){style=d.createElement('style');style.id='atlas-v066-runtime-style';style.textContent=`.atlas-v066-hidden{display:none!important}.atlas-v066-tools{margin-left:auto;display:flex;gap:6px;align-items:center}.atlas-v066-toggle{border:1px solid #b9cbd3;background:#fff;border-radius:999px;padding:5px 9px;font:700 11px Arial;cursor:pointer;color:#0b6075}.atlas-v066-summary{font:600 12px Arial;color:#526b77;margin-top:3px}.atlas-v066-collapsed-head{padding-top:14px!important;padding-bottom:14px!important}.atlas-v066-collapsed-head h2,.atlas-v066-collapsed-head h3,.atlas-v066-collapsed-head p,.atlas-v066-collapsed-head>.native-tag{display:none!important}`;d.head.appendChild(style)}
    const setup=(key,header,bodies,summary)=>{if(!header)return;let tools=header.querySelector(':scope > .atlas-v066-tools');if(!tools){tools=d.createElement('div');tools.className='atlas-v066-tools';const summaryEl=d.createElement('span');summaryEl.className='atlas-v066-summary';summaryEl.textContent=summary;const button=d.createElement('button');button.type='button';button.className='atlas-v066-toggle';tools.append(summaryEl,button);header.appendChild(tools)}const collapsed=displayMode==='work'&&collapsePrefs[key]!==false;bodies.filter(Boolean).forEach(el=>el.classList.toggle('atlas-v066-hidden',collapsed));header.classList.toggle('atlas-v066-collapsed-head',collapsed);const button=tools.querySelector('button');button.textContent=displayMode==='learn'?'Learn mode · expanded':collapsed?'Expand':'Collapse';button.disabled=displayMode==='learn';button.onclick=e=>{e.preventDefault();e.stopPropagation();setCollapsePrefs(p=>({...p,[key]:!collapsed}))}}
    const ref=d.getElementById('reference');if(ref){const children=[...ref.children],heads=children.filter(x=>x.classList?.contains('section-head')),first=heads[0],cross=heads.find(h=>/directional mapping/i.test(h.querySelector('.eyebrow')?.textContent||''));const ci=cross?children.indexOf(cross):-1;setup('sourceModels',first,children.slice(children.indexOf(first)+1,ci<0?children.length:ci),'SCOR · APQC · Atlas crosswalk');if(cross)setup('crosswalk',cross,children.slice(ci+1),'Canonical ↔ source-native crosswalk')}
    const nav=d.getElementById('navigator');if(nav){const children=[...nav.children],head=children.find(x=>x.classList?.contains('section-head'));setup('navigator',head,children.filter(x=>x!==head),'71 planned destinations · expand when needed')}
    const helpMap={'mode-select':'Mode / Service','model-select':'Operating role','movement-pattern-select':'Movement pattern','node-select':'Node','contract-service-select':'Contract / service context','context-add-select':'Jurisdiction'};for(const [selectId,term] of Object.entries(helpMap)){const label=d.querySelector(`label[for="${selectId}"]`);if(!label||label.querySelector('.atlas-v066-help'))continue;const h=d.createElement('button');h.type='button';h.className='atlas-v066-help atlas-v066-toggle';h.textContent='ⓘ';h.title=`Explain ${term}`;h.setAttribute('aria-label',`Explain ${term}`);h.style.marginLeft='5px';h.onclick=e=>{e.preventDefault();e.stopPropagation();showContextHelp(term)};label.appendChild(h)}
    const overview=d.getElementById('overview');if(overview)overview.classList.toggle('atlas-v066-hidden',displayMode==='work'&&contextCompacted);
  }
  function wireAtlasClicks(){const d=atlasDoc();bindAtlasClicks(d,'Page 0 / Integrated Atlas');setTimeout(()=>{readContext();applyAtlasPresentation();try{const cd=d?.getElementById('atlas-road-ltl-frame')?.contentDocument;bindAtlasClicks(cd,'Road LTL V1.2')}catch{}},120)}
  useEffect(()=>{applyAtlasPresentation()},[displayMode,collapsePrefs,contextCompacted,constitution]);

  async function roadDoc(){const d=atlasDoc();if(!d)return null;try{frame.current?.contentWindow?.__ATLAS_INTEGRATION__?.openRoadLTL({updateHash:true})}catch{}for(let i=0;i<25;i++){const f=d.getElementById('atlas-road-ltl-frame'),cd=f?.contentDocument;if(cd?.querySelector('[data-process]')){bindAtlasClicks(cd,'Road LTL V1.2');setContextSnapshot(s=>({...s,roadLtlOpen:true}));return cd}await new Promise(r=>setTimeout(r,80))}return null}
  async function focus(ids=[]){if(!ids.length)return;const d=await roadDoc();if(!d)return;d.querySelectorAll('[data-process]').forEach(el=>{const on=ids.includes(el.dataset.process);el.style.opacity=on?'1':'.18';el.style.filter=on?'none':'grayscale(.9)';el.style.outline=on?'3px solid #12ABDB':''});d.querySelector(`[data-process="${ids[0]}"]`)?.scrollIntoView({behavior:'smooth',block:'center'})}
  function reset(){const d=atlasDoc(),f=d?.getElementById('atlas-road-ltl-frame'),cd=f?.contentDocument;cd?.querySelectorAll('[data-process]').forEach(el=>{el.style.opacity='';el.style.filter='';el.style.outline=''})}
  function currentAtlasContext(){
    const d=atlasDoc(),w=frame.current?.contentWindow;if(!d)return {lastSelection:lastAtlasSelection,...contextSnapshot};const visible=el=>{try{const r=el.getBoundingClientRect();return r.bottom>0&&r.top<(w?.innerHeight||900)&&r.width>0&&r.height>0}catch{return false}},txt=el=>compactText(el?.textContent);const headings=[...d.querySelectorAll('h1,h2,h3,.eyebrow,.state-location span')].filter(visible).map(txt).filter(Boolean).slice(0,18);const active=[...d.querySelectorAll('#navigation-state-chips *,#active-state-chips *,#analytical-state-chips *')].map(txt).filter(Boolean).slice(0,24);const selected=[...d.querySelectorAll('select')].map(x=>x.selectedOptions?.[0]?.textContent?.trim()).filter(Boolean).slice(0,20);const labels=[...d.querySelectorAll('label,summary,.native-tag')].filter(visible).map(txt).filter(x=>x&&x.length<120).slice(0,30);let child={open:false};try{const f=d.getElementById('atlas-road-ltl-frame'),cd=f?.contentDocument;if(cd?.querySelector('[data-process]'))child={open:true,visibleHeadings:[...cd.querySelectorAll('h1,h2,h3,.phase-title,.view-title')].filter(visible).map(txt).filter(Boolean).slice(0,12),selected:[...cd.querySelectorAll('select')].map(x=>x.selectedOptions?.[0]?.textContent?.trim()).filter(Boolean).slice(0,16)}}catch{}return {lastSelection:lastAtlasSelection,page:child.open?'Road LTL V1.2':txt(d.querySelector('.state-location span'))||d.title,hash:w?.location?.hash||'',visibleHeadings:headings,activeState:active,selectedValues:selected,visibleLabels:labels,roadLtl:child,selectIds:contextSnapshot.selectIds,legal:contextSnapshot.legal,ribbon:contextSnapshot.ribbon}
  }
  const simulationContext=useCallback(()=>{if(!simulation)return {open:studioOpen};const steps=simulation.standardJourney||[],step=steps[activeIndex]||null,next=steps[activeIndex+1]||null,handoff=(simulation.allHandoffs||[]).find(h=>h.edge.id===selectedHandoffId)||simulation.standardHandoffs?.[Math.min(activeIndex,(simulation.standardHandoffs?.length||1)-1)]||null;const nextRel=step&&next?(step.relationships?.outgoing||[]).find(x=>x.to===next.id&&x.type==='PRECEDES'):null;return {open:studioOpen,view:simView,activeIndex,activeStep:branchPreview?.step||step,nextStep:next,nextRelationship:nextRel,selectedHandoff:branchPreview?.handoff||handoff,flowLayers,twinLayer}},[simulation,studioOpen,simView,activeIndex,selectedHandoffId,branchPreview,flowLayers,twinLayer]);
  async function refreshSimulation(){setSimLoading(true);setSimError('');try{const r=await fetch('/api/simulation',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({context:currentAtlasContext(),workspace:ws})}),j=await r.json();if(!r.ok)throw new Error(j.error||'Simulation failed');setSimulation(j);setActiveIndex(i=>Math.min(i,Math.max(0,(j.standardJourney?.length||1)-1)));setSelectedHandoffId(j.standardHandoffs?.[0]?.edge?.id||'')}catch(e){setSimError(String(e.message||e))}finally{setSimLoading(false)}}
  useEffect(()=>{if(studioOpen&&!simulation&&!simLoading)refreshSimulation()},[studioOpen]);
  useEffect(()=>{if(!studioOpen||!simulation||simLoading)return;const t=setTimeout(()=>refreshSimulation(),180);return()=>clearTimeout(t)},[contextSnapshot]);

  async function actions(xs=[]){for(const a of xs){if(a.type==='OPEN_SIMULATION'){setStudioOpen(true);if(!simulation)await refreshSimulation()}else if(a.type==='SIMULATION_PLAY'){setStudioOpen(true);setPlaying(true)}else if(a.type==='SIMULATION_PAUSE')setPlaying(false);else if(a.type==='SIMULATION_RESET'){setPlaying(false);setActiveIndex(0)}else if(a.type==='SIMULATION_STEP')setActiveIndex(i=>a.direction==='PREVIOUS'?Math.max(0,i-1):Math.min((simulation?.standardJourney?.length||1)-1,i+1));else if(a.type==='SET_FLOW_LAYER'&&a.layer)setFlowLayers(x=>({...x,[a.layer]:a.enabled!==false}));else if(a.type==='SELECT_HANDOFF'&&a.edgeId){setSelectedHandoffId(a.edgeId);setStudioOpen(true)}else if(a.type==='PLAY_EXISTING_FLOW'){setStudioOpen(true);for(const id of a.processIds||[]){const i=simulation?.standardJourney?.findIndex(x=>x.id===id)??-1;if(i>=0){setActiveIndex(i);await new Promise(r=>setTimeout(r,250))}}}else await focus([a.processId,...(a.processIds||[])].filter(Boolean))}}
  async function ask(e){e.preventDefault();if(!q.trim()||busy)return;const text=q.trim();setQ('');setBusy(true);setMessages(m=>[...m,{role:'user',text}]);try{const r=await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:text,context:{workspaceSummary:{client:ws.client},workspaceFacts:ws.asIs.facts,atlasContext:{...currentAtlasContext(),simulationContext:simulationContext()},simulationContext:simulationContext()}})}),j=await r.json();setMessages(m=>[...m,{role:'assistant',text:j.answer||j.error,meta:j.meta}]);if(r.ok)await actions(j.uiActions||[])}finally{setBusy(false)}}

  function fact(id,key,val,layer='asIs'){setWs(w=>{const n=structuredClone(w),arr=n[layer].facts;let f=arr.find(x=>x.processId===id);if(!f){f={processId:id,status:'UNKNOWN'};arr.push(f)}f[key]=val;return n})}
  async function analyze(){const r=await fetch('/api/scenario/analyze',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(ws)}),j=await r.json();if(r.ok){setAnalysis(j.analysis);setDelta(j.delta);setTab('analyze')}else setNotice(j.error)}
  async function transform(){const r=await fetch('/api/scenario/transform',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(ws)}),j=await r.json();if(r.ok){setFuture(j.futureState);setAnalysis(j.analysis);setTab('transform')}else setNotice(j.error)}
  async function upload(file){const fd=new FormData();fd.append('file',file);fd.append('clientName',ws.client.name);fd.append('existingClaims',JSON.stringify(ws.evidence));const r=await fetch('/api/intake/file',{method:'POST',body:fd}),j=await r.json();setIntake(j);setNotice(j.gate?.decision==='ACCEPT'?'Evidence extracted; review before commit.':j.error||j.gate?.decision||'Review required')}
  function commitClaim(c){setWs(w=>({...w,evidence:[...w.evidence,{...c,humanReviewed:true,approvedAt:new Date().toISOString()}]}));setIntake(x=>x?({...x,claims:(x.claims||[]).filter(y=>y.id!==c.id)}):x)}
  async function doResearch(){if(!ws.client.name)return setNotice('Add client name first.');setResearch(await (await fetch('/api/research',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({clientName:ws.client.name,scope:ws.client.scope})})).json())}
  async function refreshAdmin(){setAdmin(await (await fetch('/api/admin/summary')).json())}
  async function saveWorkspace(){const r=await fetch('/api/workspace',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({workspace:ws})}),j=await r.json();setNotice(j.status==='SAVED'?'Workspace saved to configured Supabase tenant. Frozen Atlas unchanged.':j.message||'Supabase persistence not connected; local draft remains saved in this browser.')}
  async function loadWorkspace(){const r=await fetch('/api/workspace'),j=await r.json();if(j.workspace){setWs(j.workspace);setNotice('Latest workspace loaded from Supabase.')}else setNotice(j.message||'No persisted workspace found.')}
  async function resolveReview(id,status){await fetch('/api/review',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'resolve',id,status})});await refreshAdmin()}
  function editContext(){emitTelemetry('CONTEXT_EDITED',{});setStudioOpen(false);setContextCompacted(false);try{frame.current?.contentWindow?.__ATLAS_INTEGRATION__?.openPage0({updateHash:true})}catch{}setTimeout(()=>{applyAtlasPresentation();atlasDoc()?.getElementById('overview')?.scrollIntoView({behavior:'smooth',block:'start'})},80)}
  function compactContext(){emitTelemetry('CONTEXT_COMPACTED',{});readContext();setContextCompacted(true);setTimeout(applyAtlasPresentation,20)}

  const ribbon=contextSnapshot.ribbon?.length?contextSnapshot.ribbon:['Neutral ecosystem'];
  return <main className="atlas-shell" style={{display:'grid',gridTemplateColumns:panelOpen?'minmax(0,1fr) minmax(360px,460px)':'minmax(0,1fr)',height:'100vh',fontFamily:'Arial,sans-serif',color:'#102a43',position:'relative'}}>
    <style>{`*{box-sizing:border-box}@media(max-width:900px){.atlas-shell{grid-template-columns:1fr!important}.atlas-intelligence{position:fixed!important;inset:20% 0 0 0!important;z-index:9998!important;box-shadow:0 -8px 28px rgba(0,0,0,.18)}}`}</style>
    <div style={{display:'flex',flexDirection:'column',height:'100%',minWidth:0,background:'#fff'}}>
      <div style={{padding:'7px 10px',borderBottom:'1px solid #d7e1e6',background:'#fbfdfe',display:'flex',gap:8,alignItems:'center',flexWrap:'wrap',minHeight:45}}>
        <div style={{display:'flex',gap:3,border:'1px solid #cbd8de',borderRadius:7,padding:2}}>{['work','learn'].map(m=><button key={m} onClick={()=>{setDisplayMode(m);emitTelemetry('DISPLAY_MODE_CHANGED',{mode:m})}} style={{...btn,border:0,background:displayMode===m?'#0a7890':'transparent',color:displayMode===m?'#fff':'#345',fontWeight:700}}>{m==='work'?'Work':'Learn'}</button>)}</div>
        <div style={{display:'flex',gap:4,alignItems:'center',flex:1,minWidth:200,overflowX:'auto'}}><b style={{fontSize:10,whiteSpace:'nowrap',color:'#5c737f'}}>ACTIVE CONTEXT</b>{ribbon.map(x=><span key={x} style={{fontSize:10,padding:'4px 7px',borderRadius:999,border:'1px solid #d5e1e6',whiteSpace:'nowrap',background:'#fff'}}>{x}</span>)}</div>
        {contextCompacted?<button style={btn} onClick={editContext}>Edit context</button>:<button style={btn} onClick={compactContext}>Apply & collapse context</button>}
        <button style={{...btn,fontWeight:800,background:studioOpen?'#e8f8fb':'#fff'}} onClick={()=>{setStudioOpen(x=>!x);if(!studioOpen&&!simulation)refreshSimulation()}}>{studioOpen?'Atlas view':'Simulation Studio'}</button>
      </div>
      <div style={{flex:1,minHeight:0}}>{studioOpen?<SimulationStudio simulation={simulation} loading={simLoading} error={simError} activeIndex={activeIndex} setActiveIndex={setActiveIndex} playing={playing} setPlaying={setPlaying} speed={speed} setSpeed={setSpeed} view={simView} setView={setSimView} flowLayers={flowLayers} setFlowLayers={setFlowLayers} selectedHandoffId={selectedHandoffId} setSelectedHandoffId={setSelectedHandoffId} twinLayer={twinLayer} setTwinLayer={setTwinLayer} branchPreview={branchPreview} setBranchPreview={setBranchPreview} onRefresh={refreshSimulation} onBack={()=>setStudioOpen(false)} onFocusProcess={()=>{}} onEvent={emitTelemetry}/>:<iframe ref={frame} onLoad={wireAtlasClicks} src="/atlas.html" title="Supply Chain & Logistics Atlas V6.2.3" style={{width:'100%',height:'100%',border:0}}/>}</div>
    </div>
    {panelOpen&&<aside className="atlas-intelligence" style={{borderLeft:'1px solid #d8e0e6',display:'flex',flexDirection:'column',minWidth:0,background:'#fff'}}>
      <header style={{padding:12,borderBottom:'1px solid #e5eaee'}}><div style={{display:'flex',justifyContent:'space-between',gap:8,alignItems:'flex-start'}}><div><b>Atlas Intelligence v0.6.6</b><div style={{fontSize:10,color:'#667784',marginTop:4}}>V6.2.3 GUIDE · FROZEN V6.2.2 + ROAD LTL V1.2 · READ ONLY</div><div style={{fontSize:10,marginTop:5,padding:'3px 6px',display:'inline-block',borderRadius:10,background:caps?.llm?.enabled?'#e5f6ee':'#fff4df',color:caps?.llm?.enabled?'#17643a':'#8a5a00'}}>{caps?.llm?.enabled?`LLM ON · ${caps.llm.provider} · ${caps.llm.model}`:'LLM OFF · deterministic fallback'}</div></div><button aria-label="Minimize Atlas Intelligence" onClick={()=>setPanelOpen(false)} style={btn}>Minimize</button></div>
        <div style={{display:'flex',flexWrap:'wrap',gap:4,marginTop:9}}>{[['ask','Explore / Ask'],['evidence','Evidence'],['map','Map Client'],['analyze','Analyze'],['transform','Transform'],['delta','Delta'],['admin','Admin']].map(([x,l])=><button key={x} onClick={()=>{setTab(x);if(x==='admin')refreshAdmin()}} style={{...btn,background:tab===x?'#0a91ae':'#fff',color:tab===x?'#fff':'#234'}}>{l}</button>)}<button style={{...btn,background:studioOpen?'#0a91ae':'#fff',color:studioOpen?'#fff':'#234'}} onClick={()=>{setStudioOpen(true);if(!simulation)refreshSimulation()}}>Simulation</button></div>
        <div style={{display:'flex',gap:5,marginTop:7,flexWrap:'wrap'}}><button style={btn} onClick={()=>{setStudioOpen(false);frame.current?.contentWindow?.__ATLAS_INTEGRATION__?.openPage0({updateHash:true})}}>Page 0</button><button style={btn} onClick={()=>{setStudioOpen(false);frame.current?.contentWindow?.__ATLAS_GUIDE_V623__?.open?.()}}>How to read Atlas</button><button style={btn} onClick={reset}>Reset view</button><button style={btn} onClick={saveWorkspace}>Save workspace</button><button style={btn} onClick={loadWorkspace}>Load workspace</button></div>{notice&&<div style={{marginTop:7,padding:7,background:'#fff7e6',fontSize:11}}>{notice}</div>}</header>
      <section style={{padding:12,overflow:'auto',flex:1}}>
        {tab==='ask'&&<div>{messages.length===0&&<p style={{fontSize:12,color:'#667784'}}>Ask about the current page, process, handoff, data exchange, risk, source or simulation state. Classification and paths remain deterministic; Gemini explains the grounded context in normal language.</p>}{messages.map((m,i)=><div key={i} style={{...card,background:m.role==='user'?'#eef6fb':'#f7f9fa'}}><b>{m.role==='user'?'You':'Atlas'}</b><div style={{whiteSpace:'pre-wrap',lineHeight:1.45,marginTop:5}}>{m.text}</div>{m.meta?.agentPath&&<small>Agents: {m.meta.agentPath.join(' → ')} · Intent: {m.meta.primaryIntent||'general'}</small>}</div>)}</div>}
        {tab==='evidence'&&<div><h3>Evidence Intake</h3><p style={{fontSize:12}}>RFP/RFI/SOP evidence is screened with the Evidence Intake Trust Gate and previewed. Nothing enters the client workspace until you approve it.</p><input type="file" accept=".pdf,.docx,.txt,.md,.csv,.json,.html,.htm" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/><button onClick={doResearch} style={{...btn,marginLeft:6}}>Research client publicly</button>{intake&&<div style={card}><b>Trust gate: {intake.gate?.decision}</b><div>Candidate claims: {intake.claims?.length||0} · Contradictions: {intake.contradictions?.length||0}</div></div>}{(intake?.claims||[]).map(c=><div key={c.id} style={card}><b>{c.status} · {c.processId||c.claimType}</b><div>{c.statement}</div><small>Confidence: {c.confidence}</small><br/><button style={btn} onClick={()=>commitClaim(c)}>Approve into workspace</button></div>)}{research&&<div style={card}><b>Research: {research.status}</b><div>{research.message}</div></div>}{(research?.claims||[]).map(c=><div key={c.id} style={card}><b>PUBLICLY_EVIDENCED candidate</b><div>{c.statement}</div><small>{c.evidence?.title||c.evidence?.url||''}</small><br/><button style={btn} onClick={()=>commitClaim(c)}>Approve public evidence</button></div>)}<h4>Committed evidence</h4>{ws.evidence.map((c,i)=><div key={i} style={card}>{c.status} · {c.processId||''} · {c.statement}</div>)}</div>}
        {tab==='map'&&<div><h3>Map Client AS-IS</h3><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:6}}><input style={inp} placeholder="Client" value={ws.client.name} onChange={e=>setWs(w=>({...w,client:{...w.client,name:e.target.value}}))}/><input style={inp} placeholder="Geography" value={ws.client.geography} onChange={e=>setWs(w=>({...w,client:{...w.client,geography:e.target.value}}))}/></div><button onClick={analyze} style={{...btn,margin:'8px 0'}}>Analyze</button>{processes.map(p=>{const f=ws.asIs.facts.find(x=>x.processId===p.id)||{status:'REFERENCE_ONLY'};return <details key={p.id} style={{borderTop:'1px solid #e5eaee',padding:'7px 0'}}><summary onClick={()=>focus([p.id])}><b>{p.id}</b> {p.label} · {f.status}</summary><div style={{display:'grid',gap:5,paddingTop:6}}><select style={inp} value={f.status} onChange={e=>fact(p.id,'status',e.target.value)}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select><input style={inp} placeholder="Client process name" value={f.clientLabel||''} onChange={e=>fact(p.id,'clientLabel',e.target.value)}/><input style={inp} placeholder={`Client system; Atlas class: ${p.authoritySystem||'not mapped'}`} value={f.systemName||''} onChange={e=>fact(p.id,'systemName',e.target.value)}/><input style={inp} placeholder="Evidence reference" value={f.evidenceText||''} onChange={e=>fact(p.id,'evidenceText',e.target.value)}/><input style={inp} placeholder="Manual handoff?" value={f.manualHandoff||''} onChange={e=>fact(p.id,'manualHandoff',e.target.value)}/><input style={inp} placeholder="Re-keying / duplicate entry?" value={f.rekeying||''} onChange={e=>fact(p.id,'rekeying',e.target.value)}/><input style={inp} placeholder="Exception latency?" value={f.exceptionLatency||''} onChange={e=>fact(p.id,'exceptionLatency',e.target.value)}/><input style={inp} placeholder="Control gap?" value={f.controlGap||''} onChange={e=>fact(p.id,'controlGap',e.target.value)}/></div></details>})}</div>}
        {tab==='analyze'&&<div><h3>AS-IS Analysis</h3>{!analysis?<button style={btn} onClick={analyze}>Analyze workspace</button>:<><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:5}}>{Object.entries(analysis.summary).map(([k,v])=><div key={k} style={card}><b>{v}</b><br/><small>{k}</small></div>)}</div><h4>Potential gaps</h4>{analysis.potentialGaps.map((x,i)=><div key={i} style={card} onClick={()=>focus([x.processId])}>{x.processId} · {x.type} · {x.detail}</div>)}<h4>Discovery questions</h4>{analysis.discoveryQuestions.slice(0,12).map((x,i)=><div key={i} style={card}>{x.processId} · {x.question}</div>)}</>}</div>}
        {tab==='transform'&&<div><h3>TO-BE</h3><button style={btn} onClick={()=>setWs(w=>({...w,toBe:{facts:structuredClone(w.asIs.facts)}}))}>Start TO-BE from AS-IS</button><button style={{...btn,marginLeft:6}} onClick={transform}>Generate advisory patterns</button>{(future?.suggestions||[]).map((x,i)=><div key={i} style={card}><b>{x.processId} · {x.label}</b><div>{x.pattern}</div><div>{x.proposal}</div></div>)}</div>}
        {tab==='delta'&&<div><h3>AS-IS ↔ TO-BE Delta</h3><p style={{fontSize:11}}>A difference from the Atlas reference is not automatically a gap.</p><button style={btn} onClick={analyze}>Refresh delta</button>{delta.map((d,i)=><div key={i} style={card} onClick={()=>focus([d.processId])}><b>{d.processId} · {d.label}</b><span style={{float:'right'}}>{d.change}</span></div>)}</div>}
        {tab==='admin'&&<div><h3>Admin & Human Review</h3><button style={btn} onClick={refreshAdmin}>Refresh</button>{admin&&<><div style={card}>Runtime v{admin.capabilities?.version} · LLM {admin.capabilities?.llm?.enabled?'connected':'fallback'} · Supabase {admin.capabilities?.supabase?.enabled?'connected':'not connected'}</div><div style={card}>Events: {admin.telemetry?.events||0} · Open reviews: {admin.reviews?.open||0}</div>{(admin.reviews?.items||[]).map((x,i)=><div key={x.id||i} style={card}><b>{x.status} · {x.type}</b><div>{x.summary}</div>{x.status==='OPEN'&&<div style={{display:'flex',gap:4,flexWrap:'wrap',marginTop:5}}>{['APPROVED','REJECTED','NEEDS_EVIDENCE','UNRESOLVED'].map(st=><button style={btn} key={st} onClick={()=>resolveReview(x.id,st)}>{st}</button>)}</div>}</div>)}</>}</div>}
      </section>
      {tab==='ask'&&<form onSubmit={ask} style={{padding:10,borderTop:'1px solid #e5eaee',display:'flex',gap:7}}><input value={q} onChange={e=>setQ(e.target.value)} placeholder={studioOpen?'Ask about this simulation step…':'Ask Atlas…'} style={{...inp,flex:1}}/><button style={btn} disabled={busy}>{busy?'…':'Ask'}</button></form>}
    </aside>}
    {!panelOpen&&<button onClick={()=>setPanelOpen(true)} aria-label="Open Atlas Intelligence" style={{position:'fixed',right:14,top:54,zIndex:9999,padding:'9px 12px',borderRadius:18,border:'1px solid #0a91ae',background:'#fff',color:'#07566b',fontWeight:700,boxShadow:'0 4px 16px rgba(0,0,0,.16)'}}>Ask Atlas</button>}
  </main>
}
