export const AGENTS={
  orchestrator:{name:'Orchestrator',mode:'supervisor',write:false,purpose:'Route intent, invoke the minimum specialist set, enforce grounding and final validation.'},
  inputQuality:{name:'Input Quality / Trust Gate',mode:'validator',write:false,purpose:'Accept, quarantine or reject chat/document input before downstream agents.'},
  atlas:{name:'Atlas Knowledge',mode:'read',write:false,purpose:'Answer only from governed Atlas content.'},
  explainer:{name:'Atlas Explainer',mode:'read',write:false,purpose:'Resolve Atlas taxonomy/provenance first, then explain the governed concept in simple real-world language. Ask clarification when namespaces remain ambiguous.'},
  navigator:{name:'Navigator',mode:'ui-state',write:false,purpose:'Temporary focus/highlight/open/trace/reset commands against existing Atlas IDs.'},
  evidence:{name:'Evidence',mode:'read',write:false,purpose:'Trace claims to governed process/source IDs and claim boundaries.'},
  simulator:{name:'Flow Simulator',mode:'ui-state',write:false,purpose:'Play existing governed execution graphs or workspace views without mutating Atlas.'},
  sourceConflict:{name:'Source Conflict',mode:'read',write:false,purpose:'Surface differing source mappings and claim boundaries without silent reconciliation.'},
  compare:{name:'Compare',mode:'read',write:false,purpose:'Compare governed processes/views without inventing facts.'},
  impact:{name:'Impact',mode:'read',write:false,purpose:'Trace upstream/downstream consequences using process graph relationships.'},
  exception:{name:'Exception',mode:'read',write:false,purpose:'Explain exception, escalation, retry and recovery paths.'},
  lineage:{name:'Lineage',mode:'read',write:false,purpose:'Trace documents, identifiers, objects, producers, authorities and consumers.'},
  actors:{name:'Actor Responsibility',mode:'read',write:false,purpose:'Explain performer, owner, custody, decision and exception responsibility.'},
  systems:{name:'System Interaction',mode:'read',write:false,purpose:'Explain authoritative systems, producers, consumers and interfaces.'},
  regulatory:{name:'Regulatory Overlay',mode:'read',write:false,purpose:'Explain only source-backed applicability and conditional overlays.'},
  enterprise:{name:'Enterprise Dependency',mode:'read',write:false,purpose:'Trace enterprise lenses plus upstream/downstream relationships.'},
  opportunity:{name:'Opportunity Discovery',mode:'advisory',write:false,purpose:'Generate labelled hypotheses from Atlas/client evidence only.'},
  solution:{name:'Solution Pattern',mode:'advisory',write:false,purpose:'Classify intervention patterns separately from source-native process content.'},
  risk:{name:'Control & Risk',mode:'read',write:false,purpose:'Surface controls, decision rights, evidence and human approval needs.'},
  audit:{name:'Audit',mode:'validator',write:false,purpose:'Reject unsupported claims, invalid UI actions, ontology leakage and mutation attempts.'},
  coverage:{name:'Coverage',mode:'read',write:false,purpose:'Identify explicit mapped coverage versus research-required areas.'},
  documentIntake:{name:'Document Intake',mode:'workspace-proposal',write:false,purpose:'Extract claim-level evidence into a human-review preview before workspace commit.'},
  clientResearch:{name:'Client Research',mode:'read',write:false,purpose:'Research approved public sources and create PUBLICLY_EVIDENCED candidate claims only.'},
  evidenceValidation:{name:'Client Evidence & Validation',mode:'validator',write:false,purpose:'Validate provenance, confidence, contradictions and promotion rules.'},
  clientMapping:{name:'Client Mapping',mode:'workspace',write:false,purpose:'Map approved client facts onto Atlas concepts in the isolated workspace only.'},
  discovery:{name:'Discovery',mode:'advisory',write:false,purpose:'Find unknown/reference-only areas and generate targeted discovery questions.'},
  deviation:{name:'Deviation',mode:'read',write:false,purpose:'Compare AS-IS facts with Atlas reference without treating difference as defect.'},
  gap:{name:'Gap & Whitespace',mode:'advisory',write:false,purpose:'Separate validated issues, potential gaps and discovery gaps.'},
  futureState:{name:'Future-State Designer',mode:'advisory',write:false,purpose:'Create TO-BE hypotheses in workspace only.'},
  scenarioValidation:{name:'Scenario Validation',mode:'validator',write:false,purpose:'Enforce evidence states, process-order rules and Atlas integrity.'},
  humanReview:{name:'Human Review Inbox',mode:'governance',write:false,purpose:'Queue contradictions, low-confidence evidence, proposed corrections and unresolved issues for human disposition.'}
};
export const WRITE_CAPABLE_AGENTS=[];
export const DEFERRED={atlasAutoCorrection:true,automaticReferenceScenarioPromotion:true,automaticClientFactConfirmation:true};
