import { randomUUID } from "node:crypto";
import {
  isAgentFailure,
  recordedToolReplies,
  resolveLimits,
  spendOf,
  workSchema,
  zeroSpend,
  type AccessPass,
  type CaseRecord,
  type DraftRunEvent,
  type Ending,
  type EngineConfig,
  type Limits,
  type LimitsOverride,
  type Manifest,
  type OrgAiProvider,
  type RunEvent,
  type Spend,
  type Start,
  type Work,
} from "@malkom/agenticai-contract";
import { engineConfig as buildEngineConfig } from "@malkom/agenticai-contract";
import { Gateway, callKey, redactorFor, type GatewayTool } from "@malkom/agenticai-gateway";
import type { Adapter, AdapterRegistry } from "@malkom/agenticai-adapters";
import { closeRunSpan, keepsFullTrace, recordEventOnSpan, startRunSpan, tracerFor } from "./telemetry.js";

/**
 * The host integration — the one seam the host implements to run agents.
 *
 * The engine is the definition centre. It never learns which model, whose
 * key, or where it is deployed. Everything it needs to touch the outside
 * world, the host supplies through this interface: an opaque AI-provider
 * handle, the gateway tools (generated by the host from its own org config
 * and data doors), somewhere to write run events, and the framework adapters
 * installed here. Command implements it one way, the client runtime another,
 * a test host a third — the engine cannot tell them apart, and does not try.
 */
export interface HostIntegration {
  /**
   * The org's AI provider for this agent — an opaque model handle plus prices.
   * The engine passes the handle to the adapter and counts the prices; it
   * never inspects the model or names it.
   */
  provider(agent: {
    readonly id: string;
    readonly version: string;
  }): OrgAiProvider | Promise<OrgAiProvider>;
  /**
   * The gateway tools this agent may use — the host generates them from its
   * org config and its own data doors. The engine offers exactly these and
   * blocks everything else at the gateway.
   */
  tools(agent: Manifest): readonly GatewayTool[] | Promise<readonly GatewayTool[]>;
  /**
   * Where a run event is written — one at a time, awaited, before the next
   * step starts. This is what makes resume and exact replay possible.
   */
  keep(event: RunEvent): void | Promise<void>;
  /** The framework adapters installed on this host. */
  readonly adapters: AdapterRegistry;
  /** The clock. Supplied so a run stays replayable and testable. */
  now?(): number;
}

/** What a host asks the engine to run: one agent on one case. */
export interface RunRequest {
  readonly manifest: Manifest;
  readonly caseRecord: CaseRecord;
  /** The engine's configuration; every default the host cares to change. */
  readonly engineConfig?: EngineConfig;
  /** This org's overrides on the manifest's limits, set at attach time. */
  readonly overrides?: LimitsOverride;
  /** True when this run must change nothing. The pass blocks all writes. */
  readonly shadow?: boolean;
  /** Continue an earlier run from its last written step. */
  readonly resume?: { readonly runId: string; readonly events: readonly RunEvent[] };
  /**
   * How the runner learns what an agent has written onto the case, so the
   * work survives a limit hit or a crash. The default recognises the
   * gateway's own "write-fields" tool; a host with different doors overrides
   * it. Return null for a call that writes nothing.
   */
  workFromCall?(tool: string, args: Record<string, unknown>): Partial<Work> | null;
}

/**
 * The runner — runs agents. Retries, timeouts, resume, park, spend limits:
 * all of it lives here, not in agent code. Agents stay simple; the engine
 * handles the hard parts.
 *
 *   Retries are configured, and split by type of failure. A network error or
 *   a dead AI endpoint is worth retrying. A wrong answer is not.
 *
 *   Three limits per run: a timeout per step, a total time limit, and a money
 *   limit. Hitting any limit is a normal ending, not a crash — the case goes
 *   to a person, with the agent's work attached. Never silently overspend.
 *
 *   Every step is written to the event log before the next step starts. If a
 *   machine dies mid-run, the run continues from the last written step.
 *
 *   The run always ends one of the four ways. There is no fifth.
 */

/**
 * The composed inputs of one run — the engine-internal shape after the host
 * integration has been resolved to a concrete adapter, tools and provider.
 * Not part of the public surface: hosts speak `RunRequest` + `HostIntegration`.
 */
interface RunOptions {
  readonly manifest: Manifest;
  readonly caseRecord: CaseRecord;
  readonly adapter: Adapter;
  /** The gateway's tools, generated from this org's config. */
  readonly tools: readonly GatewayTool[];
  /** This org's AI provider — an Integration, set per org. */
  readonly aiProvider: OrgAiProvider;
  /** The engine's configuration; every default the host cares to change. */
  readonly engineConfig?: EngineConfig;
  /** This org's overrides on the manifest's limits, set at attach time. */
  readonly overrides?: LimitsOverride;
  /** True when this run must change nothing. The pass blocks all writes. */
  readonly shadow?: boolean;
  /** Continue an earlier run from its last written step. */
  readonly resume?: { readonly runId: string; readonly events: readonly RunEvent[] };
  /**
   * The event log sink. Awaited on every event, so every step is written
   * before the next one starts — this is what makes resume possible.
   */
  keep(event: RunEvent): Promise<void>;
  /**
   * How the runner learns what an agent has written onto the case, so the
   * work survives a limit hit or a crash. The default recognises the
   * gateway's own "write-fields" tool; a host with different doors overrides
   * it. Return null for a call that writes nothing.
   */
  workFromCall?(tool: string, args: Record<string, unknown>): Partial<Work> | null;
  now?(): number;
}

export interface RunReport {
  readonly runId: string;
  readonly ending: Ending;
  readonly events: readonly RunEvent[];
  readonly spend: Spend;
  readonly attempts: number;
  /** Whether this run kept a full trace, per the manifest's tracePercent. */
  readonly traced: boolean;
  readonly pass: AccessPass;
}

const defaultWorkFromCall = (tool: string, args: Record<string, unknown>): Partial<Work> | null => {
  if (tool !== "write-fields") return null;
  const fields = args["fields"];
  const confidence = args["confidence"];
  return {
    fields: (fields ?? {}) as Record<string, unknown>,
    confidence: (confidence ?? {}) as Record<string, number>,
  };
};

const mergeWork = (base: Work, over: Work): Work => ({
  fields: { ...base.fields, ...over.fields },
  confidence: { ...base.confidence, ...over.confidence },
  tried: [...base.tried, ...over.tried],
  notes: [...base.notes, ...over.notes],
});

/**
 * Does "done" count? The minimum confidence needed on each output field is a
 * manifest number; the runner grades the ending against it, independently of
 * the agent's own claim. Never silently guess.
 */
const shortfallsOf = (manifest: Manifest, work: Work): string[] => {
  const shortfalls: string[] = [];
  for (const out of manifest.output) {
    const value = work.fields[out.field];
    if (value === undefined || value === null || value === "") {
      shortfalls.push(`"${out.field}" was not filled`);
      continue;
    }
    const confidence = work.confidence[out.field] ?? 0;
    if (confidence < out.minConfidence) {
      shortfalls.push(
        `"${out.field}" came back at confidence ${confidence.toFixed(2)}, under its ${out.minConfidence} floor`,
      );
    }
  }
  return shortfalls;
};

/**
 * Run one agent. The public entry: the host hands a request and its
 * integration, and the engine resolves the adapter, the provider and the
 * tools from the host before running.
 */
export const runAgent = async (request: RunRequest, host: HostIntegration): Promise<RunReport> => {
  const adapter = host.adapters.get(request.manifest.container.adapter);
  if (adapter === undefined) {
    throw new Error(
      `agent "${request.manifest.id}" wants the "${request.manifest.container.adapter}" adapter, ` +
        `and this host has none (it has: ${host.adapters.names().join(", ") || "nothing"})`,
    );
  }
  const [aiProvider, tools] = await Promise.all([
    Promise.resolve(host.provider({ id: request.manifest.id, version: request.manifest.version })),
    Promise.resolve(host.tools(request.manifest)),
  ]);
  return runAgentWith({
    manifest: request.manifest,
    caseRecord: request.caseRecord,
    adapter,
    tools,
    aiProvider,
    keep: async (event) => {
      await host.keep(event);
    },
    ...(request.engineConfig !== undefined ? { engineConfig: request.engineConfig } : {}),
    ...(request.overrides !== undefined ? { overrides: request.overrides } : {}),
    ...(request.shadow !== undefined ? { shadow: request.shadow } : {}),
    ...(request.resume !== undefined ? { resume: request.resume } : {}),
    ...(request.workFromCall !== undefined ? { workFromCall: request.workFromCall } : {}),
    ...(host.now !== undefined ? { now: host.now } : {}),
  });
};

/**
 * The run itself, over already-resolved inputs. Engine-internal — the
 * pipeline uses it directly so it can inject helper tools per agent. Not
 * exported from the package.
 */
export const runAgentWith = async (options: RunOptions): Promise<RunReport> => {
  const now = options.now ?? Date.now;
  const config = options.engineConfig ?? buildEngineConfig();
  const manifest = options.manifest;
  const limits: Limits = resolveLimits(manifest.limits, options.overrides);
  const shadow = options.shadow ?? false;
  const workFromCall = options.workFromCall ?? defaultWorkFromCall;

  const runId = options.resume?.runId ?? randomUUID();
  const events: RunEvent[] = options.resume !== undefined ? [...options.resume.events] : [];
  const priorSpend = options.resume !== undefined ? spendOf(options.resume.events) : zeroSpend();
  const startedAt = now();

  const redact = redactorFor(manifest.telemetry.redact);
  const tracer = tracerFor();
  const span = startRunSpan(tracer, { runId, manifest, caseRecord: options.caseRecord, shadow });

  /** The work the agent has put through the gateway, kept unredacted in memory
   *  so a limit hit still hands a person everything the agent worked out. */
  let written: Work = workSchema.parse({});

  /* -------------------- limits: the three ceilings -------------------- */

  const controller = new AbortController();
  let stopped: string | null = null;
  const stop = (why: string): void => {
    if (stopped !== null) return;
    stopped = why;
    controller.abort(new Error(why));
  };

  let money = priorSpend.money;
  let modelSteps = 0;

  const runTimer = setTimeout(
    () => stop("It hit the total time limit for the run."),
    Math.max(0, limits.runTimeoutMs - priorSpend.elapsedMs),
  );
  runTimer.unref?.();

  let stepTimer: ReturnType<typeof setTimeout> | undefined;
  const armStepTimer = (): void => {
    if (stepTimer !== undefined) clearTimeout(stepTimer);
    stepTimer = setTimeout(
      () => stop("A step took longer than the timeout per step."),
      limits.stepTimeoutMs,
    );
    stepTimer.unref?.();
  };

  /* ------------- the event log: every step written before the next ------------- */

  const emit = async (draft: DraftRunEvent): Promise<void> => {
    const event = { ...draft, runId, seq: events.length } as RunEvent;
    events.push(event);
    await options.keep(event);
    recordEventOnSpan(span, event);

    // The ceilings are watched where the evidence appears: on the log itself,
    // which is what makes them hold for any adapter, in any language.
    if (event.type === "model.replied") {
      money += event.money;
      modelSteps += 1;
      if (money > limits.moneyLimit) stop("It hit the money limit for the run.");
      if (modelSteps >= config.runner.maxSteps) stop("It hit the step ceiling for the run.");
    }
    armStepTimer();
  };

  /* ------------------------- the access pass -------------------------- */

  const issuedAt = Math.floor(startedAt / 1000);
  const pass: AccessPass = {
    format: 1,
    passId: randomUUID(),
    runId,
    org: options.caseRecord.org,
    taskId: options.caseRecord.taskId,
    agent: { id: manifest.id, version: manifest.version },
    tools: manifest.tools.map((tool) => tool.name),
    issuedAt,
    expiresAt: issuedAt + config.pass.validityMinutes * 60,
    shadow,
  };

  /* ----- the gateway, with the agent's writes captured before redaction ----- */

  const wrappedTools: GatewayTool[] = options.tools.map((tool) => ({
    ...tool,
    run: async (args: Record<string, unknown>) => {
      const partial = workFromCall(tool.name, args);
      if (partial !== null) written = mergeWork(written, workSchema.parse({ ...partial }));
      return tool.run(args);
    },
  }));

  const gateway = new Gateway({
    tools: wrappedTools,
    pass,
    record: emit,
    redact,
    stepTimeoutMs: limits.stepTimeoutMs,
    now,
    ...(options.resume !== undefined
      ? { recorded: recordedToolReplies(options.resume.events, callKey) }
      : {}),
  });

  /* ------------------------------ start ------------------------------- */

  if (options.resume === undefined) {
    await emit({
      type: "run.started",
      at: new Date(startedAt).toISOString(),
      agent: { id: manifest.id, version: manifest.version, label: manifest.label },
      org: options.caseRecord.org,
      taskId: options.caseRecord.taskId,
      queue: options.caseRecord.queue,
      ...(options.caseRecord.subQueue !== undefined ? { subQueue: options.caseRecord.subQueue } : {}),
      passId: pass.passId,
      shadow,
      goal: manifest.goal,
    });
  } else {
    await emit({
      type: "noted",
      at: new Date(startedAt).toISOString(),
      step: 0,
      note: "The run continues from the last written step.",
    });
  }

  const start: Start = {
    manifest,
    goal: manifest.goal,
    caseRecord: options.caseRecord,
    pass,
    tools: gateway.offered(),
    limits,
    shadow,
    aiProvider: options.aiProvider,
    signal: controller.signal,
    report: emit,
    call: (tool, args) => gateway.call(tool, args),
  };

  /* --------------- run, with retries split by type of failure --------------- */

  armStepTimer();
  let attempts = 0;
  let ending: Ending | null = null;

  while (ending === null) {
    attempts += 1;
    try {
      ending = await options.adapter.start(start);
    } catch (error) {
      if (stopped !== null) {
        // A limit was hit. A normal ending, not a crash: the case goes to a
        // person, with everything the agent worked out attached.
        ending = { ending: "handover", whyStopped: stopped, work: written };
        break;
      }
      const failure = isAgentFailure(error) ? error : null;
      if (failure !== null && limits.retry.on.includes(failure.failure) && attempts <= limits.retry.times) {
        await emit({
          type: "run.retried",
          at: new Date(now()).toISOString(),
          failure: failure.failure,
          attempt: attempts,
          delayMs: limits.retry.delayMs,
          because: failure.message.slice(0, 300),
        });
        await new Promise((resolve) => {
          const timer = setTimeout(resolve, limits.retry.delayMs);
          timer.unref?.();
        });
        continue;
      }
      const whyStopped =
        failure !== null
          ? failure.message.slice(0, 300)
          : `The agent's code failed: ${error instanceof Error ? error.message : String(error)}`.slice(0, 300);
      ending = { ending: "handover", whyStopped, work: written };
      break;
    }

    // The agent's ending carries its work; the gateway saw its writes too.
    // Merge them, so nothing worked out is lost whichever path recorded it.
    ending = { ...ending, work: mergeWork(written, ending.work) };

    // Grade "done" against the manifest's confidence floors — independently
    // of the agent's own claim. A wrong answer is a type of failure: retried
    // only if the manifest says so, and never by default.
    if (ending.ending === "done") {
      const shortfalls = shortfallsOf(manifest, ending.work);
      if (shortfalls.length > 0) {
        if (limits.retry.on.includes("wrong-answer") && attempts <= limits.retry.times) {
          await emit({
            type: "run.retried",
            at: new Date(now()).toISOString(),
            failure: "wrong-answer",
            attempt: attempts,
            delayMs: limits.retry.delayMs,
            because: shortfalls.join("; ").slice(0, 300),
          });
          written = ending.work;
          ending = null;
          await new Promise((resolve) => {
            const timer = setTimeout(resolve, limits.retry.delayMs);
            timer.unref?.();
          });
          continue;
        }
        ending = {
          ending: "handover",
          whyStopped: `It said done, but ${shortfalls.join("; ")}.`.slice(0, 300),
          work: ending.work,
        };
      }
    }
  }

  /* ------------------------------ ended ------------------------------- */

  clearTimeout(runTimer);

  const tallied = spendOf(events);
  const spend: Spend = {
    money,
    tokensIn: tallied.tokensIn,
    tokensOut: tallied.tokensOut,
    toolCalls: gateway.calls() + priorSpend.toolCalls,
    elapsedMs: priorSpend.elapsedMs + (now() - startedAt),
  };

  await emit({
    type: "run.ended",
    at: new Date(now()).toISOString(),
    outcome: ending,
    spend,
  });
  if (stepTimer !== undefined) clearTimeout(stepTimer);

  closeRunSpan(span, ending, spend, attempts);

  return {
    runId,
    ending,
    events,
    spend,
    attempts,
    traced: keepsFullTrace(runId, manifest.telemetry.tracePercent),
    pass,
  };
};
