create table if not exists public.atlas_workspaces(
 id uuid primary key default gen_random_uuid(), name text not null, status text not null default 'ACTIVE', atlas_release_id text not null,
 created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.atlas_workspace_members(
 workspace_id uuid not null references public.atlas_workspaces(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade,
 role text not null default 'PILOT_USER' check(role in ('OWNER','ADMIN','PILOT_USER','VIEWER')), status text not null default 'ACTIVE', created_at timestamptz not null default now(), primary key(workspace_id,user_id)
);
create table if not exists public.atlas_client_states(
 workspace_id uuid primary key references public.atlas_workspaces(id) on delete cascade, state jsonb not null default '{}'::jsonb, atlas_release_id text not null, updated_at timestamptz not null default now()
);
create table if not exists public.atlas_saved_views(
 id uuid primary key default gen_random_uuid(), workspace_id uuid not null references public.atlas_workspaces(id) on delete cascade, name text not null,
 configuration jsonb not null default '{}'::jsonb, atlas_release_id text not null, created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.atlas_audit_events(
 id bigint generated by default as identity primary key, workspace_id uuid not null references public.atlas_workspaces(id) on delete cascade, actor_id uuid references auth.users(id), event_type text not null, entity_type text, entity_key text, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);
create or replace function public.atlas_add_owner() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.atlas_workspace_members(workspace_id,user_id,role) values(new.id,new.created_by,'OWNER') on conflict do nothing; return new; end $$;
drop trigger if exists atlas_workspaces_add_owner on public.atlas_workspaces;create trigger atlas_workspaces_add_owner after insert on public.atlas_workspaces for each row execute function public.atlas_add_owner();
alter table public.atlas_workspaces enable row level security;alter table public.atlas_workspace_members enable row level security;alter table public.atlas_client_states enable row level security;alter table public.atlas_saved_views enable row level security;alter table public.atlas_audit_events enable row level security;
create policy atlas_workspaces_select on public.atlas_workspaces for select using(public.atlas_is_workspace_member(id) or created_by=auth.uid());
create policy atlas_workspaces_insert on public.atlas_workspaces for insert with check(created_by=auth.uid());
create policy atlas_workspaces_update on public.atlas_workspaces for update using(public.atlas_is_workspace_manager(id));
create policy atlas_members_select on public.atlas_workspace_members for select using(public.atlas_is_workspace_member(workspace_id) or user_id=auth.uid());
create policy atlas_members_manage on public.atlas_workspace_members for all using(public.atlas_is_workspace_manager(workspace_id)) with check(public.atlas_is_workspace_manager(workspace_id));
create policy atlas_client_state_member on public.atlas_client_states for all using(public.atlas_is_workspace_member(workspace_id)) with check(public.atlas_is_workspace_member(workspace_id));
create policy atlas_saved_views_member on public.atlas_saved_views for all using(public.atlas_is_workspace_member(workspace_id)) with check(public.atlas_is_workspace_member(workspace_id));
create policy atlas_audit_select on public.atlas_audit_events for select using(public.atlas_is_workspace_member(workspace_id));
create policy atlas_audit_insert on public.atlas_audit_events for insert with check(public.atlas_is_workspace_member(workspace_id) and (actor_id=auth.uid() or actor_id is null));
